FROM mcr.microsoft.com/dotnet/aspnet:8.0-alpine AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:8.0-alpine AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src

COPY ["./app/server/Contract/Contract/Published", "Contract/"]
COPY ["./app/server/UploadFileService/src/UploadFileService.API/UploadFileService.API.csproj", "./UploadFileService.API/"]
COPY ["./app/server/UploadFileService/src/UploadFileService.Application/UploadFileService.Application.csproj", "./UploadFileService.Application/"]
COPY ["./app/server/UploadFileService/src/UploadFileService.Domain/UploadFileService.Domain.csproj", "./UploadFileService.Domain/"]
COPY ["./app/server/UploadFileService/src/UploadFileService.Infrastructure/UploadFileService.Infrastructure.csproj", "./UploadFileService.Infrastructure/"]

WORKDIR "/src/UploadFileService.API"
RUN dotnet restore --verbosity normal
COPY ["./app/server/UploadFileService/src","/src"]
RUN dotnet build -c $BUILD_CONFIGURATION -o /app/build

FROM build AS publish
# Have to add work dir, because dotnet publish will scan entire fs, make the docker hang with NAT network
WORKDIR "/src/UploadFileService.API"
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .

RUN chown -R app:app /app
USER app

ENTRYPOINT ["dotnet", "UploadFileService.API.dll"]
