#See https://aka.ms/customizecontainer to learn how to customize your debug container and how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
USER app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
# Copy pre-build lib
COPY ["./data/nuget", "./nuget"]

COPY ["./app/server/UploadFileService/src/UploadFileService.API/UploadFileService.API.csproj", "./UploadFileService.API/"]
COPY ["./app/server/UploadFileService/src/UploadFileService.Application/UploadFileService.Application.csproj", "./UploadFileService.Application/"]
COPY ["./app/server/UploadFileService/src/UploadFileService.Domain/UploadFileService.Domain.csproj", "./UploadFileService.Domain/"]
COPY ["./app/server/UploadFileService/src/UploadFileService.Infrastructure/UploadFileService.Infrastructure.csproj", "./UploadFileService.Infrastructure/"]
COPY ["./app/server/Contract/Contract/Published", "Contract/"]

WORKDIR "/src/UploadFileService.API"
RUN dotnet restore --packages "../nuget" --verbosity normal
COPY ["./app/server/UploadFileService/src","/src"]

ENTRYPOINT ["dotnet", "watch", "run", "--no-restore"]