@startuml Sequence
title "Request update identifier diagram"

<style>
  sequenceDiagram {
    reference {
      BackGroundColor white
    }
}
</style>

actor User
activate User

boundary MobileUI
participant "<<coordinator>>\nApiGateWay" as ApiGateway
participant "<<service>>\nIdentityService" as IdentityService
participant "<<coordinator>>\nRabbitmq" as Rabbitmq
database Postgresql

User -> MobileUI ++: 1. After user click update icon\n in account setting screen
MobileUI -> ApiGateway ++: 2. Request update identifier

activate IdentityService
ref over ApiGateway, IdentityService: 3. Verify Access Token
ApiGateway -[hidden]-> IdentityService
deactivate IdentityService

ApiGateway -> IdentityService ++: 4. Forward request
IdentityService -> Postgresql ++: 5. Get account data
IdentityService <-- Postgresql --: 6. Return response

alt if account is null
  ApiGateway <-- IdentityService: 7A. Return not found error
  MobileUI <-- ApiGateway: 7A.1. Forward response
  User <-- MobileUI: 7A.2. Display error
else
  IdentityService -> Postgresql ++: 8. Update Account
  IdentityService <-- Postgresql --: 9. Return response
  IdentityService --> Rabbitmq ++: 10. Publish "UserSendOTPEvent" event <<Async>>
  activate Rabbitmq
  ref over Rabbitmq: 11. User send OTP event
  IdentityService -[hidden]-> Rabbitmq
  deactivate Rabbitmq
  destroy Rabbitmq

  ApiGateway <-- IdentityService--: 12. return success status code
  MobileUI <-- ApiGateway --: 13. Forward response
  User <-- MobileUI --: 14. Redirect user to verify OTP screen
  deactivate User
end

@enduml
