@startuml Sequence
title "Get user's report detail"

' Style section
<style>
  sequenceDiagram {
    reference {
      BackGroundColor white
    }
}
</style>

actor Admin
activate Admin

boundary WebsiteUI
participant "<<coordinator>>\nApiGateway" as ApiGateway
participant "<<service>>\n UserService" as UserService
participant "<<service>>\n IdentityService" as IdentityService
database Postgresql

Admin -> WebsiteUI ++: 1. Enter user detail screen
WebsiteUI -> ApiGateway ++: 2. Get user's report detail

activate IdentityService
ref over ApiGateway, IdentityService: 3. Get access token
ApiGateway -[hidden]-> IdentityService
deactivate IdentityService

alt Current user is not admin
    WebsiteUI <-- ApiGateway: 4A. Return error message
    Admin <-- WebsiteUI: 4A.1. Display error message
else Current user is admin
    ApiGateway -> UserService ++: 5. Forward request
    UserService -> Postgresql ++: 6. Query data
    UserService <-- Postgresql--: 7. Return response
    alt User reports list is empty
        ApiGateway <-- UserService: 8A. Return empty list
        WebsiteUI <-- ApiGateway: 8A.1. Foward response
        Admin <-- WebsiteUI: 8A.2. Display empty list
    else User reports list is not empty
        ApiGateway <-- UserService--: 9. Return user reports list
        WebsiteUI <-- ApiGateway--: 10. Forward response
        Admin <-- WebsiteUI--: 11. Display user reports list
        deactivate Admin
    end alt
end alt
@enduml