@startuml Sequence
title "Vote recipe"
<style>
  sequenceDiagram {
    reference {
      BackGroundColor white
    }
}
</style>

actor User
boundary MobileUI
participant "<<cordinator>>\nApiGateway" as ApiGateway
participant "<<service>>\n RecipeService" as RecipeService
database MongoDB

User -> MobileUI++: 1. Touch on upvote or downvote icon \n in a recipe feed or recipe detail screen

MobileUI -> ApiGateway++: 2. Vote recipe

ref over ApiGateway: 3. Verify access token

ApiGateway -> RecipeService++: 4. Forward request

database MongoDB
RecipeService -> MongoDB++: 5. Query and insert data
RecipeService <-- MongoDB--: 6. Return response

ApiGateway <-- RecipeService--: 7. Return recipe vote
MobileUI <-- ApiGateway--: 8. Forward response
User <-- MobileUI--: 9. Display recipe vote
@enduml
