@startuml ClassDiagram
!include doc/SDS/CommonClassDiagram/UnitOfWork.plantuml
!include doc/SDS/CommonClassDiagram/ResultAndError.plantuml
!include doc/SDS/CommonClassDiagram/Recipe/RecipeDbContext.plantuml
skinparam classAttributeIconSize 0
skinparam linetype polyline
skinparam nodesep 50
skinparam ranksep 50
skinparam classAttributeIconSize 0
hide circle

class BaseApiController {
    #_sender: ISender
    #_httpContextAccessor: HttpContextAccessor
}

class RecipeController {
    +UserReportRecipe(userReportRecipeDTO : UserReportRecipeDTO): async Task<IActionResult>
}

class UserReportRecipeCommand {
    +ReporterId: Guid
    +RecipeId: Guid
    +ReasonCodes : List<string>
    +AdditionalDetails: string
}

class UserReportRecipeCommandHandler {
    -_context: IApplicationDbContext
    -_unitOfWork: IUnitOfWork
    +UserReportRecipeCommandHandler(context : IApplicationDbContext, unitOfWork : IUnitOfWork)
    +Handle(request : UserReportRecipeCommand, cancellationToken : CancellationToken): async Task<Result<UserReportRecipeResponse?>> 
}

class UserReportRecipeDTO{
    +RecipeId: Guid
    +ReasonCodes : List<string>
    +AdditionalDetails: string
}

class UserReportRecipeResponse{
    +UserReportRecipe: UserReportRecipe
    +IsRemoved: bool
}

UserReportRecipeResponse "1"--"1" UserReportRecipe

class RecipeError {
    {static} +NotFound: Error
    {static} +AddRecipeFail: Error
    {static} +DeleteRecipeFail: Error
    {static} +UpdateRecipeFail: Error
}

' =========== Library class ===========
interface "IRequest<TResponse>" #black;line:white;text:white
interface "IRequestHandler<TRequest, TResponse>" #black;line:white;text:white
' =========== Library class ===========

RecipeController --|> BaseApiController
RecipeController "1"--"1" UserReportRecipeDTO
RecipeController "1"--"1" UserReportRecipeCommand

UserReportRecipeCommand --|> "IRequest<TResponse>"

UserReportRecipeCommandHandler --|> "IRequestHandler<TRequest, TResponse>"
UserReportRecipeCommandHandler "1"--"1" UserReportRecipeCommand
UserReportRecipeCommandHandler "1"--"1" UserReportRecipeResponse
UserReportRecipeCommandHandler "1"--"1" Result
UserReportRecipeCommandHandler "1" o-- "1" IUnitOfWork
UserReportRecipeCommandHandler "1" o-- "1" IApplicationDbContext
UserReportRecipeCommandHandler "1"--"1..*" RecipeError

Error "1" --"1..*" RecipeError

@enduml