FROM mcr.microsoft.com/dotnet/aspnet:8.0-alpine AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:8.0-alpine AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src

COPY ["./app/server/Contract/Contract/Published", "Contract/"]
COPY ["./app/server/NotificationService/src/SMSWorker/SMSWorker.csproj", "SMSWorker/"]

# Building the services
WORKDIR "/src/SMSWorker"
RUN dotnet restore --verbosity normal
COPY ["./app/server/NotificationService/src/SMSWorker","/src/SMSWorker"]
RUN dotnet build -c $BUILD_CONFIGURATION -o /app/build  --verbosity normal

FROM build AS publish
# Have to add work dir, because dotnet publish will scan entire fs, make the docker hang with NAT network
WORKDIR "/src/SMSWorker"
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .

RUN chown -R app:app /app
USER app

ENTRYPOINT ["dotnet", "SMSWorker.dll"]
