FROM mcr.microsoft.com/dotnet/aspnet:8.0-alpine AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:8.0-alpine AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src

COPY ["./app/server/Contract/Contract/Published", "Contract/"]
COPY ["./app/server/TrackingService/src/TrackingService.API/TrackingService.API.csproj", "TrackingService.API/"]
COPY ["./app/server/TrackingService/src/TrackingService.Application/TrackingService.Application.csproj", "TrackingService.Application/"]
COPY ["./app/server/TrackingService/src/TrackingService.Infrastructure/TrackingService.Infrastructure.csproj", "TrackingService.Infrastructure/"]
COPY ["./app/server/TrackingService/src/TrackingService.Domain/TrackingService.Domain.csproj", "TrackingService.Domain/"]

# Building the services
WORKDIR "/src/TrackingService.API"
RUN --mount=type=cache,target=/root/.cache/.nuget \
    dotnet restore --packages "../nuget" --verbosity normal
COPY ["./app/server/TrackingService/src","/src"]
RUN --mount=type=cache,target=/root/.cache/.nuget \
    dotnet build --packages "../nuget" -c $BUILD_CONFIGURATION -o /app/build

FROM build AS publish
# Have to add work dir, because dotnet publish will scan entire fs, make the docker hang with NAT network
WORKDIR "/src/TrackingService.API"
ARG BUILD_CONFIGURATION=Release
RUN --mount=type=cache,target=/root/.cache/.nuget \
    dotnet publish --packages "../nuget" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
COPY seeds seeds

RUN chown -R app:app /app
USER app

ENTRYPOINT ["dotnet", "TrackingService.API.dll"]