#See https://aka.ms/customizecontainer to learn how to customize your debug container and how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
USER app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
# Copy pre-build lib
COPY ["./data/nuget", "./nuget"]

COPY ["./app/server/TrackingService/src/TrackingService.API/TrackingService.API.csproj", "TrackingService.API/"]
COPY ["./app/server/TrackingService/src/TrackingService.Application/TrackingService.Application.csproj", "TrackingService.Application/"]
COPY ["./app/server/TrackingService/src/TrackingService.Infrastructure/TrackingService.Infrastructure.csproj", "TrackingService.Infrastructure/"]
COPY ["./app/server/TrackingService/src/TrackingService.Domain/TrackingService.Domain.csproj", "TrackingService.Domain/"]
COPY ["./app/server/Contract/Contract/Published", "Contract/"]

# Building the services
WORKDIR "/src/TrackingService.API"
RUN dotnet restore --packages "../nuget" --verbosity normal
COPY ["./app/server/TrackingService/src","/src"]

ENTRYPOINT ["dotnet", "watch", "run", "--no-restore"]
