@startuml Sequence
title "Update comment"
<style>
  sequenceDiagram {
    reference {
      BackGroundColor white
    }
}
</style>

actor User
boundary MobileUI
participant "<<coordinator>>\nApiGateway" as ApiGateway
participant "<<service>>\n RecipeService" as RecipeService
database MongoDB

activate User
User -> MobileUI++: 1. Touch update icon under\n comment in recipe detail screen

MobileUI -> ApiGateway++: 2. Update comment

ref over ApiGateway: 3. Verify access token

ApiGateway -> RecipeService++: 4. Forward request

RecipeService -> MongoDB++: 5. Update data
RecipeService <-- MongoDB--: 6. Return response

ApiGateway <-- RecipeService--: 7. Return updated comment
MobileUI <-- ApiGateway--: 8. Forward response
User <-- MobileUI--: 9. Display updated comment \nin recipe detail screen
deactivate User

@enduml
