@startuml Sequence
title "Delete comment"
<style>
  sequenceDiagram {
    reference {
      BackGroundColor white
    }
}
</style>

actor User
boundary MobileUI
participant "<<coordinator>>\nApiGateway" as ApiGateway
participant "<<service>>\n RecipeService" as RecipeService
database MongoDB

activate User
User -> MobileUI++: 1. Touch delete icon under\n comment in recipe detail screen

MobileUI -> ApiGateway++: 2. Delete comment

ref over ApiGateway: 3. Verify access token

ApiGateway -> RecipeService++: 4. Forward request

RecipeService -> MongoDB++: 5. Delete data
RecipeService <-- MongoDB--: 6. Return response

ApiGateway <-- RecipeService--: 7. Return deleted comment
MobileUI <-- ApiGateway--: 8. Forward response
User <-- MobileUI--: 9. Display delete comment \nout of recipe detail screen
deactivate User

@enduml
