FROM mcr.microsoft.com/dotnet/aspnet:8.0-alpine AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:8.0-alpine AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src

COPY ["./app/server/Contract/Contract/Published", "Contract/"]
COPY ["./app/server/NotificationService/src/EmailWorker/EmailWorker.csproj", "EmailWorker/"]

# Building the services
WORKDIR "/src/EmailWorker"
RUN --mount=type=cache,target=/root/.cache/.nuget \
    dotnet restore --verbosity normal
COPY ["./app/server/NotificationService/src/EmailWorker","/src/EmailWorker"]
RUN --mount=type=cache,target=/root/.cache/.nuget \
    dotnet build -c $BUILD_CONFIGURATION -o /app/build  --verbosity normal

FROM build AS publish
# Have to add work dir, because dotnet publish will scan entire fs, make the docker hang with NAT network
WORKDIR "/src/EmailWorker"
ARG BUILD_CONFIGURATION=Release
RUN --mount=type=cache,target=/root/.cache/.nuget \
    dotnet publish -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .

COPY ["./data/Auth.Store", "/app/Auth.Store"]
RUN chown -R app:app /app
USER app

ENTRYPOINT ["dotnet", "EmailWorker.dll"]