[tool_alias]
maestro-runner = "github:PhenChua29/maestro-runner"

[tools]
dotnet = "8"
python = "3.11"
node = "24"
maestro-runner = { version = "latest", bin = "maestro" }
docker-cli = "latest"
infisical = "latest"
mongosh = "latest"
