@startuml ClassDiagram
!include doc/SDS/CommonClassDiagram/ServiceBus.plantuml
!include doc/SDS/CommonClassDiagram/UnitOfWork.plantuml
!include doc/SDS/CommonClassDiagram/ResultAndError.plantuml
!include doc/SDS/CommonClassDiagram/Recipe/RecipeDbContext.plantuml
skinparam classAttributeIconSize 0
skinparam linetype polyline
skinparam nodesep 50
skinparam ranksep 50
hide circle

class BaseApiController {
    #_sender: ISender
    #_httpContextAccessor: HttpContextAccessor
}

class RecipeController {
    +CommentRecipe(commentRecipeDTO : CommentRecipeDTO): async Task<IActionResult>
}

class CommentRecipeCommand {
    +Content: string
    +AccountId: Guid
    +RecipeId: Guid
}

class CommentRecipeCommandHandler {
    -_context: IApplicationDbContext
    -_unitOfWork: IUnitOfWork
    -_mapper: IMapper
    -_grpcUserClient: GrpcUserClient
    -_serviceBus: IServicebus
    +CommentRecipeCommandHandler(context : IApplicationDbContext, unitOfWork : IUnitOfWork, mapper : IMapper, grpcUserClient : GrpcUserClient, serviceBus : IServicebus)
    +Handle(request : CommentRecipeCommand, cancellationToken : CancellationToken): async Task<Result<RecipeCommentResponse?>> 
}

interface IMapper{
    #Map<TDestination>(object source): TDestination
}

class CommentRecipeDTO{
    +RecipeId: Guid
    +Content: string
}

class RecipeCommentResponse{
    +Id: Guid
    +AccountId: Guid
    +DisplayName: string
    +Content: string
    +AvatarUrl: string
    +CreatedAt: DateTime
    +UpdatedAt: DateTime
    +IsActive: bool
}

class CommentError {
    {static} +NotFound: Error
    {static} +AddCommentFail: Error
    {static} +DeleteCommentFail: Error
    {static} +UpdateCommentFail: Error
}
' =========== Microservice class ===========
together {
    class GrpcGetSimpleUsersRequest #DarkBlue;line:white;text:white
    class GrpcUserClient #DarkBlue;line:white;text:white
}


' =========== Library class ===========
interface "IRequest<TResponse>" #black;line:white;text:white
interface "IRequestHandler<TRequest, TResponse>" #black;line:white;text:white
' =========== Library class ===========

RecipeController --|> BaseApiController
RecipeController "1"--"1" CommentRecipeDTO
RecipeController "1"--"1" CommentRecipeCommand

CommentRecipeCommand ..|> "IRequest<TResponse>"

CommentRecipeCommandHandler ..|> "IRequestHandler<TRequest, TResponse>"
CommentRecipeCommandHandler "1"--"1" CommentRecipeCommand
CommentRecipeCommandHandler "1"--"1" Result
CommentRecipeCommandHandler "1"--"1..*" RecipeCommentResponse
CommentRecipeCommandHandler "1" o-- "1" IUnitOfWork
CommentRecipeCommandHandler "1" o-- "1" IApplicationDbContext
CommentRecipeCommandHandler "1" o-- "1" IMapper
CommentRecipeCommandHandler "1" o-- "1" GrpcUserClient
CommentRecipeCommandHandler "1" o-- "1" IServiceBus
CommentRecipeCommandHandler "1" --"1..*" GrpcGetSimpleUsersRequest
CommentRecipeCommandHandler "1" --"1..*" CommentError

Error "1..*" --o "1" CommentError
@enduml