@startuml Sequence
title "Comment recipe"
<style>
  sequenceDiagram {
    reference {
      BackGroundColor white
    }
}
</style>

actor User
boundary MobileUI
participant "<<coordinator>>\nApiGateway" as ApiGateway
participant "<<service>>\n RecipeService" as RecipeService
participant "<<service>>\n UserService" as UserService
database MongoDB
database Postgresql

User -> MobileUI++: 1. Enter comment in recipe detail screen

MobileUI -> ApiGateway++: 2. Comment recipe

ref over ApiGateway: 3. Verify access token

ApiGateway -> RecipeService++: 4. Forward request

RecipeService -> MongoDB++: 5. Insert data
RecipeService <-- MongoDB--: 6. Return response

RecipeService -> UserService++: 7. gRPC call to get user's \n information <<gRPC>>
UserService -> Postgresql++: 8. Query data
UserService <-- Postgresql--: 9. Return response
RecipeService <-- UserService--: 10. Return user's information <<gRPC>>

RecipeService -> Rabbitmq++: 11. Publish "NotifyUserEvent" event <<Async>>
ref over Rabbitmq: 12. NotifyUserConsumer
ApiGateway <-- RecipeService--: 13. Return recipe comment
deactivate Rabbitmq
destroy Rabbitmq
MobileUI <-- ApiGateway--: 14. Forward response
User <-- MobileUI--: 15. Display recipe comment

@enduml
