@startuml Sequence
title "Admin mark all report"

' Style section
<style>
  sequenceDiagram {
    reference {
      BackGroundColor white
    }
}
</style>

actor Admin
boundary WebsiteUI
participant "<<coordinator>>\nApiGateway" as ApiGateway
participant "<<service>>\n IdentityService" as IdentityService
participant "<<service>>\n UserService" as UserService
database Postgresql

activate Admin
Admin -> WebsiteUI ++: 1. Click on mark all complete or \n reopen all button in recipe report screen
WebsiteUI -> ApiGateway ++: 2. Admin mark all recipe report

activate IdentityService
ref over ApiGateway, IdentityService: 3. Get access token
ApiGateway -[hidden]-> IdentityService
deactivate IdentityService

alt Current user is not admin
    WebsiteUI <-- ApiGateway: 4A. Return error message
    Admin <-- WebsiteUI: 4A.1. Display error message
else Current user is admin
    ApiGateway -> UserService ++: 5. Forward request
    UserService -> Postgresql++: 6. Update data
    UserService <-- Postgresql--: 7. Return response
    ApiGateway <-- UserService: 8. Return report
    WebsiteUI <-- ApiGateway--: 9. Forward response
    Admin <-- WebsiteUI--: 10. Display marked all recipe report success message
    deactivate Admin
    UserService -> Rabbitmq: 11. Publish "AddActivityLogEvent" event <<Async>>
    deactivate UserService
    activate Rabbitmq
    ref over Rabbitmq: 12. AddActivityLogConsumers
    Rabbitmq -[hidden]> 
    destroy Rabbitmq
end alt
@enduml