@startuml ClassDiagram
!include doc/SDS/CommonClassDiagram/PaginateData.plantuml
!include doc/SDS/CommonClassDiagram/ResultAndError.plantuml
!include doc/SDS/CommonClassDiagram/Recipe/RecipeDbContext.plantuml
skinparam classAttributeIconSize 0
skinparam linetype polyline
skinparam nodesep 50
skinparam ranksep 50
skinparam classAttributeIconSize 0
hide circle

class BaseApiController {
    #_sender: ISender
    #_httpContextAccessor: HttpContextAccessor
}

class RecipeController {
    +SearchRecipe(searchRecipesDTO : SearchRecipesDTO): async Task<IActionResult>
}

class SearchRecipesQuery {
    +Skip: int
    +TagCodes: List<string>?
    +Keyword: string
    +AccountId: Guid
}

class SearchRecipesQueryHandler {
    -_context: IApplicationDbContext
    -_mapper: IMapper
    -_grpcUserClient: GrpcUserClient
    -_paginateDataUtility: IPaginateDataUtility
    +SearchRecipesQueryHandler(context : IApplicationDbContext, mapper : IMapper, grpcUserClient : GrpcUserClient, paginateDataUtility : IPaginateDataUtility)
    +Handle(request : SearchRecipesQuery, cancellationToken : CancellationToken): async Task<Result<PaginatedSearchRecipeListResponse?>> 
}

interface IMapper{
    #Map<TDestination>(object source): TDestination
}

class PaginatedSearchRecipeListResponse{
}
class BasePaginatedResponse{
    +PaginatedData : IEnumerable<Type>
    +Metadata: MetadataType?
}
PaginatedSearchRecipeListResponse --|> BasePaginatedResponse

class SearchRecipesDTO{
    +Skip: int
    +TagCodes: List<string>?
    +Keyword: string
}

class RecipeError {
    {static} +NotFound: Error
    {static} +AddRecipeFail: Error
    {static} +DeleteRecipeFail: Error
    {static} +UpdateRecipeFail: Error
}

' =========== Library class ===========
interface "IRequest<TResponse>" #black;line:white;text:white
interface "IRequestHandler<TRequest, TResponse>" #black;line:white;text:white
' =========== Library class ===========

RecipeController --|> BaseApiController
RecipeController "1"--"1" SearchRecipesDTO
RecipeController "1"--"1" SearchRecipesQuery

SearchRecipesQuery --|> "IRequest<TResponse>"
SearchRecipesQueryHandler --|> "IRequestHandler<TRequest, TResponse>"

SearchRecipesQueryHandler "1"--"1" SearchRecipesQuery
SearchRecipesQueryHandler "1"--"1" Result
SearchRecipesQueryHandler "1"--"1" PaginatedSearchRecipeListResponse
SearchRecipesQueryHandler "1"--"1" GrpcGetSimpleUsersRequest
SearchRecipesQueryHandler "1"--"1" GrpcSearchUserRequest
SearchRecipesQueryHandler "1" o-- "1" IApplicationDbContext
SearchRecipesQueryHandler "1" o-- "1" IMapper
SearchRecipesQueryHandler "1" o-- "1" GrpcUserClient
SearchRecipesQueryHandler "1" o-- "1" IPaginateDataUtility
SearchRecipesQueryHandler "1"--"1..*" RecipeError

Error "1" --"1..*" RecipeError

together {
    class GrpcSearchUserRequest #DarkBlue;line:white;text:white
    class GrpcGetSimpleUsersRequest #DarkBlue;line:white;text:white
    class GrpcUserClient #DarkBlue;line:white;text:white
}
@enduml