FROM mcr.microsoft.com/dotnet/aspnet:8.0-alpine AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:8.0-alpine AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src

RUN apk update && \
apk add --no-cache curl

COPY ["./app/server/Contract/Contract/Published", "Contract/"]
COPY ["./app/server/SignalRService/src/SignalRHub/SignalRHub.csproj", "SignalRHub/"]

# Building the services
WORKDIR "/src/SignalRHub"
RUN dotnet restore --verbosity normal
COPY ["./app/server/SignalRService/src","/src"]
RUN dotnet build -c $BUILD_CONFIGURATION -o /app/build

FROM build AS publish
# Have to add work dir, because dotnet publish will scan entire fs, make the docker hang with NAT network
WORKDIR "/src/SignalRHub"
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
RUN chown -R app:app /app
USER app

ENTRYPOINT ["dotnet", "SignalRHub.dll"]
