FROM mcr.microsoft.com/dotnet/aspnet:8.0-alpine AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:8.0-alpine AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src

COPY ["./app/server/Contract/Contract/Published", "Contract/"]
COPY ["./app/server/UserService/src/UserService.API/UserService.API.csproj", "UserService.API/"]
COPY ["./app/server/UserService/src/UserService.Application/UserService.Application.csproj", "UserService.Application/"]
COPY ["./app/server/UserService/src/UserService.Infrastructure/UserService.Infrastructure.csproj", "UserService.Infrastructure/"]
COPY ["./app/server/UserService/src/UserService.Domain/UserService.Domain.csproj", "UserService.Domain/"]

# Building the services
WORKDIR "/src/UserService.API"
RUN dotnet restore --verbosity normal
COPY ["./app/server/UserService/src","/src"]
RUN dotnet build -c $BUILD_CONFIGURATION -o /app/build

FROM build AS publish
# Have to add work dir, because dotnet publish will scan entire fs, make the docker hang with NAT network
WORKDIR "/src/UserService.API"
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
COPY seeds seeds

RUN chown -R app:app /app
USER app

ENTRYPOINT ["dotnet", "UserService.API.dll"]
