@startuml Sequence
title "Set view notification diagram"

' Style section
<style>
  sequenceDiagram {
    reference {
      BackGroundColor white
    }
}
</style>

actor User
activate User

boundary MobileUI
participant "<<coordinator>>\nApiGateway" as ApiGateway
participant "<<service>>\n IdentityService" as IdentityService
participant "<<service>>\n NotificationService" as NotificationService
database MongoDB

User -> MobileUI ++: 1. User click the notification
MobileUI -> ApiGateway ++: 2. Request set view notification

activate IdentityService
ref over ApiGateway, IdentityService: 3. Get access token
ApiGateway -[hidden]-> IdentityService
deactivate IdentityService

ApiGateway -> NotificationService ++: 4. Forward request

NotificationService -> MongoDB++: 5. Query notifications data
NotificationService <-- MongoDB--: 6. Return response

alt Notification not found
  ApiGateway <-- NotificationService: 7A. Return NotFound error
  MobileUI <-- ApiGateway: 7A.1. Forward response
  User <-- MobileUI: 7A.2. Display error message
else
  alt Recipient not found
    ApiGateway <-- NotificationService: 8A. Return NotFound error
    MobileUI <-- ApiGateway: 8A.1. Forward response
    User <-- MobileUI: 8A.2. Display error message
  else
    NotificationService -> MongoDB++: 9. Update view status
    NotificationService <-- MongoDB--: 10. Return response
    ApiGateway <-- NotificationService--: 11. Return success
    MobileUI <-- ApiGateway--: 12. Forward response
    User <-- MobileUI--: 13. Display notification list
  end
end

@enduml