---
- name: Add Infisical CLI repository
  ansible.builtin.shell: |
    curl -1sLf https://artifacts-cli.infisical.com/setup.deb.sh | bash
  register: infisical_repo
  changed_when: infisical_repo.rc == 0

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
  changed_when: false

- name: Install Infisical
  ansible.builtin.package:
    name:
      - infisical
    state: present
