---
- name: Install dependencies
  ansible.builtin.apt:
    name:
      - curl
      - bash
    state: present

- name: Add Infisical CLI repository
  ansible.builtin.shell:
    executable: bash
    cmd: |
      set -o pipefail
      curl -1sLf https://artifacts-cli.infisical.com/setup.deb.sh | bash
  register: infisical_repo
  changed_when: infisical_repo.rc == 0

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true

- name: Install Infisical
  ansible.builtin.package:
    name: infisical
