---
- name: Install dependency
  ansible.builtin.package:
    name: software-properties-common
    state: present

- name: Add python repository
  ansible.builtin.command: add-apt-repository ppa:deadsnakes/ppa -y
  register: out
  changed_when: out.rc == 0

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true

- name: Install python
  ansible.builtin.package:
    name: python3.13
    state: present

- name: Set default python version
  community.general.alternatives:
    name: python
    link: /usr/bin/python
    path: /usr/bin/python3.13
