ARG CONTRACT_IMAGE
FROM ${CONTRACT_IMAGE} AS contract

FROM mcr.microsoft.com/dotnet/aspnet:8.0-alpine AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:8.0-alpine AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src

COPY --from=contract /publish ./Contract
COPY ["./app/server/APIGateway/src/APIGateway/APIGateway.csproj", "./APIGateway/"]

WORKDIR "/src/APIGateway"
RUN dotnet restore "./APIGateway.csproj" --verbosity normal

COPY ["./app/server/APIGateway/src/APIGateway","."]
RUN dotnet build "./APIGateway.csproj" -c $BUILD_CONFIGURATION -o /app/build

FROM build AS publish
# Have to add work dir, because dotnet publish will scan entire fs, make the docker hang with NAT network
WORKDIR "/src/APIGateway"
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "./APIGateway.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false
    
FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .

RUN chown -R app:app /app
USER app

ENTRYPOINT ["dotnet", "APIGateway.dll"]
