apiVersion: batch/v1
kind: CronJob
metadata:
  name: daily-db-checker
spec:
  schedule: "0 * * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: check-mongo
              image: mongo
              envFrom: 
              - secretRef:
                  name: global-secret
              args: 
                - /bin/sh
                - -c
                - |
                  set -e
                  echo "================== 1. MONGODB Check =================="
                  echo "1.1 Total recipes count:"
                  mongosh "mongodb://$MONGO_INITDB_ROOT_USERNAME:$MONGO_INITDB_ROOT_PASSWORD@$MONGODB_HOST:$MONGODB_PORT/?authSource=admin" --eval "db = db.getSiblingDB('RecipeDB'); db.Recipe.countDocuments({})"
            - name: check-postgres
              image: postgres:17.0-alpine
              envFrom: 
              - secretRef:
                  name: global-secret
              args: 
                - /bin/sh
                - -c
                - |
                  set -e
                  echo "================== 2. POSTGRESQL Check =================="
                  echo "2.1. Total account count:"
                  PGPASSWORD="$POSTGRES_PASSWORD" \
                    psql \
                    --host="$DB_HOST"\
                    --port="$DB_PORT"\
                    --username="$POSTGRES_USER"\
                    --dbname="IdentityDB"\
                    -c "select COUNT(a.\"Id\" ) from \"Account\" a"
          restartPolicy: Never
