@startuml Sequence
title "Login sequence diagram"

actor User
boundary MobileUI
participant "<<coordinator>>\nApiGateWay" as ApiGateway
participant "<<service>>\nIdentityService" as IdentityService
database Postgresql

User -> MobileUI++: 1. Fill the login form and \n touch login button
MobileUI -> ApiGateway++: 2. Login with email\n or phone
ApiGateway -> IdentityService++: 3. Forward request
IdentityService -> Postgresql++: 4. Query to check password
IdentityService <-- Postgresql--: 5. return response

alt if the password or email or phone not correct
    ApiGateway <-- IdentityService: 6A. Return login failed error
    MobileUI <-- ApiGateway: 6A.1. Forward response
    User <-- MobileUI: 6A.2. Display error
else 
    ApiGateway <-- IdentityService--: 7. return success status code
    MobileUI <-- ApiGateway--: 8. Forward response
    User <-- MobileUI--: 9. Return access token\n and redirect user to\n community screen
end

@enduml
