@startuml Sequence
title "Unlink account diagram"

<style>
  sequenceDiagram {
    reference {
      BackGroundColor white
    }
}
</style>

actor User
boundary MobileUI
participant "<<coordinator>>\nApiGateWay" as ApiGateway
participant "<<service>>\nIdentityService" as IdentityService
database Postgresql

User -> MobileUI ++: 1. User want to unlink identifier\n in their account
MobileUI -> ApiGateway ++: 2. Request unlink account

activate IdentityService
ref over ApiGateway, IdentityService: 3. Verify Access Token
ApiGateway -[hidden]-> IdentityService
deactivate IdentityService

ApiGateway -> IdentityService ++: 4. Forward request
IdentityService -> Postgresql ++: 5. Get account data
IdentityService <-- Postgresql --: 6. Return response

alt if account is null
    ApiGateway <-- IdentityService: 7A. Return not found error
    MobileUI <-- ApiGateway: 7A.1. Forward response
    User <-- MobileUI: 7A.2. Display error alert
else
    alt if user has only 1 identifier
      ApiGateway <-- IdentityService: 8A. Return only exist 1 identifier error
      MobileUI <-- ApiGateway: 8A.1. Forward response
      User <-- MobileUI: 8A.2. Display error alert
    else
      IdentityService -> Postgresql ++: 9. Update Account
      IdentityService <-- Postgresql --: 10. Return response
      ApiGateway <-- IdentityService --: 11. Return success status code
      MobileUI <-- ApiGateway --: 12. Forward response
      User <-- MobileUI --: 13. Display alert\n unlink account successfully
    end
end

@enduml
