@startuml Sequence
title "Request change password diagram"

<style>
  sequenceDiagram {
    reference {
      BackGroundColor white
    }
}
</style>

actor User
boundary MobileUI
participant "<<coordinator>>\nApiGateWay" as ApiGateway
participant "<<service>>\nIdentityService" as IdentityService
participant "<<coordinator>>\nRabbitmq" as Rabbitmq
database Postgresql

User -> MobileUI ++: 1. After user click verify button\n in forgot password screen
MobileUI -> ApiGateway ++: 2. Request change password

ApiGateway -> IdentityService ++: 3. Forward request
IdentityService -> Postgresql ++: 4. Get account data
IdentityService <-- Postgresql --: 5. Return response

alt if account is null
  ApiGateway <-- IdentityService: 6A. Return not found error
  MobileUI <-- ApiGateway: 6A.1. Forward response
  User <-- MobileUI: 6A.2. Display error
else
  IdentityService -> Postgresql ++: 7. Update Account
  IdentityService <-- Postgresql --: 8. Return response
  IdentityService --> Rabbitmq ++: 9. Publish "UserSendOTPEvent" event <<Async>>
  activate Rabbitmq
  ref over Rabbitmq: 10. User send OTP event
  IdentityService -[hidden]-> Rabbitmq
  deactivate Rabbitmq
  destroy Rabbitmq

  ApiGateway <-- IdentityService--: 11. return success status code
  MobileUI <-- ApiGateway --: 12. Forward response
  User <-- MobileUI --: 13. Redirect user to verify OTP screen
end

@enduml
