@startuml Sequence
title "Search user view recipe detail history diagram"
' Style section
<style>
  sequenceDiagram {
    reference {
      BackGroundColor white
    }
}
</style>

actor User
activate User

boundary MobileUI
participant "<<coordinator>>\nApiGateway" as ApiGateway
participant "<<service>>\n TrackingService" as TrackingService
participant "<<service>>\n RecipeService" as RecipeService
participant "<<service>>\n UserService" as UserService
database Postgresql
database MongoDB

User -> MobileUI++: 1. User search on recipe\n history page

MobileUI -> ApiGateway++: 2. Search recipe history

ref over ApiGateway: 3. Verify access token

ApiGateway -> TrackingService++: 4. Forward request

TrackingService -> MongoDB++: 5. Query data
TrackingService <-- MongoDB--: 6. Return response

alt View list is empty
    ApiGateway <-- TrackingService: 7A. Return empty list
    MobileUI <-- ApiGateway: 7A.1. Forward response
    User <-- MobileUI: 7A.2. Display empty list
else View list is not empty
    TrackingService -> RecipeService++: 8. gRPC call to search recipe's \n information list <<gRPC>>
    RecipeService -> MongoDB++: 9. Query data
    RecipeService <-- MongoDB--: 10. Return response

    RecipeService -> UserService++: 11. gRPC call to get user's \n information list <<gRPC>>
    UserService -> Postgresql++: 12. Query data
    UserService <-- Postgresql--: 13. Return response
    RecipeService <-- UserService--: 14. Return user's \n information list <<gRPC>>

    TrackingService <-- RecipeService--: 15. Return recipe's \n information list <<gRPC>>

    ApiGateway <-- TrackingService--: 16. Return recipes list
    MobileUI <-- ApiGateway--: 17. Forward response
    User <-- MobileUI--: 18. Display recipes list
    deactivate User
end

@enduml
