FROM python:3.11-slim AS builder

ARG BASE_PROJECT_PATH=app/server/IngredientPredictService
WORKDIR /app

# Install build dependencies only
RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc \
    libjpeg-dev \
    zlib1g-dev \
    && rm -rf /var/lib/apt/lists/*

COPY $BASE_PROJECT_PATH/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

FROM python:3.11-slim
ARG BASE_PROJECT_PATH=app/server/IngredientPredictService
WORKDIR /app
EXPOSE 80

COPY $BASE_PROJECT_PATH/requirements.txt .

RUN apt-get update && apt-get install -y --no-install-recommends \
    libgl1 \  
    # This lib "libgl1-mesa-glx" no longer exist, renamed to libgl1 \
    libglib2.0-0 \
    libgomp1 \
    libsm6 \
    libxext6 \
    libxrender1 \
    && rm -rf /var/lib/apt/lists/*

COPY --from=builder /root/.local /root/.local
ENV PATH=/root/.local/bin:$PATH

COPY $BASE_PROJECT_PATH .
ENV PYTHON_ENV=production
CMD ["python", "main.py"]
