FROM python:3.11-slim
WORKDIR /app
EXPOSE 80
ARG BASE_PROJECT_PATH=app/server/IngredientPredictService
ENV PYTHONUNBUFFERED=1 \
    PIP_DISABLE_PIP_VERSION_CHECK=on \
    PYTHONDONTWRITEBYTECODE=1

RUN python -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"
RUN --mount=source=$BASE_PROJECT_PATH/requirements.txt,target=requirements.txt \
  --mount=type=cache,target=/root/.cache/pip \
  pip install -r requirements.txt

COPY $BASE_PROJECT_PATH .
ENV PYTHON_ENV=production
CMD ["python", "main.py"]
