
@startuml ClassDiagram
!include doc/SDS/CommonClassDiagram/ResultAndError.plantuml
!include doc/SDS/CommonClassDiagram/ServiceBus.plantuml
skinparam classAttributeIconSize 0
skinparam linetype polyline
skinparam nodesep 20
skinparam ranksep 20
hide circle

remove IApplicationDbContext
remove ApplicationDbContext
remove Permission
remove Group
remove RoleGroupPermission
remove IDisposable
remove DbSet<T>
remove IdentityUserLogin<T>
remove IdentityRole
remove DbContext
remove IDbContext
remove BaseEntity
remove IdentityDbContext<ApplicationAccount>

class BaseApiController {
    #_sender: ISender
    #_httpContextAccessor: HttpContextAccessor
}

class AccountController {
    +ResendEmailOTP(): async Task<IActionResult>
    +ResendPhoneOTP(): async Task<IActionResult>
}

class ResendOTPCommand {
    +AccountId: Guid
    +Method: AccountMethod 
}

class ResendOTPCommandHandler {
    -_userManager: UserManager<ApplicationAccount> 
    -_serviceBus: IServiceBus 
    +ResendOTPCommandHandler(UserManager<ApplicationAccount> userManager, IServiceBus serviceBus)
    +Handle(ResendOTPCommand request, CancellationToken cancellationToken): Task<Result> 
    {static} +ResendEmailOTP(ResendOTPCommand request, CancellationToken cancellationToken): Task<Result>
    {static} +ResendPhoneOTP(ResendOTPCommand request, CancellationToken cancellationToken): Task<Result>
}

class AccountError {
    {static} +NotFound: Error
    {static} +EmailNotFound: Error
    {static} +CreateAccountFailed: Error
    {static} +PhoneNotFound: Error
}

class OTPUtility {
    -BASE_LENGTH: int
    {static} +GenerateNumericOTP(): string
    {static} +GenerateNumericOTP(length: int): string
}

enum AccountMethod {
    Phone
    Email
    Username
    Google
}

enum VerifyAccountMethod {
    Verify,
    Unlink
}

class UserResendOTPEvent{
    + AccountId : Guid
    + Identifier : string
    + OTP : string
    + Method : AccountMethod
}

!include doc/SDS/CommonClassDiagram/Account/AccountDbContext.plantuml 
remove Permission
remove Group
remove RoleGroupPermission
remove IdentityRole
remove BaseEntity


' =========== Library class ===========
interface "IRequest<TResponse>" #black;line:white;text:white
interface "IRequestHandler<TRequest, TResponse>" #black;line:white;text:white
class "UserManager<TUser>" #black;line:white;text:white
' =========== Library class ===========

AccountController --|> BaseApiController
AccountController "1"--"1" ResendOTPCommand
ResendOTPCommand "1" o--"1" AccountMethod
ResendOTPCommand "1"--"1" VerifyAccountMethod
ResendOTPCommand --|> "IRequest<TResponse>"

ResendOTPCommandHandler --|> "IRequestHandler<TRequest, TResponse>"
ResendOTPCommandHandler "1" o--"1" ResendOTPCommand
ResendOTPCommandHandler "1" o---"1" ApplicationAccount
ResendOTPCommandHandler "1" o--"1" AccountError
ResendOTPCommandHandler "1" o--"1" UserResendOTPEvent
ResendOTPCommandHandler "1" o--"1" Result
ResendOTPCommandHandler "1" o--"1" OTPUtility
ResendOTPCommandHandler "1" o--"1" IServiceBus
ResendOTPCommandHandler "1" o--"1" "UserManager<TUser>"

Error "1" --"1..*" AccountError

UserResendOTPEvent "1" o-- "1" AccountMethod

@enduml