@startuml GrpcRecipeSerciveClassDiagram
!include doc/SDS/CommonClassDiagram/ResultAndError.plantuml
!include doc/SDS/CommonClassDiagram/Recipe/RecipeDbContext.plantuml
skinparam classAttributeIconSize 0
skinparam linetype polyline
skinparam nodesep 50
skinparam ranksep 50
skinparam classAttributeIconSize 0
hide circle

class GrpcRecipeBase #Black;line:white;text:white

class GrpcRecipeService #Green;line:white;text:white extends GrpcRecipeBase {
    #_sender: ISender
    #_logger: ILogger
    +GetAllTags(request : GrpcEmpty, context : ServerCallContext): async Task<GrpcListTagDTO>
    +GetRecipeDetails(request : GrpcRecipeIdRequest, context : ServerCallContext): async Task<GrpcRecipeDetailsDTO>
    +GetSimpleRecipes(request : GrpcGetSimpleRecipeRequest, context : ServerCallContext): async Task<GrpcMapSimpleRecipes>
    +SearchSimpleRecipes(request : GrpcGetSimpleRecipeRequest, context : ServerCallContext): async Task<GrpcMapSimpleRecipes>
}

class GetAllTagsQuery {
}
class GetAllTagsQueryHandler {
    -_context: IApplicationDbContext
    +GetAllTagsQueryHandler(context: IApplicationDbContext)
    +Handle(request : GetAllTagsQuery, cancellationToken : CancellationToken): async Task<Result<<List<Tag>>> 
}


class GetRecipeDetailForServerQuery {
    +RecipeId: Guid
}
class GetRecipeDetailForServerQueryHandler {
    -_context: IApplicationDbContext
    -_grpcAccountClient: GrpcAccountClient
    +GetRecipeDetailForServerQueryHandler(context: IApplicationDbContext, grpcAccountClient: GrpcAccountClient)
    +Handle(request : GetUserDetailsQuery, cancellationToken : CancellationToken): async Task<Result<GetUserDetailsResponse?>> 
}

class GetSimpleRecipesQuery {
    +AccountId: Guid
    +RecipeIds: HashSet<Guid>
}
class GetSimpleRecipesQueryHandler {
    -_context: IApplicationDbContext
    -_grpcUserClient: GrpcUserClient
    +GetSimpleRecipesQueryHandler(context: IApplicationDbContext, grpcUserClient: GrpcUserClient)
    +Handle(request : GetSimpleRecipesQuery, cancellationToken : CancellationToken): async Task<Result<<List<SimpleRecipeResponse>>> 
}

class SearchSimpleRecipesQuery {
    +AccountId: Guid
    +RecipeIds: HashSet<Guid>
    +Keyword: string
}
class SearchSimpleRecipesQueryHandler {
    -_context: IApplicationDbContext
    -_grpcUserClient: GrpcUserClient
    +SearchSimpleRecipesQueryHandler(context: IApplicationDbContext, grpcUserClient: GrpcUserClient)
    +Handle(request : SearchSimpleRecipesQuery, cancellationToken : CancellationToken): async Task<Result<<List<SimpleRecipeResponse>>> 
}

' Grpc DTO
class GrpcEmpty #Green;line:white;text:white{
}

class GrpcRecipeIdRequest #Green;line:white;text:white{
}

class GrpcGetSimpleRecipeRequest #Green;line:white;text:white{
}

class GrpcSearchSimpleRecipeRequest #Green;line:white;text:white{
}

' Grpc responses

class GrpcTagDTO #Green;line:white;text:white{
}

class GrpcListTagDTO #Green;line:white;text:white{
}

class GrpcMapSimpleRecipes #Green;line:white;text:white{
}

class GrpcRecipeDetailsDTO #Green;line:white;text:white{
}

class GrpcStepDTO #Green;line:white;text:white{
}

class GrpcCommentDTO #Green;line:white;text:white{
}

class GrpcSimpleRecipe #Green;line:white;text:white{
}

class GrpcMapSimpleRecipes #Green;line:white;text:white{
}

' DTO
class RecipeDetailsResponse{
    +Recipe: Recipe
    +AuthorUsername: string
    +AuthorDisplayName: string
    +AuthorAvtUrl: string
    +AuthorNumberOfFollower: int
    +Vote: enum
    +IsBookmarked: bool
    +Tags: List<Tag>
}

class SimpleRecipeResponse{
    +Id: Guid
    +AuthorId: Guid
    +RecipeImgUrl: string
    +Title: string
    +Description: string
    +AuthorDisplayName: string
    +AuthorAvtUrl: string
    +VoteDiff: int
    +NumberOfComment: int
    +Vote: enum
}

class RecipeError {
    {static} +NotFound: Error
    {static} +AddRecipeFail: Error
    {static} +UpdateRecipeFail: Error
    {static} +DeleteRecipeFail: Error
    {static} +AddStepFail: Error
    {static} +UpdateStepFail: Error
    {static} +DeleteStepFail: Error
    {static} +AddCommentFail: Error
    {static} +UpdateCommentFail: Error
    {static} +DeleteCommentFail: Error
    {static} +VoteRecipeFail: Error
    {static} +AlreadyInactive: Error
    {static} +AlreadyActive: Error
}

class TagError {
    {static} +NotFound: Error
    {static} +AddTagFail: Error
    {static} +UpdateTagFail: Error
    {static} +DeleteTagFail: Error
    {static} +AlreadyExist: Error
    {static} +NullParameters: Error
}

' =========== Library class ===========
interface "IRequest<TResponse>" #black;line:white;text:white
interface "IRequestHandler<TRequest, TResponse>" #black;line:white;text:white
' =========== Library class ===========

GetAllTagsQuery --|> "IRequest<TResponse>"
GetRecipeDetailForServerQuery --|> "IRequest<TResponse>"
GetSimpleRecipesQuery --|> "IRequest<TResponse>"
SearchSimpleRecipesQuery --|> "IRequest<TResponse>"

GetAllTagsQueryHandler --|> "IRequestHandler<TRequest, TResponse>"
GetRecipeDetailForServerQueryHandler --|> "IRequestHandler<TRequest, TResponse>"
GetSimpleRecipesQueryHandler --|> "IRequestHandler<TRequest, TResponse>"
SearchSimpleRecipesQueryHandler --|> "IRequestHandler<TRequest, TResponse>"

' Commands and queries

GrpcRecipeService "1"--"1" GrpcEmpty
GrpcRecipeService "1"--"1..*" GrpcTagDTO
GrpcRecipeService "1"--"1..*" GrpcListTagDTO
GrpcRecipeService "1"--"1..*" Tag
GrpcRecipeService "1"--"1" GetAllTagsQuery

GrpcRecipeService "1"--"1" GrpcRecipeIdRequest
GrpcRecipeService "1"--"1..*" GrpcRecipeDetailsDTO
GrpcRecipeService "1"--"1..*" GrpcStepDTO
GrpcRecipeService "1"--"1..*" GrpcCommentDTO
GrpcRecipeService "1"--"1" RecipeDetailsResponse
GrpcRecipeService "1"--"1" GetRecipeDetailForServerQuery

GrpcRecipeService "1"--"1" GrpcGetSimpleRecipeRequest
GrpcRecipeService "1"--"1" GrpcMapSimpleRecipes
GrpcRecipeService "1"--"1..*" GrpcSimpleRecipe
GrpcRecipeService "1"--"1" SimpleRecipeResponse
GrpcRecipeService "1"--"1" GetSimpleRecipesQuery

GrpcRecipeService "1"--"1" GrpcSearchSimpleRecipeRequest
GrpcRecipeService "1"--"1" GrpcMapSimpleRecipes
GrpcRecipeService "1"--"1..*" GrpcSimpleRecipe
GrpcRecipeService "1"--"1" SimpleRecipeResponse
GrpcRecipeService "1"--"1" SearchSimpleRecipesQuery

' Handlers

GetAllTagsQueryHandler "1"--"1" GetAllTagsQuery
GetAllTagsQueryHandler "1"--"1..*" Tag
GetAllTagsQueryHandler "1"---"1" Result
GetAllTagsQueryHandler "1" o-- "1" IApplicationDbContext
GetAllTagsQueryHandler "1"--"1..*" TagError

GetRecipeDetailForServerQueryHandler "1"--"1" GetRecipeDetailForServerQuery
GetRecipeDetailForServerQueryHandler "1"--"1" RecipeDetailsResponse
GetRecipeDetailForServerQueryHandler "1"---"1" Result
GetRecipeDetailForServerQueryHandler "1"---"1" GrpcAccountIdRequest
GetRecipeDetailForServerQueryHandler "1" o-- "1" IApplicationDbContext
GetRecipeDetailForServerQueryHandler "1" o-- "1" IServiceBus
GetRecipeDetailForServerQueryHandler "1" o-- "1" GrpcUserClient
GetRecipeDetailForServerQueryHandler "1"----"1..*" RecipeError

GetSimpleRecipesQueryHandler "1"--"1" GetSimpleRecipesQuery
GetSimpleRecipesQueryHandler "1"--"1" SimpleRecipeResponse
GetSimpleRecipesQueryHandler "1"---"1" Result
GetSimpleRecipesQueryHandler "1"---"1" GrpcGetSimpleUsersRequest
GetSimpleRecipesQueryHandler "1" o-- "1" IApplicationDbContext
GetSimpleRecipesQueryHandler "1" o-- "1" GrpcUserClient
GetSimpleRecipesQueryHandler "1"----"1..*" RecipeError

SearchSimpleRecipesQueryHandler "1"--"1" SearchSimpleRecipesQuery
SearchSimpleRecipesQueryHandler "1"--"1" SimpleRecipeResponse
SearchSimpleRecipesQueryHandler "1"---"1" Result
SearchSimpleRecipesQueryHandler "1"---"1" GrpcGetSimpleUsersRequest
SearchSimpleRecipesQueryHandler "1" o-- "1" IApplicationDbContext
SearchSimpleRecipesQueryHandler "1" o-- "1" GrpcUserClient
SearchSimpleRecipesQueryHandler "1"----"1..*" RecipeError
' =================STYLE=================

together {
    class GrpcAccountIdRequest #DarkBlue;line:white;text:white
    class GrpcGetSimpleUsersRequest #DarkBlue;line:white;text:white
    class GrpcUserClient #DarkBlue;line:white;text:white
}

GrpcRecipeService -[hidden]down-|> GetAllTagsQuery
GrpcRecipeService -[hidden]down-|> GetRecipeDetailForServerQuery
GrpcRecipeService -[hidden]down-|> GetSimpleRecipesQuery
GrpcRecipeService -[hidden]down-|> SearchSimpleRecipesQuery

GetAllTagsQuery -[hidden]down-|> GetAllTagsQueryHandler
GetRecipeDetailForServerQuery -[hidden]down-|> GetRecipeDetailForServerQueryHandler
GetSimpleRecipesQuery -[hidden]down-|> GetSimpleRecipesQueryHandler
SearchSimpleRecipesQuery -[hidden]down-|> SearchSimpleRecipesQueryHandler

Error "1" --"1..*" RecipeError
Error "1" --"1..*" TagError

@enduml