
@startuml ClassDiagram
!include doc/SDS/CommonClassDiagram/ResultAndError.plantuml
skinparam classAttributeIconSize 0
skinparam linetype polyline
skinparam nodesep 20
skinparam ranksep 20
hide circle

class BaseApiController {
    #_sender: ISender
    #_httpContextAccessor: HttpContextAccessor
}

class AccountController {
    +VerifyAccount(method: string, dto: VerifyAccountDTO): async Task<IActionResult>
}

class VerifyAccountCommand {
    +Guid AccountId
    +String OTP
    +AccountMethod Method
}

class VerifyAccountCommandHandler {
    - _userManager : UserManager<ApplicationAccount>
    + VerifyAccountCommandHandler(userManager: UserManager<ApplicationAccount>)
    + Handle(request: VerifyAccountCommand, cancellationToken: CancellationToken) : Task<Result>
    - VerifyEmail(request: VerifyAccountCommand, cancellationToken: CancellationToken) : Task<Result>
    - VerifyPhone(request: VerifyAccountCommand, cancellationToken: CancellationToken) : Task<Result>
}

class AccountError {
    {static} +NotFound: Error
    {static} +InvalidAccountMethod: Error
    {static} +EmailAlreadyConfirmed: Error
    {static} +InvalidOTP: Error
    {static} +OTPExpired: Error
    {static} +PhoneAlreadyConfirmed: Error
    {static} +VerifyFailed: Error
}

enum AccountMethod {
    Phone
    Email
    Username
    Google
}

!include doc/SDS/CommonClassDiagram/Account/AccountDbContext.plantuml 
remove IDisposable
remove DbSet<T>
remove IdentityUserLogin<T>
remove DbContext
remove IDbContext
remove IApplicationDbContext
remove ApplicationDbContext
remove IdentityDbContext<ApplicationAccount>

' =========== DTO class ===========
class VerifyAccountDTO {
    +OTP: string
}

' =========== Library class ===========
interface "IRequest<TResponse>" #black;line:white;text:white
interface "IRequestHandler<TRequest, TResponse>" #black;line:white;text:white
class "UserManager<TUser>" #black;line:white;text:white
' =========== Library class ===========

AccountController --|> BaseApiController
AccountController "1"--"1" VerifyAccountDTO
AccountController "1"--"1" VerifyAccountCommand
VerifyAccountCommand "1"--"1" AccountMethod
VerifyAccountCommand ..|> "IRequest<TResponse>"

VerifyAccountCommandHandler ..|> "IRequestHandler<TRequest, TResponse>"
VerifyAccountCommandHandler "1" o--"1" VerifyAccountCommand
VerifyAccountCommandHandler "1" o---"1" ApplicationAccount
VerifyAccountCommandHandler "1" o--"1" AccountError
VerifyAccountCommandHandler "1" o--"1" Result
VerifyAccountCommandHandler "1" o--"1" "UserManager<TUser>"

Error "1" --"1..*" AccountError

@enduml