@startuml Sequence
title "Verify account sequence diagram"

<style>
  sequenceDiagram {
    reference {
      BackGroundColor white
    }
}
</style>

actor User
boundary MobileUI
participant "<<coordinator>>\nApiGateWay" as ApiGateway
participant "<<service>>\nIdentityService" as IdentityService
database Postgresql

User -> MobileUI ++: 1. After user click the verify\n account button
MobileUI -> ApiGateway ++: 2. Request verify account

activate IdentityService
ref over ApiGateway, IdentityService: 3. Verify Access Token
ApiGateway -[hidden]-> IdentityService
deactivate IdentityService

ApiGateway -> IdentityService ++: 4. Forward request
IdentityService -> Postgresql ++: 5. Get account data
IdentityService <-- Postgresql --: 6. Return response

alt if user's OTP is invalid
    ApiGateway <-- IdentityService: 7A.1. Return invalid otp error
    MobileUI <-- ApiGateway: 7A.2. Forward response
    User <-- MobileUI: 7A.3. Display error alert
else
    IdentityService -> Postgresql ++: 8. Update account status
    IdentityService <-- Postgresql --: 9. Return response
    ApiGateway <-- IdentityService --: 10. Return success status code
    MobileUI <-- ApiGateway --: 11. Forward response
    User <-- MobileUI --: 12. Display alert\n verify account successfully
end

@enduml
