@startuml UserDbContext

interface IDbContext extends IDisposable {
    +Instance : DbContext
}
' ========= Entity class =========
class BaseEntity {
    +Id : Guid
}

class BaseAuditableEntity extends BaseEntity {
    +DateTime CreatedAt
    +DateTime UpdatedAt
}

class User {
    + AccountId : Guid
    + DisplayName : string
    + AvatarUrl : string
    + BackgroundUrl : string
    + Dob : DateTime
    + Gender : string
    + Bio : string
    + Address : string
    + TotalFollwer : int
    + TotalFollowing : int
    + TotalRecipe : int
    + IsAccountActive : bool
    + AccountUsername : string
    + IsAdmin : bool
}

class Setting extends BaseEntity {
    + Code: string
    + Description: string
    + DataType: SettingDataType
    + DefaultValue: string
}

enum SettingDataType
{
    String,
    Integer,
    Boolean,
    DateTime
}

class UserFollow {
    + FollowerId : Guid
    + FollowingId : Guid
    + Follower : User
    + Following : User
}

class UserReport {
    + AccountId : Guid
    + ReportedId : Guid
    + Reason : string
    + Status : string
    + User : User
    + Reported : User
}

class UserSetting {
    + AccountId : Guid
    + SettingId : Guid
    + SettingValue : string
    + User : User
    + Setting : Setting
}

interface IApplicationDbContext extends IDbContext {
    + Users : DbSet<User>
    + UserReports : DbSet<UserReport>
    + UserFollows : DbSet<UserFollow>
    + Settings : DbSet<Setting>
    + UserSettings : DbSet<UserSetting>
}

class ApplicationDbContext extends DbContext implements IApplicationDbContext {
    + Users : DbSet<User>
    + UserReports : DbSet<UserReport>
    + UserFollows : DbSet<UserFollow>
    + Settings : DbSet<Setting>
    + UserSettings : DbSet<UserSetting>
    + Instance : DbContext
    + ApplicationDbContext()
    + ApplicationDbContext(options : DbContextOptions<ApplicationDbContext>)
    + OnConfiguring(optionsBuilder : DbContextOptionsBuilder) : void
    + OnModelCreating(modelBuilder : ModelBuilder) : void
}

' ========= Library class =========
interface IDisposable #black;line:white;text:white
class "DbSet<T>" #black;line:white;text:white
class DbContext #black;line:white;text:white

IDbContext o-- DbContext

ApplicationDbContext o-- "DbSet<T>"
ApplicationDbContext "1" o-- "1" Setting
ApplicationDbContext "1" o-- "1" User
ApplicationDbContext "1" o-- "1" UserFollow
ApplicationDbContext "1" o-- "1" UserReport
ApplicationDbContext "1" o-- "1" UserSetting

Setting "1" *-- "1" SettingDataType 
Setting "1" *-- "1" UserSetting
User "1" *-- "1" UserSetting
User "1" *-- "1" UserFollow
User "1" *-- "1..2" UserReport
' =========== Style ==============

ApplicationDbContext o-[hidden]down- "DbSet<T>"

@enduml