FROM mcr.microsoft.com/dotnet/aspnet:8.0-alpine AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:8.0-alpine AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src

COPY ["./app/server/Contract/Contract/Published", "Contract/"]
COPY ["./app/server/NotificationService/src/NotificationService.API/NotificationService.API.csproj", "NotificationService.API/"]
COPY ["./app/server/NotificationService/src/NotificationService.Application/NotificationService.Application.csproj", "NotificationService.Application/"]
COPY ["./app/server/NotificationService/src/NotificationService.Infrastructure/NotificationService.Infrastructure.csproj", "NotificationService.Infrastructure/"]
COPY ["./app/server/NotificationService/src/NotificationService.Domain/NotificationService.Domain.csproj", "NotificationService.Domain/"]

# Building the services
WORKDIR "/src/NotificationService.API"
RUN --mount=type=cache,target=/root/.cache/.nuget \ 
    dotnet restore --verbosity normal
COPY ["./app/server/NotificationService/src","/src"]
RUN --mount=type=cache,target=/root/.cache/.nuget \ 
    dotnet build "./NotificationService.API.csproj" -c $BUILD_CONFIGURATION -o /app/build

FROM build AS publish
# Have to add work dir, because dotnet publish will scan entire fs, make the docker hang with NAT network
WORKDIR "/src/NotificationService.API"
ARG BUILD_CONFIGURATION=Release
RUN --mount=type=cache,target=/root/.cache/.nuget \ 
    dotnet publish "./NotificationService.API.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
COPY seeds seeds

RUN chown -R app:app /app
USER app
ENTRYPOINT ["dotnet", "NotificationService.API.dll"]