@startuml Sequence
title "Remove expo push token"

' Style section
<style>
  sequenceDiagram {
    reference {
      BackGroundColor white
    }
}
</style>

actor User
boundary MobileUI
participant "<<coordinator>>\nApiGateway" as ApiGateway
participant "<<service>>\n IdentityService" as IdentityService
participant "<<service>>\n NotificationService" as NotificationService
database MongoDB

User -> MobileUI ++: 1. User logout
MobileUI -> ApiGateway ++: 2. Request remove expo \n push notification token

activate IdentityService
ref over ApiGateway, IdentityService: 3. Get access token
ApiGateway -[hidden]-> IdentityService
deactivate IdentityService

ApiGateway -> NotificationService ++: 4. Forward request

NotificationService -> MongoDB++: 5. Query data
NotificationService <-- MongoDB--: 6. Return response

alt expoPushToken not found
  ApiGateway <-- NotificationService: 10. Return ExpoPushTokenNotFound error
  MobileUI <-- ApiGateway: 11. Forward response
  User <-- MobileUI: 12. Display error message
else
  NotificationService -> MongoDB++: 8. Delete existing push notification token
  NotificationService <-- MongoDB--: 9. Return response
  ApiGateway <-- NotificationService--: 10. Return success
  MobileUI <-- ApiGateway--: 11. Forward response
  User <-- MobileUI--: 12. Display notification list
end

@enduml