FROM node:25-alpine AS base

FROM base AS deps
ARG BASE_WEBSITE_PATH=app/client/website
WORKDIR /app

RUN --mount=source=$BASE_WEBSITE_PATH/package.json,target=package.json \
  --mount=source=$BASE_WEBSITE_PATH/package-lock.json,target=package-lock.json \
  npm ci

FROM deps AS builder
ARG BASE_WEBSITE_PATH=app/client/website
ARG BUILD_ENV
WORKDIR /app
ENV NEXT_TELEMETRY_DISABLED=1

COPY $BASE_WEBSITE_PATH .

RUN if [ "$BUILD_ENV" = "dev" ]; then mv .env.pub .env.production; \
  elif [ "$BUILD_ENV" = "staging" ]; then mv .env.staging.pub .env.production; \
  else mv .env.production.pub .env.production; \
  fi;

RUN if [ -f package-lock.json ]; then npm run build; else exit 1; fi;

FROM base AS runner
WORKDIR /app
ENV NODE_ENV=production
# Disable telemetry during runtime.
ENV NEXT_TELEMETRY_DISABLED=1

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

# Automatically leverage output traces to reduce image size
# https://nextjs.org/docs/advanced-features/output-file-tracing
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs

EXPOSE 3000

ENV PORT=3000

# server.js is created by next build from the standalone output
# https://nextjs.org/docs/pages/api-reference/config/next-config-js/output
ENV HOSTNAME="0.0.0.0"
CMD ["node", "server.js"]
