@startuml GetRecipeCommentClassDiagram
!include doc/SDS/CommonClassDiagram/PaginateData.plantuml
!include doc/SDS/CommonClassDiagram/ResultAndError.plantuml
!include doc/SDS/CommonClassDiagram/Recipe/RecipeDbContext.plantuml
skinparam classAttributeIconSize 0
skinparam linetype polyline
skinparam nodesep 50
skinparam ranksep 50
hide circle

class BaseApiController {
    #_sender: ISender
    #_httpContextAccessor: HttpContextAccessor
}

class RecipeController {
    +GetRecipeComments(getRecipeCommentsDTO : GetRecipeCommentsDTO): async Task<IActionResult>
}

class GetRecipeCommentsQuery {
    +RecipeId: Guid
    +Skip: int
}

class GetRecipeCommentsQueryHandler {
    -_context: IApplicationDbContext
    -_mapper: IMapper
    -_grpcUserClient: GrpcUserClient
    -_paginateDataUtility: IPaginateDataUtility
    +GetRecipeCommentsQueryHandler(context : IApplicationDbContext, mapper : IMapper, grpcUserClient : GrpcUserClient, paginateDataUtility : IPaginateDataUtility)
    +Handle(request : GetRecipeCommentsQuery, cancellationToken : CancellationToken): async Task<Result<PaginatedRecipeCommentListResponse?>> 
}


interface IMapper{
    #Map<TDestination>(object source): TDestination
}

class PaginatedRecipeCommentListResponse{
}
class BasePaginatedResponse{
    +PaginatedData : IEnumerable<Type>
    +Metadata: MetadataType?
}
PaginatedRecipeCommentListResponse --|> BasePaginatedResponse

class GetRecipeCommentsDTO{
    +RecipeId: Guid
    +Skip: int
}

class RecipeError {
    {static} +NotFound: Error
    {static} +AddRecipeFail: Error
    {static} +DeleteRecipeFail: Error
    {static} +UpdateRecipeFail: Error
}
together {
    class GrpcGetSimpleUsersRequest #DarkBlue;line:white;text:white
    class GrpcUserClient #DarkBlue;line:white;text:white
}

' =========== Library class ===========
interface "IRequest<TResponse>" #black;line:white;text:white
interface "IRequestHandler<TRequest, TResponse>" #black;line:white;text:white
' =========== Library class ===========

RecipeController --|> BaseApiController
RecipeController "1"--"1" GetRecipeCommentsDTO
RecipeController "1"--"1" GetRecipeCommentsQuery

GetRecipeCommentsQuery ..|> "IRequest<TResponse>"

GetRecipeCommentsQueryHandler ..|> "IRequestHandler<TRequest, TResponse>"
GetRecipeCommentsQueryHandler "1"--"1" GetRecipeCommentsQuery
GetRecipeCommentsQueryHandler "1"--"1" Result
GetRecipeCommentsQueryHandler "1"--"1" PaginatedRecipeCommentListResponse
GetRecipeCommentsQueryHandler "1"--"1" GrpcGetSimpleUsersRequest
GetRecipeCommentsQueryHandler "1" o-- "1" IApplicationDbContext
GetRecipeCommentsQueryHandler "1" o-- "1" IMapper
GetRecipeCommentsQueryHandler "1" o-- "1" IPaginateDataUtility
GetRecipeCommentsQueryHandler "1" o-- "1" GrpcUserClient
GetRecipeCommentsQueryHandler "1"--"1..*" RecipeError

Error "1..*" --o "1" RecipeError
@enduml