@startuml Sequence
title "Get notifications diagram"

' Style section
<style>
  sequenceDiagram {
    reference {
      BackGroundColor white
    }
}
</style>

actor User
activate User
boundary MobileUI
participant "<<coordinator>>\nApiGateway" as ApiGateway
participant "<<service>>\n IdentityService" as IdentityService
participant "<<service>>\n NotificationService" as NotificationService
participant "<<service>>\n UserService" as UserService
participant "<<service>>\n RecipeService" as RecipeService
database MongoDB
database Postgresql

User -> MobileUI ++: 1. Navigate to notification screen
MobileUI -> ApiGateway ++: 2. Request get notification list

activate IdentityService
ref over ApiGateway, IdentityService: 3. Get access token
ApiGateway -[hidden]-> IdentityService
deactivate IdentityService

ApiGateway -> NotificationService ++: 4. Forward request

NotificationService -> MongoDB++: 5. Query notification list data
NotificationService <-- MongoDB--: 6. Return response

NotificationService -> UserService++ : 7. Call GetSimpleUserAsync <<gRPC>> 
UserService -> Postgresql++ : 8. Query data 
UserService <-- Postgresql-- : 9. Return response
NotificationService <-- UserService-- : 10. Return response <<gRPC>> 

NotificationService -> RecipeService++ : 11. Call GetSimpleRecipesAsync <<gRPC>> 
RecipeService -> MongoDB++ : 12. Query data 
RecipeService <-- MongoDB-- : 13. Return response
NotificationService <-- RecipeService-- : 14. Return response <<gRPC>> 

NotificationService -> RecipeService++ : 15. Call GetSimpleCommentsAsync <<gRPC>> 
RecipeService -> MongoDB++ : 16. Query data 
RecipeService <-- MongoDB-- : 17. Return response
NotificationService <-- RecipeService-- : 18. Return response <<gRPC>> 

ApiGateway <-- NotificationService--: 19. Return notification list
MobileUI <-- ApiGateway--: 20. Forward response
User <-- MobileUI--: 21. Display notification list
deactivate User

@enduml