@startuml Sequence
title "Check forgot password's OTP diagram"

<style>
  sequenceDiagram {
    reference {
      BackGroundColor white
    }
}
</style>

actor User
boundary MobileUI
participant "<<coordinator>>\nApiGateWay" as ApiGateway
participant "<<service>>\nIdentityService" as IdentityService
database Postgresql

User -> MobileUI ++: 1. User click the verify button\n in forgot password screen
MobileUI -> ApiGateway ++: 2. Request check forgot password's OTP

ApiGateway -> IdentityService ++: 3. Forward request
IdentityService -> Postgresql ++: 4. Get account data
IdentityService <-- Postgresql --: 5. Return response

alt if account is null
  ApiGateway <-- IdentityService: 6A.1. Return not found error
  MobileUI <-- ApiGateway: 6A.2. Forward response
  User <-- MobileUI: 6A.3. Display error
else
  alt if the forgot password's OTP is invalid
    ApiGateway <-- IdentityService: 6B.1. Return OTP invalid error
    MobileUI <-- ApiGateway: 6B.2. Forward response
    User <-- MobileUI: 6B.3. Display error
  else
    alt if the forgot password's OTP is expired
      ApiGateway <-- IdentityService: 6C.1. Return OTP expired error
      MobileUI <-- ApiGateway: 6C.2. Forward response
      User <-- MobileUI: 6C.3. Display error
    else
      ApiGateway <-- IdentityService --: 7. Return success status code
      MobileUI <-- ApiGateway --: 8. Forward response
      User <-- MobileUI --: 9. Redirect user to change password screen
    end
  end
end

@enduml
