@startuml Sequence
title "Check forgot password's OTP diagram"

<style>
  sequenceDiagram {
    reference {
      BackGroundColor white
    }
}
</style>

actor User

activate User

boundary MobileUI
participant "<<coordinator>>\nApiGateWay" as ApiGateway
participant "<<service>>\nIdentityService" as IdentityService
database Postgresql

User -> MobileUI ++: 1. User click the verify button\n in forgot password screen
MobileUI -> ApiGateway ++: 2. Request check forgot password's OTP

ApiGateway -> IdentityService ++: 3. Forward request
IdentityService -> Postgresql ++: 4. Get account data
IdentityService <-- Postgresql --: 5. Return response

alt if account is null
  ApiGateway <-- IdentityService: 6A. Return not found error
  MobileUI <-- ApiGateway: 6A.1. Forward response
  User <-- MobileUI: 6A.2. Display error
else
  alt if the forgot password's OTP is invalid
    ApiGateway <-- IdentityService: 7A. Return OTP invalid error
    MobileUI <-- ApiGateway: 7A.1. Forward response
    User <-- MobileUI: 7A.2. Display error
  else
    alt if the forgot password's OTP is expired
      ApiGateway <-- IdentityService: 8A. Return OTP expired error
      MobileUI <-- ApiGateway: 8A.1. Forward response
      User <-- MobileUI: 8A.2. Display error
    else
      ApiGateway <-- IdentityService --: 9. Return success status code
      MobileUI <-- ApiGateway --: 10. Forward response
      User <-- MobileUI --: 11. Redirect user to change password screen
      deactivate User
    end
  end
end

@enduml
