---
helm:
  public_key:
    link: 'https://packages.buildkite.com/helm-linux/helm-debian/gpgkey'
    path: '/tmp/helm-key'
  keyring:
    dir: '/usr/share/keyrings'
    file_path: '{{ helm.keyring.dir }}/helm.gpg'
  source:
    repo: 'deb [signed-by={{ helm.keyring.file_path }}] https://packages.buildkite.com/helm-linux/helm-debian/any/ any main'
    name: 'helm-stable-debian'
