#See https://aka.ms/customizecontainer to learn how to customize your debug container and how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
USER app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
# Copy pre-build lib
COPY ["./data/nuget", "./nuget"]

COPY ["./app/server/IdentityService/src/DuendeIdentityServer/DuendeIdentityServer.csproj", "DuendeIdentityServer/"]
COPY ["./app/server/IdentityService/src/IdentityService.Application/IdentityService.Application.csproj", "IdentityService.Application/"]
COPY ["./app/server/IdentityService/src/IdentityService.Domain/IdentityService.Domain.csproj", "IdentityService.Domain/"]
COPY ["./app/server/IdentityService/src/IdentityService.Infrastructure/IdentityService.Infrastructure.csproj", "IdentityService.Infrastructure/"]
COPY ["./app/server/Contract/Contract/Published", "Contract/"]

# Building the services
WORKDIR "/src/DuendeIdentityServer"
RUN dotnet restore --packages "../nuget" --verbosity normal
COPY ["./app/server/IdentityService/src","/src"]
COPY seeds seeds

ENTRYPOINT ["dotnet","watch","run", "--no-restore", "--packages", "./nuget"]