ARG CONTRACT_IMAGE
FROM ${CONTRACT_IMAGE} AS contract

FROM mcr.microsoft.com/dotnet/aspnet:8.0-alpine AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:8.0-alpine AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src

COPY --from=contract /publish ./Contract
COPY ["./app/server/IdentityService/src/DuendeIdentityServer/DuendeIdentityServer.csproj", "DuendeIdentityServer/"]
COPY ["./app/server/IdentityService/src/IdentityService.Application/IdentityService.Application.csproj", "IdentityService.Application/"]
COPY ["./app/server/IdentityService/src/IdentityService.Domain/IdentityService.Domain.csproj", "IdentityService.Domain/"]
COPY ["./app/server/IdentityService/src/IdentityService.Infrastructure/IdentityService.Infrastructure.csproj", "IdentityService.Infrastructure/"]

# Building the services
WORKDIR "/src/DuendeIdentityServer"
RUN dotnet restore --verbosity normal
COPY ["./app/server/IdentityService/src","/src"]
RUN dotnet build "./DuendeIdentityServer.csproj" -c $BUILD_CONFIGURATION -o /app/build 

FROM build AS publish
# Have to add work dir, because dotnet publish will scan entire fs, make the docker hang with NAT network
WORKDIR "/src/DuendeIdentityServer"
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "./DuendeIdentityServer.csproj"  -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
COPY seeds seeds

RUN chown -R app:app /app
USER app

ENTRYPOINT ["dotnet", "DuendeIdentityServer.dll"]
