---
- name: Check maestro runner
  ansible.builtin.command: which maestro
  register: maestro_runner_check
  changed_when: false
  failed_when: false

- name: Load OS-specific tasks
  ansible.builtin.include_tasks: "{{ ansible_os_family | lower }}.yml"
  when: maestro_runner_check.rc != 0
