@startuml UserUsecase
skinparam style strictuml
skinparam monochrome true
skinparam linetype polyline
skinparam defaultFontSize 12
left to right direction
actor "User" as user
actor "Gmail" as gmail
actor "Cloudinary" as cl
actor "SpeedSMS         " as sms
actor "Gemma" as gemma
actor "Expo Speech Recognition" as speech

rectangle Ingredient-based<U+0020>food<U+0020>recommendation<U+0020>application {
    usecase "UC-2: Login (Mobile)" as ucLogin
    usecase "UC-5: Forgot password (Mobile)" as ucForgotPassword
    usecase "UC-11 Report users" as ucReportUser
    usecase "UC-12 Logout" as ucLogout
    usecase "UC-13: Manage settings (Mobile)" as ucManageSetting
    usecase "UC-15: Manage profile (Mobile)" as ucManageProfile

    usecase "UC-7: Search" as ucSearch
    usecase "UC-8: Browse recipes" as ucBrowseRecipes
    usecase "UC-17: Vote recipes" as ucVoteRecipe
    usecase "UC-18: Comment recipes" as ucCmtRecipe
    usecase "UC-19: Report comments" as ucReportComment
    usecase "UC-20: Report recipes" as ucReportRecipe
    usecase "UC-21: Bookmark recipes" as ucBookmarkRecipe
    usecase "UC-22: View recipe detail" as ucViewRecipeDetail
    usecase "UC-23: Use guided cooking mode" as ucGuidedCCM
    usecase "UC-10: View other users' profiles (User)" as ucViewUSProfile

    usecase "UC-24: View menu" as ucViewMenu
    usecase "UC-25: Manage own recipes" as ucManageRecipe
    usecase "UC-26: View recent recipes" as ucViewRecentRecipes

    usecase "UC-27: View notifications" as ucViewNotif
    usecase "UC-28: View followers and followings" as ucViewFollow

    note "Create/Read/\nUpdate/Delete" as noteManageRecipe
    note "Read/Update" as noteManageProfile
    note "Create/Read/\nUpdate/Delete" as noteVoteRecipe
    note "Create/Read/\nUpdate/Delete" as noteCmtRecipe
    note "Create/Read/\nUpdate/Delete" as noteBookmarkRecipe
    note "{Follow/Unfollow}" as noteViewUSProfile

    user --> ucSearch

    user --> ucBrowseRecipes
        ucBrowseRecipes <.. ucVoteRecipe : <<extend>>
            ucVoteRecipe . noteVoteRecipe
        ucBrowseRecipes <.. ucReportRecipe : <<extend>>
        ucBrowseRecipes <.. ucViewRecipeDetail : <<extend>>
            ucViewRecipeDetail <... ucCmtRecipe : <<extend>>
                ucCmtRecipe . noteCmtRecipe
            ucViewRecipeDetail <... ucReportComment : <<extend>>
            ucViewRecipeDetail <.. ucGuidedCCM : <<extend>>
        ucBrowseRecipes <.. ucBookmarkRecipe : <<extend>>
            ucBookmarkRecipe . noteBookmarkRecipe
        ucBrowseRecipes <.. ucViewUSProfile : <<extend>>
            ucViewUSProfile . noteViewUSProfile
            ucViewUSProfile <.. ucReportUser : <<extend>>

    user --> ucViewMenu
        ucViewMenu <.. ucManageProfile : <<extend>>
            ucManageProfile . noteManageProfile
            ucManageProfile <.. ucManageRecipe : <<extend>>
            ucManageProfile <.. ucViewFollow : <<extend>>
                ucManageRecipe . noteManageRecipe
        ucViewMenu <.. ucManageSetting : <<extend>>
        ucViewMenu <.. ucViewRecentRecipes : <<extend>>
        ucViewMenu <.. ucLogout : <<extend>>

    user --> ucViewNotif
    
    gmail -up-> ucLogin
    cl --up-> ucManageProfile
    cl --up-> ucManageRecipe
    gemma -up-> ucManageRecipe
    sms --up-> ucForgotPassword

    ucSearch .....> ucLogin : <<include>>
    ucBrowseRecipes .....> ucLogin : <<include>>
    ucViewMenu .....> ucLogin : <<include>>
    ucViewNotif .....>ucLogin : <<include>>
    ucLogin <.. ucForgotPassword : <<extend>>

    usecase "UC-29: Command by voice \n in cooking mode" as ucCommandVoiceCCM
    usecase "UC-30: Recognize ingredients \n by capturing image" as ucRecognizeIngre

    speech --up-> ucCommandVoiceCCM

    user --> ucRecognizeIngre
    ucGuidedCCM <.. ucCommandVoiceCCM : <<extend>>

    ucRecognizeIngre .....> ucLogin : <<include>>

}

@enduml
