@startuml GrpcRecipeSerciveClassDiagram
!include doc/SDS/CommonClassDiagram/ResultAndError.plantuml
skinparam classAttributeIconSize 0
skinparam linetype polyline
skinparam nodesep 50
skinparam ranksep 50
skinparam classAttributeIconSize 0

hide circle

class GrpcUploadFileService {
    #_sender: ISender
    #_logger: ILogger
    #_fileUtility: IFileUtility
    +UpdateMultipleImage(GrpcUpdateMultipleImageRequest request, ServerCallContext context): async Task<GrpcListFileDTO>
    +UploadMultipleImage(GrpcUploadMultipleImageRequest request, ServerCallContext context): async Task<GrpcListFileDTO>
}


class Cloudinary #Black;line:white;text:white{
}

class ImageUploadParams #Black;line:white;text:white{
}

class ImageUploadResult #Black;line:white;text:white {
}

class DeletionParams #Black;line:white;text:white{
}

interface IFileUtility {
    #GetFileType(string fileName): enum
    #GetPublicIdByUrl(string url): string?
    #ConvertGrpcFileStreamToIFormFileAsync(List<GrpcFileStreamDTO> streams): Task<List<IFormFile>>
    #ConvertFileStreamDTOToIFormFileAsync(List<FileStreamDTO> streams): Task<List<IFormFile>>
}

class FileUtility Implements IFileUtility {
    +GetFileType(string fileName): enum
    +GetPublicIdByUrl(string url): string?
    +ConvertGrpcFileStreamToIFormFileAsync(List<GrpcFileStreamDTO> streams): Task<List<IFormFile>>
    +ConvertFileStreamDTOToIFormFileAsync(List<FileStreamDTO> streams): Task<List<IFormFile>>
}

class UpdateMultipleImageFileCommand {
    +DeleteUrls: List<string>?
    +FormFiles: List<IFormFile>?
}

class UpdateMultipleImageFileCommandHandler{
    -_fileUtility: IFileUtility
    -_cloudinary: Cloudinary
    +Handle(UpdateMultipleImageFileCommand request, CancellationToken cancellationToken): async Task<Result<List<FileResponse>?>>
    -UploadMultipleImage(List<IFormFile> formFiles, CancellationToken cancellationToken): async Task<Result<List<FileResponse>?>>
    -DeleteMultipleImage(List<string> urls): async Task
}

class CreateMultipleImageFileCommand {
    +FormFiles: List<IFormFile>?
}

class CreateMultipleImageFileCommandHandler{
    -_fileUtility: IFileUtility
    -_cloudinary: Cloudinary
    +Handle(CreateMultipleImageFileCommand request, CancellationToken cancellationToken): async Task<Result<List<FileResponse>?>>
}
' Grpc DTO
class GrpcUpdateMultipleImageRequest{
    +Files: List<GrpcFileStreamDTO>
    +DeleteUrls: List<string>
}

class GrpcUploadMultipleImageRequest{
    +Files: List<GrpcFileStreamDTO>
}

class GrpcListFileDTO{
    +Files: List<GrpcFileDTO>
}

class GrpcFileDTO{
    +Name: string
    +PublicId: string
    +Size: long
    +Url: string
}

class GrpcFileStreamDTO{
    +FileName: string
    +ContentType: string
    +Stream: byte[]
}

GrpcUpdateMultipleImageRequest *--"1.." GrpcFileStreamDTO
GrpcUploadMultipleImageRequest *--"1.." GrpcFileStreamDTO
GrpcListFileDTO *--"1.." GrpcFileDTO

' DTO
class FileResponse{
    +PublicId: string
    +Name: string
    +Extension: string
    +Size: long
    +Url: string
}

class CloudinaryFileError {
    {static} +NotFound: Error
    {static} +UploadToCloudFail: Error
    {static} +DeleteToCloudFail: Error
    {static} +FileListContainNull: Error
    {static} +FileListTooLarge(long MaxSize, long FileSize): Error
    {static} +InvalidFile(string Type, string ChosenFileType): Error
}

GrpcUploadFileService "1"--"1" GrpcUpdateMultipleImageRequest
GrpcUploadFileService "1"--"1..*" GrpcListFileDTO
GrpcUploadFileService "1"--"1..*" GrpcFileDTO
GrpcUploadFileService "1"--"1..*" FileResponse
GrpcUploadFileService "1"--"1" UpdateMultipleImageFileCommand

GrpcUploadFileService "1"--"1" GrpcUploadMultipleImageRequest
GrpcUploadFileService "1"--"1..*" GrpcListFileDTO
GrpcUploadFileService "1"--"1..*" GrpcFileDTO
GrpcUploadFileService "1"--"1..*" FileResponse
GrpcUploadFileService "1"--"1" CreateMultipleImageFileCommand

UpdateMultipleImageFileCommandHandler "1"--"1" UpdateMultipleImageFileCommand
UpdateMultipleImageFileCommandHandler "1"--"1..*" FileResponse
UpdateMultipleImageFileCommandHandler "1"----"1..*" Result
UpdateMultipleImageFileCommandHandler "1" o---- "1" IFileUtility
UpdateMultipleImageFileCommandHandler "1" o-- "1" Cloudinary
UpdateMultipleImageFileCommandHandler "1"--"1..*" CloudinaryFileError
UpdateMultipleImageFileCommandHandler "1"--"1..*" ImageUploadResult
UpdateMultipleImageFileCommandHandler "1"--"1..*" ImageUploadParams
UpdateMultipleImageFileCommandHandler "1"--"1..*" DeletionParams

CreateMultipleImageFileCommandHandler "1"--"1" CreateMultipleImageFileCommand
CreateMultipleImageFileCommandHandler "1"--"1..*" FileResponse
CreateMultipleImageFileCommandHandler "1"----"1..*" Result
CreateMultipleImageFileCommandHandler "1" o---- "1" IFileUtility
CreateMultipleImageFileCommandHandler "1" o-- "1" Cloudinary
CreateMultipleImageFileCommandHandler "1"--"1..*" CloudinaryFileError
CreateMultipleImageFileCommandHandler "1"--"1..*" ImageUploadResult
CreateMultipleImageFileCommandHandler "1"--"1..*" ImageUploadParams


' =================STYLE=================
GrpcUploadFileService -[hidden]down-|> UpdateMultipleImageFileCommand
GrpcUploadFileService -[hidden]down-|> CreateMultipleImageFileCommand

UpdateMultipleImageFileCommand -[hidden]down-|> UpdateMultipleImageFileCommandHandler
CreateMultipleImageFileCommand -[hidden]down-|> CreateMultipleImageFileCommandHandler

Error "1" --"1..*" CloudinaryFileError
@enduml