@startuml GrpcRecipeSerciveClassDiagram
!include doc/SDS/CommonClassDiagram/ResultAndError.plantuml
skinparam classAttributeIconSize 0
skinparam linetype polyline
skinparam nodesep 50
skinparam ranksep 50
skinparam classAttributeIconSize 0

hide circle
class GrpcUploadFileBase #Black;line:white;text:white


class GrpcUploadFileService #LightSalmon;line:white;text:white extends GrpcUploadFileBase {
    #_sender: ISender
    #_fileUtility: IFileUtility
    +UpdateMultipleImage(request: GrpcUpdateMultipleImageRequest, context: ServerCallContext): async Task<GrpcListFileDTO>
    +UploadMultipleImage(request: GrpcUploadMultipleImageRequest, context: ServerCallContext): async Task<GrpcListFileDTO>
}


class Cloudinary #Black;line:white;text:white{
}

class ImageUploadParams #Black;line:white;text:white{
}

class ImageUploadResult #Black;line:white;text:white {
}

class DeletionParams #Black;line:white;text:white{
}

interface IFileUtility {
    #GetFileType(string fileName): enum
    #GetPublicIdByUrl(string url): string?
    #ConvertGrpcFileStreamToIFormFileAsync(List<GrpcFileStreamDTO> streams): Task<List<IFormFile>>
    #ConvertFileStreamDTOToIFormFileAsync(List<FileStreamDTO> streams): Task<List<IFormFile>>
}

class FileUtility Implements IFileUtility {
    +GetFileType(string fileName): enum
    +GetPublicIdByUrl(string url): string?
    +ConvertGrpcFileStreamToIFormFileAsync(List<GrpcFileStreamDTO> streams): Task<List<IFormFile>>
    +ConvertFileStreamDTOToIFormFileAsync(List<FileStreamDTO> streams): Task<List<IFormFile>>
}

class UpdateMultipleImageFileCommand {
    +DeleteUrls: List<string>?
    +FormFiles: List<IFormFile>?
}

class UpdateMultipleImageFileCommandHandler{
    -_fileUtility: IFileUtility
    -_cloudinary: Cloudinary
    +UpdateMultipleImageFileCommandHandler(fileUtility: IFileUtility, cloudinary: Cloudinary)
    +Handle(request: UpdateMultipleImageFileCommand, cancellationToken: CancellationToken): async Task<Result<List<FileResponse>?>>
    -UploadMultipleImage(formFiles: List<IFormFile>, cancellationToken: CancellationToken): async Task<Result<List<FileResponse>?>>
    -DeleteMultipleImage(urls: List<string>): async Task
}

class CreateMultipleImageFileCommand {
    +FormFiles: List<IFormFile>?
}

class CreateMultipleImageFileCommandHandler{
    -_fileUtility: IFileUtility
    -_cloudinary: Cloudinary
    +CreateMultipleImageFileCommandHandler(fileUtility: IFileUtility, cloudinary: Cloudinary)
    +Handle(request: CreateMultipleImageFileCommand, cancellationToken: CancellationToken): async Task<Result<List<FileResponse>?>>
}
' Grpc DTO
class GrpcUpdateMultipleImageRequest #LightSalmon;line:white;text:white{
}

class GrpcUploadMultipleImageRequest #LightSalmon;line:white;text:white{
}

class GrpcListFileDTO #LightSalmon;line:white;text:white{
}

class GrpcFileDTO #LightSalmon;line:white;text:white{
}


' DTO
class FileResponse{
    +PublicId: string
    +Name: string
    +Extension: string
    +Size: long
    +Url: string
}

class CloudinaryFileError {
    {static} +NotFound: Error
    {static} +UploadToCloudFail: Error
    {static} +DeleteToCloudFail: Error
    {static} +FileListContainNull: Error
    {static} +FileListTooLarge(long MaxSize, long FileSize): Error
    {static} +InvalidFile(string Type, string ChosenFileType): Error
}

' =========== Library class ===========
interface "IRequest<TResponse>" #black;line:white;text:white
interface "IRequestHandler<TRequest, TResponse>" #black;line:white;text:white
' =========== Library class ===========

UpdateMultipleImageFileCommand ..|> "IRequest<TResponse>"
CreateMultipleImageFileCommand ..|> "IRequest<TResponse>"

UpdateMultipleImageFileCommandHandler ..|> "IRequestHandler<TRequest, TResponse>"
CreateMultipleImageFileCommandHandler ..|> "IRequestHandler<TRequest, TResponse>"

GrpcUploadFileService "1"--"1" GrpcUpdateMultipleImageRequest
GrpcUploadFileService "1"--"1..*" GrpcListFileDTO
GrpcUploadFileService "1"--"1..*" GrpcFileDTO
GrpcUploadFileService "1"--"1..*" FileResponse
GrpcUploadFileService "1"--"1" UpdateMultipleImageFileCommand

GrpcUploadFileService "1"--"1" GrpcUploadMultipleImageRequest
GrpcUploadFileService "1"--"1" CreateMultipleImageFileCommand

UpdateMultipleImageFileCommandHandler "1"--"1" UpdateMultipleImageFileCommand
UpdateMultipleImageFileCommandHandler "1"--"1..*" FileResponse
UpdateMultipleImageFileCommandHandler "1"----"1..*" Result
UpdateMultipleImageFileCommandHandler "1" o---- "1" IFileUtility
UpdateMultipleImageFileCommandHandler "1" o-- "1" Cloudinary
UpdateMultipleImageFileCommandHandler "1"--"1..*" CloudinaryFileError
UpdateMultipleImageFileCommandHandler "1"--"1..*" ImageUploadResult
UpdateMultipleImageFileCommandHandler "1"--"1..*" ImageUploadParams
UpdateMultipleImageFileCommandHandler "1"--"1..*" DeletionParams

CreateMultipleImageFileCommandHandler "1"--"1" CreateMultipleImageFileCommand
CreateMultipleImageFileCommandHandler "1"--"1..*" FileResponse
CreateMultipleImageFileCommandHandler "1"----"1..*" Result
CreateMultipleImageFileCommandHandler "1" o---- "1" IFileUtility
CreateMultipleImageFileCommandHandler "1" o-- "1" Cloudinary
CreateMultipleImageFileCommandHandler "1"--"1..*" CloudinaryFileError
CreateMultipleImageFileCommandHandler "1"--"1..*" ImageUploadResult
CreateMultipleImageFileCommandHandler "1"--"1..*" ImageUploadParams


' =================STYLE=================
GrpcUploadFileService -[hidden]down-|> UpdateMultipleImageFileCommand
GrpcUploadFileService -[hidden]down-|> CreateMultipleImageFileCommand

UpdateMultipleImageFileCommand -[hidden]down-|> UpdateMultipleImageFileCommandHandler
CreateMultipleImageFileCommand -[hidden]down-|> CreateMultipleImageFileCommandHandler

Error "1..*" --o "1" CloudinaryFileError

@enduml