@startuml Sequence
title "Check update identifier's OTP diagram"

<style>
  sequenceDiagram {
    reference {
      BackGroundColor white
    }
}
</style>

actor User
boundary MobileUI
participant "<<coordinator>>\nApiGateWay" as ApiGateway
participant "<<service>>\nIdentityService" as IdentityService
database Postgresql

User -> MobileUI ++: 1. User click the verify button\n in update identifier screen
MobileUI -> ApiGateway ++: 2. Request check update identifier's OTP

activate IdentityService
ref over ApiGateway, IdentityService: 3. Verify Access Token
ApiGateway -[hidden]-> IdentityService
deactivate IdentityService

ApiGateway -> IdentityService ++: 4. Forward request
IdentityService -> Postgresql ++: 5. Get account data
IdentityService <-- Postgresql --: 6. Return response

alt if account is null
  ApiGateway <-- IdentityService: 7A.1. Return not found error
  MobileUI <-- ApiGateway: 7A.2. Forward response
  User <-- MobileUI: 7A.3. Display error alert
else
  alt if the update identifier's OTP is invalid
    ApiGateway <-- IdentityService: 7B.1. Return OTP invalid error
    MobileUI <-- ApiGateway: 7B.2. Forward response
    User <-- MobileUI: 7B.3. Display error alert
  else
    alt if the update identifier's OTP is expired
      ApiGateway <-- IdentityService: 7C.1. Return OTP expired error
      MobileUI <-- ApiGateway: 7C.2. Forward response
      User <-- MobileUI: 7C.3. Display error alert
    else
      ApiGateway <-- IdentityService --: 8. Return success status code
      MobileUI <-- ApiGateway --: 9. Forward response
      User <-- MobileUI --: 10. Display alert update identifier successfully
    end
  end
end

@enduml
