
@startuml ClassDiagram
!include doc/SDS/CommonClassDiagram/ResultAndError.plantuml
!include doc/SDS/CommonClassDiagram/UnitOfWork.plantuml
!include doc/SDS/CommonClassDiagram/FileUtility.plantuml
!include doc/SDS/CommonClassDiagram/User/UserDbContext.plantuml
skinparam classAttributeIconSize 0
skinparam linetype polyline
skinparam nodesep 100
skinparam ranksep 100
hide circle

remove UserSetting
remove Setting
remove SettingDataType
remove BaseEntity
remove BaseAuditableEntity
remove SettingDataType
remove UserReport
remove UserFollow

together {
    class BaseApiController {
        #_sender: ISender
        #_httpContextAccessor: HttpContextAccessor
    }

    class UserController {
        +UpdateUser(UpdateUserDTO dto): async Task<IActionResult>
    }
    class UpdateUserDTO {
        +DisplayName: string
        +Bio: string
        +Gender: string
        +Username: string
        +Avatar: IFormFile
        +Background: IFormFile
    }

    class UpdateUserCommand {
        +AccountId: Guid 
        +DisplayName: string
        +Bio: string
        +Gender: string
        +Username: string
        +Avatar: IFormFile
        +Background: IFormFile
    }
}

class UpdateUserCommandHandler {
    -_context : IApplicationDbContext
    -_unitOfWork: IUnitOfWork
    -_grpcAccountClient: GrpcAccountClient 
    -_grpcUploadFileClient: GrpcUploadFileClient
    +UpdateUserCommandHandler(context : IApplicationDbContext, unitOfWork : IUnitOfWork, grpcUploadFileClient : GrpcUploadFileClient, grpcAccountClient : GrpcAccountClient)
    +Handle(request : UpdateUserCommand, cancellationToken : CancellationToken) : Task<Result>
}

class UserError {
    {static} +NotFound: Error
    {static} +NullParameters: Error
}

enum GenderType {
    MALE
    FEMALE
}

' =========== Microservice class ===========
class IFormFile #Black;line:white;text:white
together {
    class GrpcUploadFileClient #LightSalmon;line:white;text:white
    class GrpcUpdateMultipleImageRequest #LightSalmon;line:white;text:white
    class GrpcUpdateAccountRequest #DarkViolet;line:white;text:white
    class GrpcAccountClient #DarkViolet;line:white;text:white
}

' =========== Library class ===========
interface "IRequest<TResponse>" #black;line:white;text:white
interface "IRequestHandler<TRequest, TResponse>" #black;line:white;text:white
' =========== Library class ===========

UserController --|> BaseApiController
UserController "1"--"1" UpdateUserCommand
UpdateUserCommand ..|> "IRequest<TResponse>"
UpdateUserDTO "1" o-- "0..2" IFormFile
UpdateUserCommand "1" o-- "0..2" IFormFile
UpdateUserCommand "1" o-- "1" UpdateUserDTO

UpdateUserCommandHandler ..|> "IRequestHandler<TRequest, TResponse>"
UpdateUserCommandHandler "1" --"1" UpdateUserCommand
UpdateUserCommandHandler "1" o--"1" IUnitOfWork
UpdateUserCommandHandler "1" o--"1" IApplicationDbContext
UpdateUserCommandHandler "1" o--"1" GrpcUploadFileClient
UpdateUserCommandHandler "1" o--"1" GrpcAccountClient

UpdateUserCommandHandler "1" --"1..*" UserError
UpdateUserCommandHandler "1" --"1" FileUtility
UpdateUserCommandHandler "1" --"1..*" GrpcUpdateMultipleImageRequest
UpdateUserCommandHandler "1" --"1..*" GrpcUpdateAccountRequest
UpdateUserCommandHandler "1" --"1..*" GenderType
UpdateUserCommandHandler "1" --"1" Result

Error "1..*" --o "1" UserError

@enduml