namespace UserService.Domain.Responses;
public class PaginatedSimpleUserListResponse : BasePaginatedResponse<SimpleUserResponse, AdvancePaginatedMetadata>;
public class PaginatedAdminGetUserListResponse : BasePaginatedResponse<AdminGetUserResponse, NumberedPaginatedMetadata>;
public class PaginatedAdminUserReportListResponse : BasePaginatedResponse<AdminUserReportResponse, NumberedPaginatedMetadata>;
public class PaginatedAdminUserReportDetailListResponse : BasePaginatedResponse<AdminUserReportDetailResponse, AdvancePaginatedMetadata>;