apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingredient-predict-api
spec:
  selector:
    matchLabels:
      app: ingredient-predict-api
  template:
    metadata:
      labels:
        app: ingredient-predict-api
    spec:
      restartPolicy: Always
      volumes:
        - name: model-volume
          hostPath:
            path: /home/server/models
            type: DirectoryOrCreate
      containers:
        - name: ingredient-predict-api
          image: taiduc113/tastopia:ingredient-predict-api
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: global-secret
            - secretRef:
                name: ingredient-predict-api-secret
          volumeMounts:
            - mountPath: /app/model
              name: model-volume
          resources:
            requests:
              cpu: "2000m"
              memory: "7Gi"
            limits:
              cpu: "6000m"
              memory: "10Gi"
          ports:
            - containerPort: 80
              protocol: TCP
