apiVersion: apps/v1
kind: Deployment
metadata:
  name: signalr
spec:
  selector:
    matchLabels:
      app: signalr
  template:
    metadata:
      labels:
        app: signalr
    spec:
      restartPolicy: Always
      containers:
      - name: signalr
        image: taiduc113/tastopia:signalr
        imagePullPolicy: Always
        envFrom:
          - secretRef:
              name: global-secret
          - secretRef:
              name: signalr-secret
        resources:
          requests:
            cpu: "250m"
            memory: "64Mi"
          limits:
            memory: "500M"
            cpu: "500m"
        ports:
        - containerPort: 80
          protocol: TCP
        - containerPort: 443
          protocol: TCP
