apiVersion: apps/v1
kind: Deployment
metadata:
  name: tracking-api
spec:
  selector:
    matchLabels:
      app: tracking-api
  template:
    metadata:
      labels:
        app: tracking-api
    spec:
      restartPolicy: Always
      initContainers:
        - name: db-wait
          image: mongo
          envFrom: 
            - secretRef:
                name: global-secret
          command: 
            - sh
            - -c
            - |
              until mongosh -u $MONGO_INITDB_ROOT_USERNAME -p \
                $MONGO_INITDB_ROOT_PASSWORD --authenticationDatabase admin \
                --quiet --eval "1"; echo $? \
                2>/dev/null; do

                  echo 'Waiting for database to be creatable...'
                  sleep 2
              done

              echo 'Database is online'
        - name: db-migrate
          envFrom: 
            - secretRef:
                name: global-secret
            - secretRef:
                name: tracking-api-secret
          image: taiduc113/tastopia:tracking-api
          command: ["dotnet","TrackingService.API.dll", "--seed"]
      containers:
      - name: tracking-api
        image: taiduc113/tastopia:tracking-api
        imagePullPolicy: Always
        envFrom:
          - secretRef:
              name: global-secret
          - secretRef:
              name: tracking-api-secret
        resources:
          requests:
            cpu: "250m"
            memory: "64Mi"
          limits:
            memory: "500M"
            cpu: "500m"
        ports:
        - containerPort: 80
          protocol: TCP
        - containerPort: 443
          protocol: TCP
