apiVersion: apps/v1
kind: Deployment
metadata:
  name: website
spec:
  selector:
    matchLabels:
      app: website
  template:
    metadata:
      labels:
        app: website
    spec:
      restartPolicy: Always
      initContainers:
        - name: waiter
          image: busybox
          envFrom:
            - secretRef:
                name: global-secret
          command: ["/bin/sh"]
          args: 
            - -c
            - |
              until nc -z api-gateway 80; do
                echo 'Waiting for api-gateway...'
                sleep 2
              done

              echo 'api-gateway is online'
      containers:
      - name: website
        image: taiduc113/tastopia:website
        imagePullPolicy: Always
        envFrom:
          - secretRef:
              name: website-secret
        resources:
          requests:
            cpu: "20m"
            memory: "64Mi"
          limits:
            memory: "500M"
            cpu: "500m"
        ports:
        - containerPort: 3000
          protocol: TCP
