---
- name: Install dependencies
  ansible.builtin.apt:
    name:
      - curl

- name: Download the public signing key for the Kubernetes package repositories
  ansible.builtin.get_url:
    url: https://storage.googleapis.com/minikube/releases/latest/minikube_latest_amd64.deb
    dest: /tmp/minikube.deb
    mode: '444'

- name: Install minikube
  ansible.builtin.command: dpkg -i /tmp/minikube.deb
  register: rc
  changed_when: rc is success

- name: Delete existing minikube node
  become: false
  ansible.builtin.command: minikube delete
  register: rc
  changed_when: rc is success

- name: Start minikube node
  become: false
  ansible.builtin.command: minikube start --cpus {{ minikube.cpus }} --memory {{ minikube.memory }}
  register: rc
  changed_when: rc is success

- name: Add minikube ip into /etc/hosts
  block:
    - name: Get the cluster ip
      become: false
      ansible.builtin.shell: sleep 5 && minikube ip
      register: rc
      changed_when: false

    - name: Add minikube ip to hosts file
      ansible.builtin.lineinfile:
        path: /etc/hosts
        regexp: 'minikube$'
        line: '{{ rc.stdout }} minikube'

- name: Install metric-server
  become: false
  ansible.builtin.command: minikube addons enable metrics-server
  register: rc
  changed_when: rc is success
