export const API_GATEWAY_SCHEME = process.env.NEXT_PUBLIC_API_GATEWAY_SCHEME;
export const API_GATEWAY_HOST = process.env.NEXT_PUBLIC_API_GATEWAY_HOST;
export const API_GATEWAY_PORT = process.env.NEXT_PUBLIC_API_GATEWAY_PORT;
export const SIGNALR_PORT = process.env.NEXT_PUBLIC_SIGNALR_PORT;

export const API_URI = `${API_GATEWAY_SCHEME}://${API_GATEWAY_HOST}:${API_GATEWAY_PORT}`;
export const SIGNALR_URI = `${API_GATEWAY_SCHEME}://${API_GATEWAY_HOST}:${SIGNALR_PORT}`;
