@startuml AdminUsecase
skinparam style strictuml
skinparam monochrome true
skinparam linetype polyline
skinparam defaultFontSize 12
left to right direction
actor "Admin" as admin
' actor "Admin" as admin
rectangle Ingredient-based<U+0020>food<U+0020>recommendation<U+0020>application {
    usecase "Logout" as ucLogout
    usecase "View statistic" as ucViewStatistic
    usecase "Administer reported recipes" as ucAdmReportedRepices
    usecase "Administer users" as ucAdmUser
    usecase "Administer role permission" as ucAdmRolePermis
    usecase "Administer recipes" as ucAdmRecipe
    usecase "Administer ingredients" as ucAdmIngre
    usecase "Administer subscriptions" as ucAdmSubcript
    usecase "Administer event" as ucAdmEvent
    usecase "View income" as ucViewIncome
    usecase "Export income" as ucExportIncome

    note "Read/\nUpdate/Delete" as noteAdmUser
    note "Create/Read/\nUpdate/Delete" as noteAdmRecipe
    note "Create/Read/\nUpdate/Delete" as noteAdmIngre
    note "Create/Read/\nUpdate/Delete" as noteAdmSubcipt
    note "Create/Read/\nUpdate/Delete" as noteAdmEvent
    note "Read/Delete" as noteAdmReportedRecipes
    note "Read/Update" as noteAmdRolePermis

    admin --> ucAdmUser
        ucAdmUser .. noteAdmUser
    admin --> ucAdmRecipe
        ucAdmRecipe <.. ucAdmReportedRepices : <<extend>>
            ucAdmReportedRepices .. noteAdmReportedRecipes
        ucAdmRecipe .. noteAdmRecipe
    admin --> ucAdmIngre
        ucAdmIngre .. noteAdmIngre
    admin --> ucAdmRolePermis
        ucAdmRolePermis .. noteAmdRolePermis
    admin --> ucAdmSubcript
        ucAdmSubcript <.. ucAdmEvent : <<extend>>
            ucAdmEvent .. noteAdmEvent
        ucAdmSubcript .. noteAdmSubcipt
    admin --> ucViewStatistic
    admin --> ucViewIncome
        ucViewIncome <.. ucExportIncome : <<extend>>
    admin --> ucLogout

}

@enduml
