@startuml UserUsecase
skinparam style strictuml
skinparam monochrome true
skinparam linetype polyline
skinparam defaultFontSize 12
left to right direction
actor "User" as user
actor "Premium User" as pUser
' actor "Admin" as admin
rectangle Ingredient-based<U+0020>food<U+0020>recommendation<U+0020>application {
    usecase "UC-2: Login" as ucLogin
    usecase "UC-10: Logout" as ucLogout

    usecase "UC-5: Search" as ucSearch
    usecase "UC-6: Search recipes" as ucSearchRecipes
    usecase "UC-7: Search user" as ucSearchUser

    usecase "UC-8: Browse recipes" as ucBrowseRecipes
    usecase "UC-11: Vote recipes" as ucVoteRecipe
    usecase "UC-12: Comment recipes" as ucCmtRecipe
    usecase "UC-13: Report recipes" as ucReportRecipe
    usecase "UC-14: Bookmark recipe" as ucBookmarkRecipe
    usecase "UC-15: View recipe detail" as ucViewRecipeDetail
    usecase "UC-16: Use guided cooking mode" as ucGuidedCCM
    usecase "UC-9: View other user profile" as ucViewUSProfile

    usecase "UC-17: View menu" as ucViewMenu
    usecase "UC-18: Manage profile" as ucManageProfile
    usecase "UC-19: Manage own recipe" as ucManageRecipe
    usecase "UC-20: Manage allergic\n ingredients" as ucManageAller
    usecase "UC-21: Manage settings" as ucManageSetting
    usecase "UC-22: Setting language" as ucSetLang
    usecase "UC-23: Setting theme" as ucSetTheme
    usecase "UC-24: View recent recipes" as ucViewRecentRecipes
    usecase "UC-25: Upgrade to premium" as ucUpgradeToPremium

    usecase "UC-26: View notifications" as ucViewNotif
    
    note "Create/Read/\nUpdate/Delete" as noteManageRecipe
    note "Create/Read/\nUpdate/Delete" as noteManageAller
    note "Read/Update" as noteManageProfile
    note "Create/Read/\nUpdate/Delete" as noteVoteRecipe
    note "Create/Read/\nUpdate/Delete" as noteCmtRecipe
    note "Create/Read/\nUpdate/Delete" as noteBookmarkRecipe
    note "{Only available for User}" as noteUpgradeToPremium


    user --> ucSearch
        ucSearch <.. ucSearchUser : <<extend>>
        ucSearch <.. ucSearchRecipes : <<extend>>

    user --> ucBrowseRecipes
        ucBrowseRecipes <.. ucVoteRecipe : <<extend>>
            ucVoteRecipe . noteVoteRecipe
        ucBrowseRecipes <.. ucCmtRecipe : <<extend>>
            ucCmtRecipe . noteCmtRecipe
        ucBrowseRecipes <.. ucReportRecipe : <<extend>>
        ucBrowseRecipes <.. ucViewRecipeDetail : <<extend>>
            ucViewRecipeDetail <.. ucGuidedCCM : <<extend>>
        ucBrowseRecipes <.. ucBookmarkRecipe : <<extend>>
            ucBookmarkRecipe . noteBookmarkRecipe
        ucBrowseRecipes <.. ucViewUSProfile : <<extend>>

    user --> ucViewMenu
        ucViewMenu <.. ucManageProfile : <<extend>>
            ucManageProfile . noteManageProfile
            ucManageProfile <.. ucManageRecipe : <<extend>>
                ucManageRecipe . noteManageRecipe
            ucManageProfile <.. ucManageAller : <<extend>>
                ucManageAller . noteManageAller
        ucViewMenu <.. ucManageSetting : <<extend>>
            ucManageSetting <.. ucSetLang : <<extend>>
            ucManageSetting <.. ucSetTheme : <<extend>>
        ucViewMenu <.. ucViewRecentRecipes : <<extend>>
        ucViewMenu <.. ucUpgradeToPremium : <<extend>>
            ucUpgradeToPremium . noteUpgradeToPremium
        ucViewMenu <.. ucLogout : <<extend>>

    user --> ucViewNotif

    ucSearch .....> ucLogin : <<include>>
    ucBrowseRecipes .....> ucLogin : <<include>>
    ucViewMenu .....> ucLogin : <<include>>
    ucViewNotif .....>ucLogin : <<include>>


    usecase "UC-27: Command by voice \n in cooking mode" as ucCommandVoiceCCM
    usecase "UC-28: Recognize ingredients \n by capturing image" as ucRecognizeIngre
    usecase "UC-29: Manage subscription plan" as ucMngSubcriptPlan
    

    note "{Only available for Premium User}" as noteMngSubcriptPlan
    note "{Only available for Premium User}" as noteCommandVoiceCCM


    pUser -|> user
    pUser --> ucRecognizeIngre
    ucGuidedCCM <.. ucCommandVoiceCCM : <<extend>>
        ucCommandVoiceCCM . noteCommandVoiceCCM
    ucViewMenu <.. ucMngSubcriptPlan : <<extend>>
        ucMngSubcriptPlan . noteMngSubcriptPlan

    ucRecognizeIngre .....> ucLogin : <<include>>

}

@enduml
