@startuml
left to right direction
' actor "Guest" as guest
actor "User" as user
actor "Premium User" as pUser
' actor "Admin" as admin



rectangle Ingredient-based<U+0020>food<U+0020>recommendation<U+0020>application {
'   usecase "Register" as ucRegister
  usecase "Search posts" as ucSearchPosts
  usecase "Browse posts" as ucBrowsePosts
  usecase "View user profile" as ucViewUSProfile
  usecase "Search user" as ucSearchUser

  usecase "Login" as ucLogin
  usecase "Search media" as ucSearchMedia
  usecase "Search recipes" as ucSearchRecipes
  usecase "Interact with posts" as ucInteractPosts
  usecase "Bookmark post" as ucBookmarkPost
  usecase "Manage own post" as ucManagePost
  usecase "Manage profile" as ucManageProfile
  usecase "Manage settings" as ucManageSetting
  usecase "View notifications" as ucViewNotif
  usecase "Step-to-step cooking mode" as ucStepToStepCCM
  note "Create/Read/\nUpdate/Delete" as noteManagePost
  note "Read/Update" as noteManageProfile


  usecase "Command by voice \n in cooking mode" as ucCommandVoiceCCM
  usecase "Recognize ingredients \n by capturing image" as ucRecognizeIngre

'   usecase "View statistic" as ucViewStatistic
'   usecase "View report" as ucViewRepost
'   usecase "Administer users" as ucAdmUser
'   usecase "Administer permission" as ucAdmPermis
'   usecase "Administer posts" as ucAdmPost
'   usecase "Administer recipes" as ucAdmRecipes
'   usecase "Administer ingredients" as ucAdmIngre

  


}
' guest --> ucRegister
' guest --> ucSearchPosts
' guest --> ucBrowsePosts
' ucBrowsePosts --> ucViewUSProfile
' guest --> ucSearchUser
' ucSearchUser --> ucViewUSProfile


user --> ucSearchMedia
user --> ucSearchRecipes
user --> ucInteractPosts
user --> ucBookmarkPost
user --> ucManagePost
user --> ucManageProfile
user --> ucManageSetting
user --> ucViewNotif
user --> ucStepToStepCCM

ucManagePost . noteManagePost
ucManageProfile . noteManageProfile



ucSearchMedia ..> ucLogin : <<include>>
ucSearchRecipes ..> ucLogin : <<include>>
ucInteractPosts ..> ucLogin : <<include>>
ucBookmarkPost ..> ucLogin : <<include>>
ucManagePost ..> ucLogin : <<include>>
ucManageProfile ..> ucLogin : <<include>>
ucManageSetting ..> ucLogin : <<include>>
ucViewNotif ..> ucLogin : <<include>>
ucStepToStepCCM ..> ucLogin : <<include>>


@enduml
