@startuml GetRecipeComment
actor User
boundary MobileUI
participant ApiGateway
participant RecipeService
participant UserService
database Postgresql
database MongoDB

User -> MobileUI: 1. Enter recipe detail screen
activate MobileUI

MobileUI -> ApiGateway: 2. Get recipe comments
activate ApiGateway

ApiGateway -> RecipeService: 3. Forward request
activate RecipeService

database MongoDB
RecipeService -> MongoDB: 4. Query data
activate MongoDB
RecipeService <-- MongoDB: 5. return response
deactivate MongoDB

RecipeService -> UserService: 6. gRPC call to get user's \n information list <<gRPC>>
activate UserService
UserService -> Postgresql: 7. Query data
activate Postgresql
UserService <-- Postgresql: 8. return response
deactivate Postgresql
RecipeService <-- UserService: 9. return user's information list <<gRPC>>
deactivate UserService

ApiGateway <-- RecipeService: 10. return recipe comments list
deactivate RecipeService
MobileUI <-- ApiGateway: 11. Forward response
deactivate ApiGateway
User <-- MobileUI: 12. Display recipe comments list
deactivate MobileUI

@enduml
