@startuml GrpcRecipeSerciveClassDiagram
!include doc/SDS/CommonClassDiagram/ResultAndError.plantuml
!include doc/SDS/CommonClassDiagram/UnitOfWork.plantuml
!include doc/SDS/CommonClassDiagram/Tracking/TrackingDbContext.plantuml
skinparam classAttributeIconSize 0
skinparam linetype polyline
skinparam nodesep 50
skinparam ranksep 50
skinparam classAttributeIconSize 0
skinparam classBackgroundColor CadetBlue
skinparam classBorderColor While
skinparam classFontColor While
skinparam classAttributeFontColor While

hide circle

class TrackingServiceConsumer {
    #_sender: ISender
    #_logger: ILogger
    +CreateUserViewRecipeDetailConsumer(ConsumeContext<CreateUserViewRecipeDetailEvent> context): async Task
}

class CreateUserVewRecipeDetailCommand {
    +AccountId: Guid?
    +RecipeId: Guid?
    +ViewTime: DateTime?
}

class CreateUserVewRecipeDetailCommandHandler{
    -_context: IApplicationDbContext
    -_unitOfWork: IUnitOfWork
    +Handle(CreateUserVewRecipeDetailCommand request, CancellationToken cancellationToken): async Task<Result>
}

' Event DTO
class CreateUserViewRecipeDetailEvent{
    +AccountId: Guid?
    +RecipeId: Guid?
    +ViewTime: DateTime?
}

class UserViewRecipeDetailError {
    {static} +NotFound: Error
    {static} +AddUserViewRecipeDetailFail: Error
    {static} +DeleteUserViewRecipeDetailFail: Error
    {static} +UpdateUserViewRecipeDetailFail: Error
}

' =========== Library class ===========
interface "IRequest<TResponse>" #black;line:white;text:white
interface "IRequestHandler<TRequest, TResponse>" #black;line:white;text:white
' =========== Library class ===========

CreateUserVewRecipeDetailCommand ..|> "IRequest<TResponse>"
CreateUserVewRecipeDetailCommandHandler ..|> "IRequestHandler<TRequest, TResponse>"

TrackingServiceConsumer "1"--"1" CreateUserViewRecipeDetailEvent
TrackingServiceConsumer "1"--"1" CreateUserVewRecipeDetailCommand

CreateUserVewRecipeDetailCommandHandler "1"--"1" CreateUserVewRecipeDetailCommand
CreateUserVewRecipeDetailCommandHandler "1"--"1..*" Result
CreateUserVewRecipeDetailCommandHandler "1" o-- "1" IApplicationDbContext
CreateUserVewRecipeDetailCommandHandler "1" o-- "1" IUnitOfWork
CreateUserVewRecipeDetailCommandHandler "1"--"1..*" UserViewRecipeDetailError
CreateUserVewRecipeDetailCommandHandler "1"--"1..*" UserViewRecipeDetail


' =================STYLE=================
TrackingServiceConsumer -[hidden]down-|> CreateUserVewRecipeDetailCommand

CreateUserVewRecipeDetailCommand -[hidden]down-|> CreateUserVewRecipeDetailCommandHandler

Error "1" --"1..*" UserViewRecipeDetailError
@enduml