
@startuml ClassDiagram
!include doc/SDS/CommonClassDiagram/ResultAndError.plantuml
!include doc/SDS/CommonClassDiagram/User/UserDbContext.plantuml 
!include doc/SDS/CommonClassDiagram/UnitOfWork.plantuml
!include doc/SDS/CommonClassDiagram/ServiceBus.plantuml

skinparam classAttributeIconSize 0
skinparam linetype polyline
skinparam nodesep 20
skinparam ranksep 20
hide circle

class BaseApiController {
    #_sender: ISender
    #_httpContextAccessor: HttpContextAccessor
}

class AdminController {
    +AdminMarkAllReport(markAllUserReportDTO : MarkAllUserReportDTO): async Task<IActionResult>
}

class MarkAllReportCommand {
    +AccountId : Guid
    +IsReopened : bool
    +CurrentAccountId : Guid
}

class MarkAllReportCommandHandler {
    -_context : IApplicationDbContext
    -_serviceBus: IServiceBus 
    -_unitOfWork: IUnitOfWork 
    +MarkReportCommandHandler(context : IApplicationDbContext, serviceBus : IServiceBus, unitOfWork : IUnitOfWork)
    +Handle(request: MarkAllReportCommand, cancellationToken: CancellationToken) : Task<Result>
}

class MarkAllUserReportDTO {
    +AccountId : Guid
    +IsReopened : bool
}

class UserReportError {
    {static} +NotFound: Error
    {static} +AddUserReportFail: Error
    {static} +DeleteUserReportFail: Error
    {static} +UpdateUserReportFail: Error
    {static} +NullParameter: Error
    {static} +AlreadyMarkComplete: Error
    {static} +AlreadyPending: Error
}

' =========== Library class ===========
interface "IRequest<TResponse>" #black;line:white;text:white
interface "IRequestHandler<TRequest, TResponse>" #black;line:white;text:white
' =========== Library class ===========
together {
    class AddActivityLogEvent #CadetBlue;line:white;text:white
}

AdminController --|> BaseApiController
AdminController "1"--"1" ReportDTO
AdminController "1"--"1" MarkAllReportCommand

MarkAllReportCommand ..|> "IRequest<TResponse>"

MarkAllReportCommandHandler ..|> "IRequestHandler<TRequest, TResponse>"
MarkAllReportCommandHandler "1" --"1" MarkAllReportCommandHandler
MarkAllReportCommandHandler "1" o--"1" IApplicationDbContext
MarkAllReportCommandHandler "1" o--"1" IServiceBus
MarkAllReportCommandHandler "1" o--"1" IUnitOfWork
MarkAllReportCommandHandler "1" --"1" Result
MarkAllReportCommandHandler "1" --"1..*" AddActivityLogEvent
MarkAllReportCommandHandler "1" --"1..*" UserReport
MarkAllReportCommandHandler "1" --"1..*" UserReportError

Error "1..*" --o "1" UserReportError

@enduml