@startuml Sequence
title "Admin update tag"
' Style section
<style>
  sequenceDiagram {
    reference {
      BackGroundColor white
    }
}
</style>

actor Admin
boundary WebsiteUI
participant "<<coordinator>>\nApiGateway" as ApiGateway
participant "<<service>>\n IdentityService" as IdentityService
participant "<<service>>\n RecipeService" as RecipeService
participant "<<service>>\n UploadFileService" as UploadFileService
participant "<<service>>\n Cloudinary" as Cloudinary
participant "<<coordinator>>\nRabbitmq" as Rabbitmq
database MongoDB

Admin -> WebsiteUI++: 1. Fill the update tag form and \n click Update button
WebsiteUI -> ApiGateway++: 2. Admin update tag

activate IdentityService
ref over ApiGateway, IdentityService: 3. Get access token
ApiGateway -[hidden]-> IdentityService
deactivate IdentityService

alt Current user is not admin
    WebsiteUI <-- ApiGateway: 4A. Return error message
    Admin <-- WebsiteUI: 4A.1. Display error message
else Current user is admin
    ApiGateway -> RecipeService++: 4. Forward request
    opt Tag image is not null
        RecipeService -> UploadFileService++: 5A. gRPC call to upload tag's images <<gRPC>>
        UploadFileService -> Cloudinary++: 5A.1. Upload image to cloudinary
        UploadFileService <-- Cloudinary--: 5A.2. Return response
        alt Upload to cloudinary fail
            RecipeService <-- UploadFileService: 5A.3. Return upload image fail error
            ApiGateway <-- RecipeService: 5A.4. Return upload image fail error
            WebsiteUI <-- ApiGateway: 5A.5. Forward response
            Admin <-- WebsiteUI: 5A.6. Display upload image fail error
        else Upload to cloudinary success 
            RecipeService <-- UploadFileService--: 5A.7. Return tag's image urls list <<gRPC>>
        end alt 
    end opt
    opt Tag dishtype category limit reached
            ApiGateway <-- RecipeService: 6A.1. Return exceed limit dishtype tag error
            WebsiteUI <-- ApiGateway: 6A.2. Forward response
            Admin <-- WebsiteUI: 6A.3. Display exceed limit dishtype tag error
    end opt
    RecipeService -> MongoDB++: 7. Insert data
    RecipeService <-- MongoDB--: 8. Return response
    alt Update tag to database fail
        opt Tag image is not null
            RecipeService -> RecipeService: 9A. Roll back images
            activate RecipeService
            RecipeService -> Rabbitmq: 9A.1. Publish "DeleteMultipleImageEvent" \n event <<Async>>
            deactivate RecipeService
            activate Rabbitmq
            Rabbitmq -> UploadFileService: 9A.2. Deliver "DeleteMultipleImageEvent"\n message
            deactivate Rabbitmq
            activate UploadFileService
            UploadFileService -> Cloudinary++: 9A.3. Consume message and call \n cloudinary to delete images
            UploadFileService <-- Cloudinary--: 9A.4. Return response
            destroy UploadFileService
            deactivate UploadFileService
        end opt
        ApiGateway <-- RecipeService: 10A.5. Return update tag fail error
        WebsiteUI <-- ApiGateway: 10A.6. Forward response
        Admin <-- WebsiteUI: 10A.7. Display update tag fail error.
    else Update tag to database success
        ApiGateway <-- RecipeService: 11. Return update tag success message
        WebsiteUI <-- ApiGateway: 12. Forward response
        Admin <-- WebsiteUI: 13. Display update tag success message
        RecipeService -> Rabbitmq: 14. Publish "AddActivityLogCommand" event <<Async>>
        activate Rabbitmq
        ref over Rabbitmq: 15. Add activity log event
        RecipeService -[hidden]-> Rabbitmq
        deactivate Rabbitmq
        destroy Rabbitmq
        deactivate RecipeService
    end alt 
end alt

@enduml