apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
spec:
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      restartPolicy: Always
      containers:
      - name: api-gateway
        image: taiduc113/tastopia:api-gateway
        envFrom:
          - secretRef:
              name: global-secret
          - secretRef:
              name: api-gateway-secret
        resources:
          requests:
            cpu: "250m"
            memory: "64Mi"
          limits:
            memory: "500M"
            cpu: "500m"
        ports:
        - containerPort: 80
          protocol: TCP
        - containerPort: 443
          protocol: TCP
