apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
spec:
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      restartPolicy: Always
      initContainers:
      - name: redis-wait
        image: redis:alpine
        envFrom:
          - secretRef:
              name: global-secret
        command: 
          - sh
          - -c
          - |
            until redis-cli -h redis -p $REDIS_PORT ping 2>/dev/null | grep -q PONG; do
              echo 'Waiting for redis...'
              sleep 2
            done

            echo 'Redis is ready'
      - name: identity-service-wait
        image: curlimages/curl
        envFrom:
          - secretRef:
              name: global-secret
        command: 
          - sh
          - -c
          - |
            until curl -s "$CONSUL_SCHEME://consul:$CONSUL_PORT/v1/health/checks/identity-service" \
                   | grep -q '"Status": "passing"'; do

                echo 'Waiting for identity-service...'
                sleep 2
            done
            
            echo 'identity-service is ready'
      containers:
      - name: api-gateway
        image: taiduc113/tastopia:api-gateway
        envFrom:
          - secretRef:
              name: global-secret
          - secretRef:
              name: api-gateway-secret
        resources:
          requests:
            cpu: "250m"
            memory: "64Mi"
          limits:
            memory: "500M"
            cpu: "500m"
        ports:
        - containerPort: 80
          protocol: TCP
        - containerPort: 443
          protocol: TCP
