apiVersion: apps/v1
kind: Deployment
metadata:
  name: consul
spec:
  selector:
    matchLabels:
      app: consul
  template:
    metadata:
      labels:
        app: consul
    spec:
      containers:
      - name: consul
        image: hashicorp/consul
        livenessProbe:
          exec:
            command:
              - sh
              - -c
              - |
                curl -f http://localhost:8500/v1/status/leader || exit 1
          failureThreshold: 3
          initialDelaySeconds: 30
          timeoutSeconds: 10
          periodSeconds: 30
        resources:
          requests:
            cpu: "250m"
            memory: "64Mi"
          limits:
            memory: "500M"
            cpu: "500m"
        ports:
        - containerPort: 8500
          protocol: TCP
