apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-api
spec:
  selector:
    matchLabels:
      app: identity-api
  template:
    metadata:
      labels:
        app: identity-api
    spec:
      restartPolicy: Always
      initContainers:
        - name: db-wait
          image: busybox:1.36
          envFrom: 
            - secretRef:
                name: global-secret
          command: 
            - sh
            - -c
            - |
              until nc -z $DB_HOST $DB_PORT; do
                echo 'Waiting for database...'
                sleep 2
              done

              echo 'Database is online'
        - name: db-migrate
          image: taiduc113/tastopia:identity-api
          command: ["dotnet","DuendeIdentityServer.dll", "--migrate", "--seed"]
      containers:
      - name: identity-api
        image: taiduc113/tastopia:identity-api
        imagePullPolicy: Always
        envFrom:
          - secretRef:
              name: global-secret
          - secretRef:
              name: identity-api-secret
        resources:
          requests:
            cpu: "250m"
            memory: "64Mi"
          limits:
            memory: "500M"
            cpu: "500m"
        ports:
        - containerPort: 80
          protocol: TCP
        - containerPort: 443
          protocol: TCP
