apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc
      restartPolicy: Always
      containers:
      - name: postgres
        envFrom:
          - secretRef:
              name: global-secret
        image: postgres:17.0-alpine
        volumeMounts:
          - name: postgres-storage
            mountPath: /var/lib/postgresql/data
        livenessProbe:
          exec:
            command:
              - sh
              - -c
              - | 
                pg_isready -U ${POSTGRES_USER} || exit 1
          failureThreshold: 10
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 15
        resources:
          requests:
            cpu: "250m"
            memory: "64Mi"
          limits:
            memory: "500M"
            cpu: "500m"
        ports:
        - containerPort: 5432
          protocol: TCP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce

