apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-api
spec:
  selector:
    matchLabels:
      app: user-api
  template:
    metadata:
      labels:
        app: user-api
    spec:
      restartPolicy: Always
      initContainers:
        - name: db-wait
          image: postgres:17.0-alpine
          envFrom: 
            - secretRef:
                name: global-secret
          command: 
            - sh
            - -c
            - |
              until PGPASSWORD=$POSTGRES_PASSWORD psql \
                -h $DB_HOST -U $POSTGRES_USER -d postgres \
                -c '\q' \
                2>/dev/null; do

                  echo 'Waiting for database to be creatable...'
                  sleep 2
              done

              echo 'Database is online'
        - name: db-migrate
          envFrom: 
            - secretRef:
                name: global-secret
            - secretRef:
                name: user-api-secret
          image: taiduc113/tastopia:user-api
          command: ["dotnet","UserService.API.dll", "--migrate", "--seed"]
      containers:
      - name: user-api
        image: taiduc113/tastopia:user-api
        envFrom:
          - secretRef:
              name: global-secret
          - secretRef:
              name: user-api-secret
        resources:
          requests:
            cpu: "250m"
            memory: "64Mi"
          limits:
            memory: "500M"
            cpu: "500m"
        ports:
        - containerPort: 80
          protocol: TCP
        - containerPort: 443
          protocol: TCP
