apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-api
spec:
  selector:
    matchLabels:
      app: user-api
  template:
    metadata:
      labels:
        app: user-api
    spec:
      restartPolicy: Always
      volumes:
        - name: tls-certs
          secret:
            secretName: user-api-tls
            items:
              - key: tls.crt
                path: tls.crt
              - key: tls.key
                path: tls.key
      containers:
      - name: user-api
        image: taiduc113/tastopia:user-api
        volumeMounts:
          - name: tls-certs
            mountPath: /etc/ssl/certs/server-cert.crt
            subPath: tls.crt
          - name: tls-certs
            mountPath: /etc/ssl/private/private-key.pem
            subPath: tls.key
        envFrom:
          - secretRef:
              name: global-secret
          - secretRef:
              name: user-api-secret
        resources:
          requests:
            cpu: "250m"
            memory: "64Mi"
          limits:
            memory: "500M"
            cpu: "500m"
        ports:
        - containerPort: 80
          protocol: TCP
        - containerPort: 443
          protocol: TCP
