@startuml ClassDiagram
!include doc/SDS/CommonClassDiagram/ResultAndError.plantuml
!include doc/SDS/CommonClassDiagram/UnitOfWork.plantuml
!include doc/SDS/CommonClassDiagram/Tracking/TrackingDbContext.plantuml
skinparam classAttributeIconSize 0
skinparam linetype polyline
skinparam nodesep 100
skinparam ranksep 100
skinparam classAttributeIconSize 0

hide circle

class CreateUserViewRecipeDetailConsumer #CadetBlue;line:white;text:white {
    #_sender: ISender
    +CreateUserViewRecipeDetailConsumer(sender: ISender)
    +Consume(context: ConsumeContext<CreateUserViewRecipeDetailEvent>): async Task
}

class CreateUserViewRecipeDetailCommand implements "IRequest<TResponse>" {
    +AccountId: Guid
    +Keyword: string
    +ViewTime: DateTime
}

class CreateUserViewRecipeDetailCommandHandler {
    -_context: IApplicationDbContext
    -_unitOfWork: IUnitOfWork
    +Handle(request: CreateUserViewRecipeDetailCommand, cancellationToken: CancellationToken): async Task<Result>
}

' Event DTO
class CreateUserViewRecipeDetailEvent #CadetBlue;line:white;text:white {
    +AccountId: Guid
    +Keyword: string
    +ViewTime: DateTime
}

class UserViewRecipeDetailError {
    {static} +AddUserViewRecipeDetailFail: Error
}

' =========== Library class ===========
interface "IRequest<TResponse>" #black;line:white;text:white
interface "IRequestHandler<TRequest, TResponse>" #black;line:white;text:white
' =========== Library class ===========

CreateUserViewRecipeDetailCommandHandler ..|> "IRequestHandler<TRequest, TResponse>"

CreateUserViewRecipeDetailConsumer "1" -- "1" CreateUserViewRecipeDetailEvent
CreateUserViewRecipeDetailConsumer "1" -- "1" CreateUserViewRecipeDetailCommand

CreateUserViewRecipeDetailCommandHandler "1" -- "1" CreateUserViewRecipeDetailCommand
CreateUserViewRecipeDetailCommandHandler "1" o-- "1" IApplicationDbContext
CreateUserViewRecipeDetailCommandHandler "1" o-- "1" IUnitOfWork

CreateUserViewRecipeDetailCommandHandler "1" -- "1..*" Result
CreateUserViewRecipeDetailCommandHandler "1" -- "1..*" UserViewRecipeDetailError
CreateUserViewRecipeDetailCommandHandler "1" -- "1..*" UserViewRecipeDetail

UserViewRecipeDetailError "1" o-- "1..*" Error

' =================STYLE=================

@enduml