---
- name: Install dependencies
  ansible.builtin.apt:
    name:
      - curl
      - bash
    state: present

- name: Add Infisical CLI repository
  ansible.builtin.shell:
    executable: bash
    cmd: |
      set -o pipefail
      curl -1sLf {{ setup_link }} | bash
  register: rc
  changed_when: rc is success

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true

- name: Install Infisical
  ansible.builtin.apt:
    name: infisical
