---
- name: Check if infisical exists
  ansible.builtin.command: command -v infisical
  register: check
  changed_when: false
  failed_when: false

- name: Load OS-specific tasks
  include_tasks: '{{ ansible_os_family | lower }}.yml'
  when: check.rc != 0
