@startuml Sequence
title "Admin create tag"
' Style section
<style>
  sequenceDiagram {
    reference {
      BackGroundColor white
    }
}
</style>

actor Admin
boundary WebsiteUI
participant "<<coordinator>>\nApiGateway" as ApiGateway
participant "<<service>>\n IdentityService" as IdentityService
participant "<<service>>\n RecipeService" as RecipeService
participant "<<service>>\n UploadFileService" as UploadFileService
participant "<<service>>\n Cloudinary" as Cloudinary
participant "<<coordinator>>\nRabbitmq" as Rabbitmq
database MongoDB

Admin -> WebsiteUI++: 1. Fill the create tag form and \n click Create button
WebsiteUI -> ApiGateway++: 2. Admin create tag

activate IdentityService
ref over ApiGateway, IdentityService: 3. Get access token
ApiGateway -[hidden]-> IdentityService
deactivate IdentityService

alt Current user is not admin
    WebsiteUI <-- ApiGateway: 4A. Return error message
    Admin <-- WebsiteUI: 4A.1. Display error message
else Current user is admin
    ApiGateway -> RecipeService++: 4. Forward request
    RecipeService -> UploadFileService++: 5. gRPC call to upload tag's images <<gRPC>>
    UploadFileService -> Cloudinary++: 6. Upload image to cloudinary
    UploadFileService <-- Cloudinary--: 7. Return response
    alt Upload to cloudinary fail
        RecipeService <-- UploadFileService: 8A. Return upload image fail error
        ApiGateway <-- RecipeService: 8A.1. Return upload image fail error
        WebsiteUI <-- ApiGateway: 8A.2. Forward response
        Admin <-- WebsiteUI: 8A.3. Display upload image fail error
    else Upload to cloudinary success 
        RecipeService <-- UploadFileService--: 9. Return tag's image urls list <<gRPC>>
        RecipeService -> MongoDB++: 10. Insert data
        RecipeService <-- MongoDB--: 11. Return response
        opt Tag dishtype category limit reached
            ApiGateway <-- RecipeService: 12A.1. Return exceed limit dishtype tag error
            WebsiteUI <-- ApiGateway: 12A.2. Forward response
            Admin <-- WebsiteUI: 12A.3. Display exceed limit dishtype tag error
        end opt
        alt Add tag to database fail
            RecipeService -> RecipeService: 13A. Roll back images
            activate RecipeService
            RecipeService -> Rabbitmq: 13A.1. Publish "DeleteMultipleImageEvent" \n event <<Async>>
            deactivate RecipeService
            activate Rabbitmq
            Rabbitmq -> UploadFileService: 13A.2. Deliver "DeleteMultipleImageEvent"\n message
            deactivate Rabbitmq
            activate UploadFileService
            UploadFileService -> Cloudinary++: 13A.3. Consume message and call \n cloudinary to delete images
            UploadFileService <-- Cloudinary--: 12A.4. Return response
            destroy UploadFileService
            deactivate UploadFileService
            ApiGateway <-- RecipeService: 13A.5. Return add tag fail error
            WebsiteUI <-- ApiGateway: 13A.6. Forward response
            Admin <-- WebsiteUI: 13A.7. Display add tag fail error.
        else Add tag to database success
            RecipeService -> Rabbitmq: 14. Publish "AddActivityLogCommand" event <<Async>>
            activate Rabbitmq
            ref over Rabbitmq: 15. Add activity log event
            RecipeService -[hidden]-> Rabbitmq
            deactivate Rabbitmq
            destroy Rabbitmq
            ApiGateway <-- RecipeService: 16. Return add tag success message
            WebsiteUI <-- ApiGateway: 17. Forward response
            Admin <-- WebsiteUI: 18. Display add tag success message
        end alt 
    end alt 
end alt

@enduml