@startuml SuperAdminUsecase
skinparam style strictuml
skinparam monochrome true
skinparam linetype polyline
skinparam defaultFontSize 12
left to right direction
actor "Super Admin" as admin
actor "Cloudinary" as cl

rectangle Ingredient-based<U+0020>food<U+0020>recommendation<U+0020>application {
    usecase "UC-2: Login" as ucLogin
    usecase "UC-4: Forgot password" as ucForgotPassword
    usecase "UC-8: Logout" as ucLogout
    usecase "UC-11: Manage profile" as ucManageProfile
    usecase "UC-10: Manage settings" as ucManageSetting

    usecase "UC-24: Administer users" as ucAdmUser
    usecase "UC-25: Administer tags" as ucAdmTags
    usecase "UC-26: Administer recipes" as ucAdmRecipe
    usecase "UC-27: View statistics" as ucViewStatistic
    usecase "UC-28: Administer reports" as ucAdmReport
    usecase "UC-29: Administer admins" as ucAdmAdmin
    usecase "UC-30: View activity log" as ucViewActivityLog

    note "Read/Delete/Restore" as noteAdmUser
    note "Read/Delete/Restore" as noteAdmRecipe
    note "Create/Read/\nUpdate/Delete/\nRestore" as noteAdmTag
    note "Create/Read/\nDelete/Restore" as noteAdmAdmin
    note "Read/Delete/Restore" as noteAdmReport

    admin --> ucAdmUser
        ucAdmUser .. noteAdmUser
    admin --> ucAdmRecipe
        ucAdmRecipe .. noteAdmRecipe
    admin --> ucAdmReport
        ucAdmReport .. noteAdmReport
    admin --> ucAdmTags
        ucAdmTags .. noteAdmTag
    admin --> ucViewStatistic
    admin --> ucViewActivityLog
    admin --> ucManageProfile
    admin --> ucManageSetting
    admin --> ucLogout
    admin --> ucAdmAdmin
        ucAdmAdmin .. noteAdmAdmin

    ucLogout .....> ucLogin : <<include>>
    ucViewStatistic .....> ucLogin : <<include>>
    ucAdmUser .....> ucLogin : <<include>>
    ucAdmRecipe .....> ucLogin : <<include>>
    ucAdmTags .....> ucLogin : <<include>>
    ucManageProfile .....> ucLogin : <<include>>
    ucViewActivityLog .....> ucLogin : <<include>>
    ucAdmAdmin .....> ucLogin : <<include>>

    ucLogin <.. ucForgotPassword : <<extend>>

    cl --up---> ucManageProfile
    cl --up----> ucAdmEvent
    cl --up---> ucAdmTags
}

@enduml
