@startuml SuperAdminUsecase
skinparam style strictuml
skinparam monochrome true
skinparam linetype polyline
skinparam defaultFontSize 12
left to right direction
actor "Super Admin" as admin
actor "Cloudinary" as cl
actor "SpeedSMS         " as sms
actor "Gmail      " as gmail

rectangle Ingredient-based<U+0020>food<U+0020>recommendation<U+0020>dashboard<U+0020>website {
    usecase "UC-W-01: Login" as ucLogin
    usecase "UC-W-02: Forgot password" as ucForgotPassword
    usecase "UC-W-03: Logout" as ucLogout
    usecase "UC-W-04: Change settings" as ucManageSetting
    usecase "UC-W-05: Manage profile" as ucManageProfile

    usecase "UC-W-06: Administer users" as ucAdmUser
    usecase "UC-W-07: Administer tags" as ucAdmTags
    usecase "UC-W-08: Administer recipes" as ucAdmRecipe
    usecase "UC-W-09: View statistics" as ucViewStatistic
    usecase "UC-W-10: Administer reports" as ucAdmReport
    usecase "UC-W-11: Administer admins" as ucAdmAdmin
    usecase "UC-W-12: View activity log" as ucViewActivityLog

    note "Read/Delete/Restore" as noteAdmUser
    note "Read/Delete/Restore" as noteAdmRecipe
    note "Create/Read/\nUpdate/Delete/\nRestore" as noteAdmTag
    note "Create/Read/\nDelete/Restore" as noteAdmAdmin
    note "Read/Delete/Restore" as noteAdmReport

    admin -- ucAdmUser
        ucAdmUser .. noteAdmUser
    admin -- ucAdmRecipe
        ucAdmRecipe .. noteAdmRecipe
    admin -- ucAdmReport
        ucAdmReport .. noteAdmReport
    admin -- ucAdmTags
        ucAdmTags .. noteAdmTag
    admin -- ucViewStatistic
    admin -- ucViewActivityLog
    admin -- ucManageProfile
    admin -- ucManageSetting
    admin -- ucLogout
    admin -- ucAdmAdmin
        ucAdmAdmin .. noteAdmAdmin

    ucLogout .....> ucLogin : <<include>>
    ucViewStatistic .....> ucLogin : <<include>>
    ucAdmUser .....> ucLogin : <<include>>
    ucAdmRecipe .....> ucLogin : <<include>>
    ucAdmTags .....> ucLogin : <<include>>
    ucManageProfile .....> ucLogin : <<include>>
    ucViewActivityLog .....> ucLogin : <<include>>
    ucAdmAdmin .....> ucLogin : <<include>>

    ucLogin <.. ucForgotPassword : <<extend>>

    cl --up-> ucManageProfile
    cl --up-> ucAdmTags
    sms --up-> ucForgotPassword
    gmail --up-> ucForgotPassword
}

@enduml
