@startuml Sequence
title "Get tags"
' Style section
<style>
  sequenceDiagram {
    reference {
      BackGroundColor white
    }
}
</style>

actor User
boundary MobileUI
participant "<<cordinator>>\n ApiGateway" as ApiGateway
participant "<<service>>\n RecipeService" as RecipeService
database MongoDB

User -> MobileUI++: 1. Enter recipe community \n or search recipe srceen

MobileUI -> ApiGateway++: 2. Get recipe tags

ref over ApiGateway: 3. Verify access token

ApiGateway -> RecipeService++: 4. Forward request

RecipeService -> MongoDB++: 5. Query data
RecipeService <-- MongoDB--: 6. Return response

ApiGateway <-- RecipeService--: 7. Return recipe tags list
MobileUI <-- ApiGateway--: 8. Forward response
User <-- MobileUI--: 9. Display recipe tags list

@enduml
