---
- name: Install .NET SDK 8.0
  ansible.builtin.package:
    name: dotnet-sdk-8.0

- name: Get installed .NET runtimes
  ansible.builtin.command: dotnet --list-runtimes
  register: dotnet_out
  changed_when: false

- name: Print installed .NET runtimes
  ansible.builtin.debug:
    var: dotnet_out.stdout_lines
