@startuml Sequence
title "Delete user search user diagram"
' Style section
<style>
  sequenceDiagram {
    reference {
      BackGroundColor white
    }
}
</style>

actor User
activate User

boundary MobileUI
participant "<<coordinator>>\nApiGateway" as ApiGateway
participant "<<service>>\nTrackingService" as TrackingService
database MongoDB

User -> MobileUI++: 1. Touch on search bar in search user\n screen and touch delete icon

MobileUI -> ApiGateway++: 2. Delete search keyword

ref over ApiGateway: 3. Verify access token

ApiGateway -> TrackingService++: 4. Forward request

TrackingService -> MongoDB++: 5. Query search keyword data
TrackingService <-- MongoDB--: 6. Return response
alt if keyword is not found
  ApiGateway <-- TrackingService: 7A. Return not found error
  MobileUI <-- ApiGateway: 7A.1. Forward response
  User <-- MobileUI: 7A.2. Display error alert
else
  TrackingService -> MongoDB ++: 8. Delete data
  TrackingService <-- MongoDB --: 9. Return response
  ApiGateway <-- TrackingService--: 10. Return success status code
  MobileUI <-- ApiGateway--: 11. Forward response
  User <-- MobileUI--: 12. Re-render the search keyword
  deactivate User
end

@enduml
