@startuml GuestUsecase
skinparam style strictuml
skinparam monochrome true
skinparam linetype polyline
skinparam defaultFontSize 12
left to right direction
actor "Guest" as guest
actor "Gmail   " as gmail
actor "SpeedSMS   "as SpeedSMS

rectangle Ingredient-based<U+0020>food<U+0020>recommendation<U+0020>application {
    usecase "UC-M-01: View welcome screen" as ucViewWelcome
    usecase "UC-M-03: Register" as ucRegister
    usecase "UC-M-06: Browse recipes" as ucBrowseRecipes
    usecase "UC-M-07: View other users profiles" as ucViewUSProfile
    usecase "UC-M-10: Change settings" as ucManageSetting
    usecase "UC-M-19: View menu" as ucViewMenu
}

guest -- ucViewWelcome
    ucViewWelcome <.. ucRegister : <<extend>>
    ucViewWelcome <.. ucBrowseRecipes : <<extend>>
        ucBrowseRecipes <.. ucViewUSProfile : <<extend>>
guest -- ucViewMenu
    ucViewMenu <.. ucManageSetting : <<extend>>
    
SpeedSMS -up--> ucRegister
gmail -down-> ucRegister
@enduml
