@startuml GuestUsecase
skinparam style strictuml
skinparam monochrome true
skinparam linetype polyline
skinparam defaultFontSize 12
left to right direction
actor "Guest" as guest
actor "Gmail   " as gmail
actor "SpeedSMS   "as SpeedSMS

rectangle Ingredient-based<U+0020>food<U+0020>recommendation<U+0020>application {
    usecase "UC-1: View welcome screen" as ucViewWelcome
    usecase "UC-4: Register" as ucRegister
    usecase "UC-8: Browse recipes" as ucBrowseRecipes
    usecase "UC-9: View other users profiles (Guest)" as ucViewUSProfile
    usecase "UC-13: Change settings (Mobile)" as ucManageSetting
    usecase "UC-24: View menu" as ucViewMenu
}

guest -- ucViewWelcome
    ucViewWelcome <.. ucRegister : <<extend>>
    ucViewWelcome <.. ucBrowseRecipes : <<extend>>
        ucBrowseRecipes <.. ucViewUSProfile : <<extend>>
guest -- ucViewMenu
    ucViewMenu <.. ucManageSetting : <<extend>>
    
SpeedSMS -up--> ucRegister
gmail -down-> ucRegister
@enduml
