@startuml GuestUsecase
skinparam style strictuml
skinparam monochrome true
skinparam linetype polyline
skinparam defaultFontSize 12
left to right direction
actor "Guest" as guest
actor "Gmail   " as gmail
actor "SpeedSMS   "as SpeedSMS

rectangle Ingredient-based<U+0020>food<U+0020>recommendation<U+0020>application {
    usecase "UC-1: View welcome screen" as ucViewWelcome
    usecase "UC-2: Login (Mobile)" as ucLogin
    usecase "UC-4: Register" as ucRegister
    usecase "UC-5: Forgot password (Mobile)" as ucForgotPassword
    usecase "UC-8: Browse recipes" as ucBrowseRecipes
    usecase "UC-9: View other users profiles (Guest)" as ucViewUSProfile
}

guest --> ucViewWelcome
    ucViewWelcome --> ucLogin
        ucLogin <.. ucForgotPassword : <<extend>>
    ucViewWelcome --> ucRegister
    ucViewWelcome --> ucBrowseRecipes
        ucBrowseRecipes <.. ucViewUSProfile : <<extend>>

gmail -up-> ucLogin
SpeedSMS -up-> ucForgotPassword
gmail -up-> ucForgotPassword
SpeedSMS -up-> ucRegister
gmail -up-> ucRegister
@enduml
