@startuml AccountDbContext

together {
    interface IApplicationDbContext {
        +UserLogins : DbSet<IdentityUserLogin<string>>
        +Permissions : DbSet<Permission>
        +Groups : DbSet<Group>
        +RoleGroupPermissions : DbSet<RoleGroupPermission>
    }

    interface IDbContext {
        +Instance : DbContext
    }
    ' ========= Entity class =========
    class ApplicationAccount extends IdentityUser {
        +EmailOTP: string
        +EmailOTPCreated: DateTime
        +EmailOTPExpiry: DateTime
        +PhoneOTP: string
        +PhoneOTPCreated: DateTime
        +PhoneOTPExpiry: DateTime
        +ForgotPasswordOTP: string
        +ForgotPasswordCreated: Datetime
        +ForgotPasswordExpiry: Datetime
        +IsFirstTimeLogin: bool
        +IsActive: bool
        +CreatedAt: DateTime
        +UpdatedAt: DateTime
    }
    ' ========= Library class =========
    interface IDisposable #black;line:white;text:white
    class "DbSet<T>" #black;line:white;text:white
    class "IdentityUserLogin<T>" #black;line:white;text:white
    class DbContext #black;line:white;text:white
    class IdentityUser #black;line:white;text:white
    class "IdentityDbContext<ApplicationAccount>" #black;line:white;text:white

    class ApplicationDbContext extends "IdentityDbContext<ApplicationAccount>" implements IApplicationDbContext {
        +Permissions : DbSet<Permission>
        +Groups : DbSet<Group>
        +RoleGroupPermissions : DbSet<RoleGroupPermission>
        +Instance : DbContext
        #OnConfiguring(optionsBuilder : DbContextOptionsBuilder) : void
        #OnModelCreating(modelBuilder : ModelBuilder) : void
    }
}

IDbContext ..|> IDisposable
IDbContext o-- DbContext

IApplicationDbContext ..|> IDbContext
IApplicationDbContext o-- "DbSet<T>"
IApplicationDbContext o-- "IdentityUserLogin<T>"
IApplicationDbContext o-- ApplicationAccount

ApplicationDbContext o-- ApplicationAccount

@enduml