@startuml Sequence

title "Verify access token sequence diagram"

' Style section
<style>
  sequenceDiagram {
    reference {
      BackGroundColor white
    }
}
</style>

' Write flow here
participant "<<cordinator>>\nApiGateway" as ApiGateway
participant "<<service>>\nIdentity service" as IdentityService

ApiGateway -> IdentityService: 1. Request to validate token
activate ApiGateway
activate IdentityService

alt if the token is invalid
    ApiGateway <-- IdentityService: 2A. Validate token failed
    ref over ApiGateway: 2A.1. Login
else if the token is valid
    ApiGateway <-- IdentityService: 3. Validate success
end
@enduml
