
@startuml ClassDiagram
!include doc/SDS/CommonClassDiagram/ResultAndError.plantuml
!include doc/SDS/CommonClassDiagram/User/UserDbContext.plantuml 

skinparam classAttributeIconSize 0
skinparam linetype polyline
skinparam nodesep 20
skinparam ranksep 20
hide circle

class BaseApiController {
    #_sender: ISender
    #_httpContextAccessor: HttpContextAccessor
}

class AdminController {
    +GetAdmins(paginatedDTO : PaginatedDTO): async Task<IActionResult>
}

class GetAdminsQuery {
    +DTO : PaginatedDTO
}

class GetAdminsQueryHandler {
    -_context : IApplicationDbContext
    -_grpcAccountClient: GrpcAccountClient 
    -_paginateDataUtility: IPaginateDataUtility<AdminResponse, NumberedPaginatedMetadata> 
    +GetAdminsQueryHandler(context : IApplicationDbContext, grpcAccountClient : GrpcAccountClient, paginateDataUtility : IPaginateDataUtility<AdminResponse, NumberedPaginatedMetadata>)
    +Handle(request: GetAdminsQuery, cancellationToken: CancellationToken) : Task<Result<PaginatedAdminListResponse?>>
}

class PaginatedAdminListResponse

class "BasePaginatedResponse<Type,MetadataType>" {
    +PaginatedData: IEnumerable<Type>
    +Metadata: MetadataType
}

PaginatedAdminListResponse --|> "BasePaginatedResponse<Type,MetadataType>"

class CommonPaginatedMetadata {
    +TotalPage: int
}

class NumberedPaginatedMetadata extends CommonPaginatedMetadata {
    +CurrentPage: int
    +TotalRow: int
}

class PaginatedDTO {
    +Skip : int
    +SortOrder : SortType
    +SortBy : string
    +Keyword : string
    +Limit : int
}

class AdminResponse{
    +AccountId : Guid
    +UserName : string
    +DisplayName : string
    +Email : string
    +PhoneNumber : string
    +Dob : DateTime
    +IsActive : bool
    +Address : string
    +CreatedAt : DateTime
    +UpdatedAt : DateTime
}

class UserError {
    {static} +NotFound: Error
    {static} +NullParameters: Error
}

' =========== Library class ===========
interface "IRequest<TResponse>" #black;line:white;text:white
interface "IRequestHandler<TRequest, TResponse>" #black;line:white;text:white
' =========== Library class ===========

' =========== Microservice class ===========
together {
    class GrpcSearchAccountRequest #DarkViolet;line:white;text:white
    class GrpcAccountIdListRequest #DarkViolet;line:white;text:white
    class GrpcAccountClient #DarkViolet;line:white;text:white
}
AdminController --|> BaseApiController
AdminController "1"--"1" PaginatedDTO
AdminController "1"--"1" GetAdminsQuery

GetAdminsQuery ..|> "IRequest<TResponse>"

GetAdminsQueryHandler ..|> "IRequestHandler<TRequest, TResponse>"
GetAdminsQueryHandler "1" --"1" GetAdminsQuery
GetAdminsQueryHandler "1" o--"1" IApplicationDbContext
GetAdminsQueryHandler "1" o--"1" IPaginateDataUtility
GetAdminsQueryHandler "1" o--"1" GrpcAccountClient
GetAdminsQueryHandler "1" --"1" Result
GetAdminsQueryHandler "1" --"1..*" GrpcSearchAccountRequest
GetAdminsQueryHandler "1" --"1..*" GrpcAccountIdListRequest
GetAdminsQueryHandler "1" --"1..*" PaginatedAdminGetUserListResponse
GetAdminsQueryHandler "1" --"1..*" NumberedPaginatedMetadata
GetAdminsQueryHandler "1" --"1..*" AdminResponse
GetAdminsQueryHandler "1" --"1..*" UserError

Error "1..*" --o "1" UserError

@enduml