@startuml GrpcUserSerciveClassDiagram
!include doc/SDS/CommonClassDiagram/ResultAndError.plantuml
!include doc/SDS/CommonClassDiagram/User/UserDbContext.plantuml
!include doc/SDS/CommonClassDiagram/UnitOfWork.plantuml

skinparam classAttributeIconSize 0
skinparam linetype polyline
skinparam nodesep 50
skinparam ranksep 50
skinparam classAttributeIconSize 0

hide circle

class GrpcUserService #DarkBlue;line:white;text:white extends GrpcUserBase{
    #_sender: ISender
    +GetSimpleUser(request: GrpcGetSimpleUsersRequest, context: ServerCallContext): async Task<GrpcGetSimpleUsersDTO>
    +GetUserDetail(request: GrpcAccountIdRequest, context: ServerCallContext): async Task<GrpcUserDetailDTO>
    +CreateUser(request: GrpcCreateUserRequest, context: ServerCallContext): async Task<GrpcEmpty>
    +SearchUser(request: GrpcSearchUserRequest, context: ServerCallContext): async Task<GrpcListAccountIds>
    +GetUserSetting(request: GrpcAccountIdRequest, context: ServerCallContext): async Task<GrpcUserSetting>
}

class GetSimpleUsersQuery {
    +AccountId: Guid
}

class GetUserDetailsQuery {
    +AccountId: Guid
}

class CreateUserCommand {
    +User: User
}

class SearchSimpleUserQuery{
    +Keyword: string
}

class GetMultipleUserSettingQuery {
    +AccountIdSet: HashSet<Guid>
}

class GetSimpleUsersQueryHandler {
    -_context: IApplicationDbContext
    +GetSimpleUsersQueryHandler(context: IApplicationDbContext)
    +Handle(request: GetSimpleUsersQuery, cancellationToken: CancellationToken): async Task<Result<<List<User>>> 
}

class GetUserDetailsQueryHandler {
    -_context: IApplicationDbContext
    -_grpcAccountClient: GrpcAccountClient
    +GetUserDetailsQueryHandler(context: IApplicationDbContext, grpcAccountClient: GrpcAccountClient)
    +Handle(request: GetUserDetailsQuery, cancellationToken: CancellationToken): async Task<Result<GetUserDetailsResponse>> 
}

class CreateUserCommandHandler {
    -_context: IApplicationDbContext
    -_unitOfWork: IUnitOfWork
    +CreateUserCommandHandler(context: IApplicationDbContext, unitOfWork: IUnitOfWork)
    +Handle(request: CreateUserCommand, cancellationToken: CancellationToken): async Task<Result<User>> 
}

class SearchSimpleUserQueryHandler {
    -_context: IApplicationDbContext
    +SearchSimpleUserQueryHandler(context: IApplicationDbContext)
    +Handle(request: SearchSimpleUserQuery, cancellationToken: CancellationToken): async Task<Result<<List<Guid>>> 
}

class GetMultipleUserSettingQueryHandler {
    -_context: IApplicationDbContext
    +GetMultipleUserSettingQueryHandler(context: IApplicationDbContext)
    +Handle(request: GetMultipleUserSettingQuery, cancellationToken: CancellationToken): async Task<Result<Dictionary<Guid, List<UserSetting>>>>
}
' Grpc DTO
class GrpcEmpty #DarkBlue;line:white;text:white{
}

class GrpcGetSimpleUsersRequest #DarkBlue;line:white;text:white{
}

class GrpcAccountIdRequest #DarkBlue;line:white;text:white{
}

class GrpcSearchUserRequest #DarkBlue;line:white;text:white{
}

class GrpcCreateUserRequest #DarkBlue;line:white;text:white{
}

class GrpcGetUserSettingRequest #DarkBlue;line:white;text:white{ 
}

class GrpcListAccountIds #DarkBlue;line:white;text:white{
}

class GrpcSimpleUser #DarkBlue;line:white;text:white{
} 

class GrpcUserDetailDTO #DarkBlue;line:white;text:white{
}

class GrpcGetSimpleUsersDTO #DarkBlue;line:white;text:white{
}

class GrpcUserSetting #DarkBlue;line:white;text:white{
}
' DTO
class GetUserDetailsResponse{
    +AccountId: Guid
    +DisplayName: string
    +AvatarUrl: string
    +BackgroundUrl: string
    +Dob: DateTime
    +Gender: string
    +Bio: string
    +Address: string
    +TotalFollowers: int
    +TotalFollowing: int
    +TotalRecipes: int
    +IsAccountAcitive: bool
    +AccountUserName: string
    +IsAdmin: bool
    +AccountEmail: string
    +AccountPhoneNumber: string
}

class UserError {
    {static} +NotFound: Error
    {static} +AlreadyExistUser: Error
    {static} +NullParameters: Error
    {static} +AddUserFail: Error
    {static} +UpdateUserFail: Error
    {static} +DeleteUserFail: Error
}

class SettingError {
    {static} +NotFound: Error
    {static} +InvalidSettingKey: Error
    {static} +InvalidSettingValue: Error
}

together {
    class GrpcUserBase #Black;line:white;text:white
    class GrpcAccountIdRequest #DarkViolet;line:white;text:white
    class GrpcAccountClient #DarkViolet;line:white;text:white
}

GrpcUserService -[hidden]down-|> GetSimpleUsersQuery
GrpcUserService -[hidden]down-|> GetUserDetailsQuery
GrpcUserService -[hidden]down-|> CreateUserCommand
GrpcUserService -[hidden]down-|> SearchSimpleUserQuery
GrpcUserService -[hidden]down-|> GetMultipleUserSettingQuery


GetSimpleUsersQuery -[hidden]down-|> GetSimpleUsersQueryHandler
GetUserDetailsQuery -[hidden]down-|> GetUserDetailsQueryHandler
CreateUserCommand -[hidden]down-|> CreateUserCommandHandler
SearchSimpleUserQuery -[hidden]down-|> SearchSimpleUserQueryHandler
GetMultipleUserSettingQuery -[hidden]down-|> GetMultipleUserSettingQueryHandler


GrpcUserService "1"--"1" GrpcGetSimpleUsersDTO
GrpcUserService "1"--"1" GrpcGetSimpleUsersRequest
GrpcUserService "1"--"1" GetSimpleUsersQuery
GrpcUserService "1"--"1" GrpcSimpleUser
GrpcUserService "1"--"1" GrpcGetSimpleUsersDTO

GrpcUserService "1"--"1" GrpcUserDetailDTO
GrpcUserService "1"--"1" GetUserDetailsQuery
GrpcUserService "1"--"1" GetUserDetailsResponse
GrpcUserService "1"--"1" GrpcUserDetailDTO

GrpcUserService "1"--"1" GrpcEmpty
GrpcUserService "1"--"1" GrpcCreateUserRequest
GrpcUserService "1"--"1" User
GrpcUserService "1"--"1" CreateUserCommand

GrpcUserService "1"--"1" GrpcListAccountIds
GrpcUserService "1"--"1" GrpcSearchUserRequest
GrpcUserService "1"--"1" SearchSimpleUserQuery

GrpcUserService "1"--"1" GrpcUserSetting
GrpcUserService "1"--"1" GrpcGetUserSettingRequest
GrpcUserService "1"--"1" GetMultipleUserSettingQuery

GetSimpleUsersQueryHandler "1"--"1" GetSimpleUsersQuery
GetSimpleUsersQueryHandler "1"--"1" User
GetSimpleUsersQueryHandler "1"----"1" Result
GetSimpleUsersQueryHandler "1" o-- "1" IApplicationDbContext
GetSimpleUsersQueryHandler "1"--"1" UserError

GetUserDetailsQueryHandler "1"--"1" GetUserDetailsQuery
GetUserDetailsQueryHandler "1"--"1" GetUserDetailsResponse
GetUserDetailsQueryHandler "1"----"1" Result
GetUserDetailsQueryHandler "1"--"1" GrpcAccountIdRequest
GetUserDetailsQueryHandler "1" o-- "1" IApplicationDbContext
GetUserDetailsQueryHandler "1" o-- "1" GrpcAccountClient
GetUserDetailsQueryHandler "1"--"1" UserError

CreateUserCommandHandler "1"--"1" CreateUserCommand
CreateUserCommandHandler "1"--"1" User
CreateUserCommandHandler "1"----"1" Result
CreateUserCommandHandler "1" o-- "1" IApplicationDbContext
CreateUserCommandHandler "1" o-- "1" IUnitOfWork
CreateUserCommandHandler "1"--"1" UserError

SearchSimpleUserQueryHandler "1"--"1" SearchSimpleUserQuery
SearchSimpleUserQueryHandler "1"----"1" Result
SearchSimpleUserQueryHandler "1" o-- "1" IApplicationDbContext
SearchSimpleUserQueryHandler "1"--"1" UserError

GetMultipleUserSettingQueryHandler "1"--"1" GetMultipleUserSettingQuery
GetMultipleUserSettingQueryHandler "1"--"1" UserSetting
GetMultipleUserSettingQueryHandler "1"----"1" Result
GetMultipleUserSettingQueryHandler "1" o-- "1" IApplicationDbContext
GetMultipleUserSettingQueryHandler "1"--"1" SettingError

Error "1..*" --o "1" UserError
Error "1..*" --o "1" SettingError
@enduml