---
- name: Check argocd
  ansible.builtin.command: which argocd
  register: argocd_check
  changed_when: false
  failed_when: false

- name: Load OS-specific tasks
  ansible.builtin.include_tasks: "{{ ansible_os_family | lower }}.yml"
  when: argocd_check.rc != 0
