@startuml Sequence
title "Resend Email OTP Sequence diagram"

<style>
  sequenceDiagram {
    reference {
      BackGroundColor white
    }
}
</style>

actor User
boundary MobileUI
participant "<<coordinator>>\nApiGateWay" as ApiGateway
participant "<<service>>\nIdentityService" as IdentityService
participant "<<coordinator>>\nRabbitmq"  as Rabbitmq
participant "<<service>>\nNotificationService" as NotificationService
participant "<<service>>\nEmailWorker" as EmailWorker
participant "<<service>>\nGmail" as Gmail

database Postgresql
User -> MobileUI++: 1. Touch resend OTP button
MobileUI -> ApiGateway++: 2. Request resend

activate IdentityService
ref over ApiGateway, IdentityService: 3. Verify Access Token
ApiGateway -[hidden]-> IdentityService
deactivate IdentityService

ApiGateway -> IdentityService++: 4. Forward request
IdentityService -> Postgresql++: 5. Query and insert data
IdentityService <-- Postgresql--: 6. return response

alt if user's email is null
    ApiGateway <-- IdentityService: 7A.1. return resend OTP fail
    MobileUI <-- ApiGateway: 7A.2. Forward response
    User <-- MobileUI: 7A.3. Display error
else
    IdentityService -> Rabbitmq: 8. Publish "UserResendOTPEvent"\n message <<Async>>
    activate Rabbitmq
    Rabbitmq --> NotificationService: 9. Deliver "UserResendOTPEvent"\n message
    deactivate Rabbitmq
    activate NotificationService
    NotificationService -> Rabbitmq: 10. Consume event and publish \n "SendEmailEvent" message <<Async>>
    deactivate NotificationService
    activate Rabbitmq
    Rabbitmq --> EmailWorker: 11. Deliver "SendEmailEvent"\n message
    deactivate Rabbitmq
    activate EmailWorker
    EmailWorker -> Gmail: 12. Send OTP email\n to specified email
    deactivate EmailWorker
    activate Gmail
  
    ApiGateway <-- IdentityService--: 13. return success status code
    deactivate Gmail
    destroy Gmail
    MobileUI <-- ApiGateway--: 14. Forward response
    User <-- MobileUI--: 15. Display alert\n resend OTP successfully
end

@enduml
