@startuml GetTagsClassDiagram
!include doc/SDS/CommonClassDiagram/PaginateData.plantuml
!include doc/SDS/CommonClassDiagram/ResultAndError.plantuml
!include doc/SDS/CommonClassDiagram/Recipe/RecipeDbContext.plantuml
skinparam classAttributeIconSize 0
skinparam linetype polyline
skinparam nodesep 50
skinparam ranksep 50
skinparam classAttributeIconSize 0
hide circle

class BaseApiController {
    #_sender: ISender
    #_httpContextAccessor: HttpContextAccessor
}

class RecipeController {
    +GetTag(getTagsDTO : GetTagsDTO): async Task<IActionResult>
}

class GetTagsQuery {
    +Skip: int
    +Keyword: string
    +TagCodes: List<string>
    +Category: string
}

class GetTagsQueryHandler {
    -_context: IApplicationDbContext
    -_paginateDataUtility: IPaginateDataUtility
    +GetTagsQueryHandler(context : IApplicationDbContext, paginateDataUtility : IPaginateDataUtility)
    +Handle(request : GetTagsQuery, cancellationToken : CancellationToken): async Task<Result<PaginatedTagListResponse>> 
}

class PaginatedTagListResponse 
class BasePaginatedResponse{
    +PaginatedData : IEnumerable<Type>
    +Metadata: MetadataType
}
PaginatedTagListResponse --|> BasePaginatedResponse

class TagResponse {
    +Id: Guid
    +Code: string
    +En: string
    +Vi: string
    +Category: string
    +Status: string
    +ImageUrl: string
    +CreatedAt: DateTime
}

class CommonPaginatedMetadata {
    +TotalPage: int
}

class AdvancePaginatedMetadata extends CommonPaginatedMetadata {
    +HasNextPage: bool
}

class GetTagsDTO{
    +Skip: int
    +Keyword: string
    +TagCodes: List<string>
    +Category: string
}

class TagError {
    {static} +NotFound: Error
    {static} +AddTagFail: Error
    {static} +DeleteTagFail: Error
    {static} +UpdateTagFail: Error
}

' =========== Library class ===========
interface "IRequest<TResponse>" #black;line:white;text:white
interface "IRequestHandler<TRequest, TResponse>" #black;line:white;text:white
' =========== Library class ===========

PaginatedTagListResponse "1" o-- "1..*" TagResponse
PaginatedTagListResponse "1" o-- "1" AdvancePaginatedMetadata

RecipeController --|> BaseApiController
RecipeController "1"--"1" GetTagsDTO
RecipeController "1"--"1" GetTagsQuery

GetTagsQuery ..|> "IRequest<TResponse>"

GetTagsQueryHandler ..|> "IRequestHandler<TRequest, TResponse>"
GetTagsQueryHandler "1"--"1" GetTagsQuery
GetTagsQueryHandler "1"--"1" Result
GetTagsQueryHandler "1"--"1" PaginatedTagListResponse
GetTagsQueryHandler "1" o-- "1" IApplicationDbContext
GetTagsQueryHandler "1" o-- "1" IPaginateDataUtility
GetTagsQueryHandler "1"--"1..*" TagError

Error "1..*" --o "1" TagError
@enduml