@startuml ClassDiagram
!include doc/SDS/CommonClassDiagram/ResultAndError.plantuml
!include doc/SDS/CommonClassDiagram/UnitOfWork.plantuml
!include doc/SDS/CommonClassDiagram/Tracking/TrackingDbContext.plantuml
skinparam classAttributeIconSize 0
skinparam linetype polyline
skinparam nodesep 100
skinparam ranksep 100
skinparam classAttributeIconSize 0

hide circle

class CreateUserSearchUserConsumer #CadetBlue;line:white;text:white {
    #_sender: ISender
    +CreateUserSearchUserConsumer(sender: ISender)
    +Consume(context: ConsumeContext<CreateUserSearchUserEvent>): async Task
}

class CreateUserSearchUserCommand implements "IRequest<TResponse>" {
    +AccountId: Guid
    +Keyword: string
    +SearchTime: DateTime
}

class CreateUserSearchUserCommandHandler {
    -_context: IApplicationDbContext
    -_unitOfWork: IUnitOfWork
    +Handle(request: CreateUserSearchUserCommand, cancellationToken: CancellationToken): async Task<Result>
}

' Event DTO
class CreateUserSearchUserEvent #CadetBlue;line:white;text:white {
    +AccountId: Guid
    +Keyword: string
    +SearchTime: DateTime
}

class UserSearchUserError {
    {static} +AddUserViewRecipeDetailFail: Error
}

' =========== Library class ===========
interface "IRequest<TResponse>" #black;line:white;text:white
interface "IRequestHandler<TRequest, TResponse>" #black;line:white;text:white
' =========== Library class ===========

CreateUserSearchUserCommandHandler ..|> "IRequestHandler<TRequest, TResponse>"

CreateUserSearchUserConsumer "1" -- "1" CreateUserSearchUserEvent
CreateUserSearchUserConsumer "1" -- "1" CreateUserSearchUserCommand

CreateUserSearchUserCommandHandler "1" -- "1" CreateUserSearchUserCommand
CreateUserSearchUserCommandHandler "1" o-- "1" IApplicationDbContext
CreateUserSearchUserCommandHandler "1" o-- "1" IUnitOfWork

CreateUserSearchUserCommandHandler "1" -- "1..*" Result
CreateUserSearchUserCommandHandler "1" -- "1..*" UserSearchUserError
CreateUserSearchUserCommandHandler "1" -- "1..*" UserSearchUser

UserSearchUserError "1" o-- "1..*" Error

' =================STYLE=================
CreateUserSearchUserConsumer -[hidden]down-|> CreateUserSearchUserCommand

CreateUserSearchUserCommand -[hidden]down-|> CreateUserSearchUserCommandHandler

@enduml