apiVersion: v1
kind: Service
metadata:
  name: identity-api
spec:
  selector:
    app: identity-api
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  - port: 443
    targetPort: 443
    protocol: TCP
