apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./ingresses/api-gateway.yaml
  - ./ingresses/identity-api.yaml
  - ./ingresses/consul.yaml
  - ./ingresses/rabbitmq.yaml
  - ./ingresses/website.yaml
