@startuml Sequence
title "Verify update identifier diagram"

<style>
  sequenceDiagram {
    reference {
      BackGroundColor white
    }
}
</style>

actor User
boundary MobileUI
participant "<<coordinator>>\nApiGateWay" as ApiGateway
participant "<<service>>\nIdentityService" as IdentityService
database Postgresql

User -> MobileUI ++: 1. User click the button verify\n in verify update identifier screen
MobileUI -> ApiGateway ++: 2. Request verify update identifier

activate IdentityService
ref over ApiGateway, IdentityService: 3. Verify Access Token
ApiGateway -[hidden]-> IdentityService
deactivate IdentityService

ApiGateway -> IdentityService ++: 4. Forward request
IdentityService -> Postgresql ++: 5. Get account data
IdentityService <-- Postgresql --: 6. Return response

alt if account is null
  ApiGateway <-- IdentityService: 7A. Return not found error
  MobileUI <-- ApiGateway: 7A.1. Forward response
  User <-- MobileUI: 7A.2. Display error alert
else
  alt if user's OTP is invalid
    ApiGateway <-- IdentityService: 8A. Return invalid otp error
    MobileUI <-- ApiGateway: 8A.1. Forward response
    User <-- MobileUI: 8A.2. Display error alert
  else
    alt if user's OTP is expired
      ApiGateway <-- IdentityService: 9A. Return otp expired error
      MobileUI <-- ApiGateway: 9A.1. Forward response
      User <-- MobileUI: 9A.2. Display error
    else
      IdentityService -> Postgresql ++: 10. Update account identifier
      IdentityService <-- Postgresql --: 11. Return response
      ApiGateway <-- IdentityService --: 12. Return success status code
      MobileUI <-- ApiGateway --: 13. Forward response
      User <-- MobileUI --: 14. Display alert\n update identifier successfully
    end
  end
end


@enduml
