export enum NotificationTemplateCode {
	USER_COMMENT = "USER_COMMENT",
	USER_CREATE_RECIPE = "USER_CREATE_RECIPE",
	USER_FOLLOW = "USER_FOLLOW",
  USER_REPLY = "USER_REPLY",
  USER_UPVOTE = "USER_UPVOTE",
  USER_DOWNVOTE = "USER_DOWNVOTE",
	SYSTEM_DISABLE_RECIPE = "SYSTEM_DISABLE_RECIPE",
	ADMIN_DISABLE_RECIPE = "ADMIN_DISABLE_RECIPE",
	ADMIN_RESTORE_RECIPE = "ADMIN_RESTORE_RECIPE",
	ADMIN_DISABLE_COMMENT = "ADMIN_DISABLE_COMMENT",
	ADMIN_RESTORE_COMMENT = "ADMIN_RESTORE_COMMENT"
}
