export enum SETTING_KEY {
  LANGUAGE = "LANGUAGE",
  DARK_MODE = "DARK_MODE",
  NOTIFICATION_COMMENT = "NOTIFICATION_COMMENT",
  NOTIFICATION_VOTE = "NOTIFICATION_VOTE",
  NOTIFICATION_FOLLOW = "NOTIFICATION_FOLLOW"
}

export enum REPORT_TYPE {
  RECIPE = "Recipe",
  COMMENT = "Comment",
  USER = "User"
}

export namespace SETTING_VALUE {
  export enum LANGUAGE {
    VIETNAMESE = "VIETNAMESE",
    ENGLISH = "ENGLISH"
  }

  export enum BOOLEAN {
    TRUE = "TRUE",
    FALSE = "FALSE"
  }
}
