FROM mcr.microsoft.com/dotnet/aspnet:8.0-alpine AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:8.0-alpine AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src

COPY ["./app/server/Contract/Contract/Published", "Contract/"]
COPY ["./app/server/RecipeService/src/RecipeService.API/RecipeService.API.csproj", "RecipeService.API/"]
COPY ["./app/server/RecipeService/src/RecipeService.Application/RecipeService.Application.csproj", "RecipeService.Application/"]
COPY ["./app/server/RecipeService/src/RecipeService.Infrastructure/RecipeService.Infrastructure.csproj", "RecipeService.Infrastructure/"]
COPY ["./app/server/RecipeService/src/RecipeService.Domain/RecipeService.Domain.csproj", "RecipeService.Domain/"]

# Building the services
WORKDIR "/src/RecipeService.API"
RUN --mount=type=cache,target=/root/.cache/.nuget \
    dotnet restore --verbosity normal
COPY ["./app/server/RecipeService/src","/src"]
RUN --mount=type=cache,target=/root/.cache/.nuget \
    dotnet build -c $BUILD_CONFIGURATION -o /app/build

FROM build AS publish
# Have to add work dir, because dotnet publish will scan entire fs, make the docker hang with NAT network
WORKDIR "/src/RecipeService.API"
ARG BUILD_CONFIGURATION=Release
RUN --mount=type=cache,target=/root/.cache/.nuget \
    dotnet publish -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
COPY seeds seeds

RUN chown -R app:app /app
USER app

ENTRYPOINT ["dotnet", "RecipeService.API.dll"]