#See https://aka.ms/customizecontainer to learn how to customize your debug container and how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
USER app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
# Copy pre-build lib
COPY ["./data/nuget", "./nuget"]

COPY ["./app/server/RecipeService/src/RecipeService.API/RecipeService.API.csproj", "RecipeService.API/"]
COPY ["./app/server/RecipeService/src/RecipeService.Application/RecipeService.Application.csproj", "RecipeService.Application/"]
COPY ["./app/server/RecipeService/src/RecipeService.Infrastructure/RecipeService.Infrastructure.csproj", "RecipeService.Infrastructure/"]
COPY ["./app/server/RecipeService/src/RecipeService.Domain/RecipeService.Domain.csproj", "RecipeService.Domain/"]
COPY ["./app/server/Contract/Contract/Published", "Contract/"]

# Building the services
WORKDIR "/src/RecipeService.API"
RUN dotnet restore --packages "../nuget" --verbosity normal
COPY ["./app/server/RecipeService/src","/src"]

ENTRYPOINT ["dotnet", "watch", "run", "--no-restore"]
