// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RecipeService.Infrastructure.Persistence;

#nullable disable

namespace RecipeService.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241226082812_ChangeAttachedFilesToStringArray")]
    partial class ChangeAttachedFilesToStringArray
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RecipeService.Domain.Entities.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.ToTable("Comment");
                });

            modelBuilder.Entity("RecipeService.Domain.Entities.CommentVote", b =>
                {
                    b.Property<Guid>("CommentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsUpvote")
                        .HasColumnType("boolean");

                    b.HasKey("CommentId", "UserId");

                    b.ToTable("CommentVote");
                });

            modelBuilder.Entity("RecipeService.Domain.Entities.Recipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid");

                    b.Property<string>("CookTime")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<List<string>>("Ingredients")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("NumberOfComment")
                        .HasColumnType("integer");

                    b.Property<int?>("Serves")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("TotalView")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("VoteDiff")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Recipe");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aa626791-ee53-4390-a5a5-94c5b8096f87"),
                            AuthorId = new Guid("61c61ac7-291e-4075-9689-666ef05547ed"),
                            CookTime = "10m",
                            CreatedAt = new DateTime(2024, 7, 28, 22, 11, 18, 0, DateTimeKind.Utc),
                            Description = "A quick and easy recipe for creamy scrambled eggs, perfect for breakfast.",
                            ImageUrl = "https://i.imgur.com/rxAzMjR.jpg",
                            Ingredients = new List<string> { "2 Eggs", "2 tbsp Milk", "1 tbsp Butter", "Salt", "Pepper" },
                            IsActive = true,
                            NumberOfComment = 0,
                            Serves = 2,
                            Title = "Classic Scrambled Eggs",
                            TotalView = 0,
                            UpdatedAt = new DateTime(2024, 7, 28, 22, 11, 18, 0, DateTimeKind.Utc),
                            VoteDiff = 0
                        },
                        new
                        {
                            Id = new Guid("c8362fc3-5cff-4171-a78d-40613c748596"),
                            AuthorId = new Guid("61c61ac7-291e-4075-9689-666ef05547ed"),
                            CookTime = "40m",
                            CreatedAt = new DateTime(2023, 12, 24, 19, 1, 34, 0, DateTimeKind.Utc),
                            Description = "A comforting tomato soup made from fresh tomatoes and spices.",
                            ImageUrl = "https://i.imgur.com/SzhMVWs.jpg",
                            Ingredients = new List<string> { "4 Ripe Tomatoes", "1 Onion", "2 Garlic Cloves", "2 cups Vegetable Stock", "Salt", "Pepper" },
                            IsActive = true,
                            NumberOfComment = 0,
                            Serves = 2,
                            Title = "Tomato Soup",
                            TotalView = 0,
                            UpdatedAt = new DateTime(2023, 12, 24, 19, 1, 34, 0, DateTimeKind.Utc),
                            VoteDiff = 0
                        },
                        new
                        {
                            Id = new Guid("068be5ad-dc4d-4a7b-bce7-24b4ed9fec57"),
                            AuthorId = new Guid("61c61ac7-291e-4075-9689-666ef05547ed"),
                            CookTime = "30m",
                            CreatedAt = new DateTime(2023, 5, 31, 12, 6, 57, 0, DateTimeKind.Utc),
                            Description = "A creamy, cheesy pasta with bacon, eggs, and parmesan.",
                            ImageUrl = "https://i.imgur.com/le7gFC6.jpg",
                            Ingredients = new List<string> { "200g Spaghetti", "100g Bacon", "2 Eggs", "50g Parmesan Cheese", "Salt", "Pepper" },
                            IsActive = true,
                            NumberOfComment = 0,
                            Serves = 2,
                            Title = "Pasta Carbonara",
                            TotalView = 0,
                            UpdatedAt = new DateTime(2023, 5, 31, 12, 6, 57, 0, DateTimeKind.Utc),
                            VoteDiff = 0
                        },
                        new
                        {
                            Id = new Guid("0a1ff224-99eb-442f-b043-0d00bf9fb1c2"),
                            AuthorId = new Guid("61c61ac7-291e-4075-9689-666ef05547ed"),
                            CookTime = "20m",
                            CreatedAt = new DateTime(2023, 2, 18, 23, 28, 9, 0, DateTimeKind.Utc),
                            Description = "A healthy stir-fry with various vegetables and soy sauce.",
                            ImageUrl = "https://i.imgur.com/aXVMMXA.jpg",
                            Ingredients = new List<string> { "1 Bell Pepper", "1 Carrot", "1 Broccoli Head", "2 tbsp Soy Sauce", "1 tbsp Olive Oil", "1 Garlic Clove" },
                            IsActive = true,
                            NumberOfComment = 0,
                            Serves = 2,
                            Title = "Vegetable Stir-Fry",
                            TotalView = 0,
                            UpdatedAt = new DateTime(2023, 2, 18, 23, 28, 9, 0, DateTimeKind.Utc),
                            VoteDiff = 0
                        },
                        new
                        {
                            Id = new Guid("057aa844-742a-4952-8162-dbfbd7e493ac"),
                            AuthorId = new Guid("61c61ac7-291e-4075-9689-666ef05547ed"),
                            CookTime = "15m",
                            CreatedAt = new DateTime(2023, 9, 30, 18, 9, 19, 0, DateTimeKind.Utc),
                            Description = "A simple and delicious garlic bread recipe, perfect as a side dish.",
                            ImageUrl = "https://i.imgur.com/RpT3aRb.jpg",
                            Ingredients = new List<string> { "1 Baguette", "50g Butter", "2 Garlic Cloves", "1 tbsp Parsley", "Salt" },
                            IsActive = true,
                            NumberOfComment = 0,
                            Serves = 2,
                            Title = "Garlic Bread",
                            TotalView = 0,
                            UpdatedAt = new DateTime(2023, 9, 30, 18, 9, 19, 0, DateTimeKind.Utc),
                            VoteDiff = 0
                        });
                });

            modelBuilder.Entity("RecipeService.Domain.Entities.RecipeTag", b =>
                {
                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid");

                    b.HasKey("RecipeId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("RecipeTag");

                    b.HasData(
                        new
                        {
                            RecipeId = new Guid("aa626791-ee53-4390-a5a5-94c5b8096f87"),
                            TagId = new Guid("2bf7f026-e745-4bd9-8701-a9519742d0f7")
                        },
                        new
                        {
                            RecipeId = new Guid("aa626791-ee53-4390-a5a5-94c5b8096f87"),
                            TagId = new Guid("f92b7c2e-d2f0-4b7f-b5d5-9d3a41b718c3")
                        },
                        new
                        {
                            RecipeId = new Guid("aa626791-ee53-4390-a5a5-94c5b8096f87"),
                            TagId = new Guid("6f229db7-e0d7-4fd8-83d6-4f8b9c3ef5c1")
                        },
                        new
                        {
                            RecipeId = new Guid("c8362fc3-5cff-4171-a78d-40613c748596"),
                            TagId = new Guid("df3f6301-3cae-480a-87da-c7b8f6150292")
                        },
                        new
                        {
                            RecipeId = new Guid("c8362fc3-5cff-4171-a78d-40613c748596"),
                            TagId = new Guid("8db97f13-4ff0-4a0e-9c5c-b2c1d4e1b78e")
                        },
                        new
                        {
                            RecipeId = new Guid("068be5ad-dc4d-4a7b-bce7-24b4ed9fec57"),
                            TagId = new Guid("2bf7f026-e745-4bd9-8701-a9519742d0f7")
                        },
                        new
                        {
                            RecipeId = new Guid("068be5ad-dc4d-4a7b-bce7-24b4ed9fec57"),
                            TagId = new Guid("9c5d4e5f-3c44-4bde-a5a6-7a1d3e1b67d6")
                        },
                        new
                        {
                            RecipeId = new Guid("068be5ad-dc4d-4a7b-bce7-24b4ed9fec57"),
                            TagId = new Guid("3e084d1f-4dd1-42dc-9a15-9f8fbb4b8495")
                        },
                        new
                        {
                            RecipeId = new Guid("0a1ff224-99eb-442f-b043-0d00bf9fb1c2"),
                            TagId = new Guid("ad7dca4b-9ae8-44d3-b4c3-7d4c9e9b6f8e")
                        },
                        new
                        {
                            RecipeId = new Guid("0a1ff224-99eb-442f-b043-0d00bf9fb1c2"),
                            TagId = new Guid("63af97d6-9fc0-4c5b-b6b1-d5e5e8b8a0a6")
                        },
                        new
                        {
                            RecipeId = new Guid("0a1ff224-99eb-442f-b043-0d00bf9fb1c2"),
                            TagId = new Guid("4a6fc1f9-7f8d-49de-85b4-b6b9f8d1c4a8")
                        },
                        new
                        {
                            RecipeId = new Guid("057aa844-742a-4952-8162-dbfbd7e493ac"),
                            TagId = new Guid("8db97f13-4ff0-4a0e-9c5c-b2c1d4e1b78e")
                        },
                        new
                        {
                            RecipeId = new Guid("057aa844-742a-4952-8162-dbfbd7e493ac"),
                            TagId = new Guid("6f229db7-e0d7-4fd8-83d6-4f8b9c3ef5c1")
                        });
                });

            modelBuilder.Entity("RecipeService.Domain.Entities.RecipeVote", b =>
                {
                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsUpvote")
                        .HasColumnType("boolean");

                    b.HasKey("RecipeId", "UserId");

                    b.ToTable("RecipeVote");
                });

            modelBuilder.Entity("RecipeService.Domain.Entities.Step", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<List<string>>("AttachedImageUrls")
                        .HasColumnType("text[]");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("OdinalNumber")
                        .HasColumnType("integer");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.ToTable("Step");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a75ef94e-b0a9-41f1-87b6-004f2d052463"),
                            Content = "Crack the eggs into a bowl and whisk with milk, salt, and pepper.",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            OdinalNumber = 1,
                            RecipeId = new Guid("aa626791-ee53-4390-a5a5-94c5b8096f87"),
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("2bd8dfb4-0ad0-41f6-b6f3-848c74138d25"),
                            Content = "Melt butter in a non-stick pan over medium heat.",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            OdinalNumber = 2,
                            RecipeId = new Guid("aa626791-ee53-4390-a5a5-94c5b8096f87"),
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("e15a2a39-e321-48b8-97b2-c9872360daf8"),
                            Content = "Pour the egg mixture into the pan and gently stir until softly set.",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            OdinalNumber = 3,
                            RecipeId = new Guid("aa626791-ee53-4390-a5a5-94c5b8096f87"),
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("ba1c4554-f0f4-4940-808f-bdd38adb5a39"),
                            Content = "Chop the tomatoes, onion, and garlic.",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            OdinalNumber = 1,
                            RecipeId = new Guid("c8362fc3-5cff-4171-a78d-40613c748596"),
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("4d2f7874-73c4-41c0-aac4-214431825d73"),
                            Content = "Sauté onion and garlic in olive oil until soft.",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            OdinalNumber = 2,
                            RecipeId = new Guid("c8362fc3-5cff-4171-a78d-40613c748596"),
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("60c692b6-5cfd-45cc-ae02-9e9dd7fe3ca7"),
                            Content = "Add tomatoes and vegetable stock, then simmer for 30 minutes.",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            OdinalNumber = 3,
                            RecipeId = new Guid("c8362fc3-5cff-4171-a78d-40613c748596"),
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("5f286099-716e-4d82-91e1-d079d44d749e"),
                            Content = "Blend the soup until smooth and season with salt and pepper.",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            OdinalNumber = 4,
                            RecipeId = new Guid("c8362fc3-5cff-4171-a78d-40613c748596"),
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("cb8f9f6d-79de-4012-a5ff-f5e270ca279a"),
                            Content = "Cook spaghetti in salted boiling water until al dente.",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            OdinalNumber = 1,
                            RecipeId = new Guid("068be5ad-dc4d-4a7b-bce7-24b4ed9fec57"),
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("a3f72e82-2025-44a1-9b74-1bc3999dd65b"),
                            Content = "Fry bacon until crispy.",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            OdinalNumber = 2,
                            RecipeId = new Guid("068be5ad-dc4d-4a7b-bce7-24b4ed9fec57"),
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("55559bf3-f134-427e-8552-99bd6710e5b3"),
                            Content = "Mix eggs and grated parmesan in a bowl.",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            OdinalNumber = 3,
                            RecipeId = new Guid("068be5ad-dc4d-4a7b-bce7-24b4ed9fec57"),
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("98a5f870-2f1b-436a-8d40-9a0cd451ecca"),
                            Content = "Toss cooked spaghetti with bacon and remove from heat.",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            OdinalNumber = 4,
                            RecipeId = new Guid("068be5ad-dc4d-4a7b-bce7-24b4ed9fec57"),
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("274f2842-a3e5-4a32-a8a5-5211dcab2912"),
                            Content = "Add the egg mixture and stir until creamy.",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            OdinalNumber = 5,
                            RecipeId = new Guid("068be5ad-dc4d-4a7b-bce7-24b4ed9fec57"),
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("df106c03-8e82-43a2-ae64-561164dc889f"),
                            Content = "Chop all vegetables into bite-sized pieces.",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            OdinalNumber = 1,
                            RecipeId = new Guid("0a1ff224-99eb-442f-b043-0d00bf9fb1c2"),
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("5f1944af-04fc-4124-866f-c1685ef991c0"),
                            Content = "Heat olive oil in a wok or large pan.",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            OdinalNumber = 2,
                            RecipeId = new Guid("0a1ff224-99eb-442f-b043-0d00bf9fb1c2"),
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("2df28722-ac4f-4965-b90c-c098131589f0"),
                            Content = "Add vegetables and stir-fry for 5-7 minutes.",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            OdinalNumber = 3,
                            RecipeId = new Guid("0a1ff224-99eb-442f-b043-0d00bf9fb1c2"),
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("35483d6c-6c63-4603-87a2-e0111327e49b"),
                            Content = "Add soy sauce and stir well.",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            OdinalNumber = 4,
                            RecipeId = new Guid("0a1ff224-99eb-442f-b043-0d00bf9fb1c2"),
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("91e558fa-5c9f-4d51-8342-0e6555e19a35"),
                            Content = "Preheat the oven to 180°C (350°F).",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            OdinalNumber = 1,
                            RecipeId = new Guid("057aa844-742a-4952-8162-dbfbd7e493ac"),
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("c042ed72-eee4-46cf-a58a-3cd4599e3060"),
                            Content = "Mix softened butter with minced garlic and parsley.",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            OdinalNumber = 2,
                            RecipeId = new Guid("057aa844-742a-4952-8162-dbfbd7e493ac"),
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("21bedadf-1a37-4e53-a3b9-0a885ee60601"),
                            Content = "Spread the mixture onto sliced baguette.",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            OdinalNumber = 3,
                            RecipeId = new Guid("057aa844-742a-4952-8162-dbfbd7e493ac"),
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("48e5469b-cbfd-493a-8f97-87ccdeb582a4"),
                            Content = "Bake in the oven for 10-12 minutes until golden.",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            OdinalNumber = 4,
                            RecipeId = new Guid("057aa844-742a-4952-8162-dbfbd7e493ac"),
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("RecipeService.Domain.Entities.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Tag");

                    b.HasData(
                        new
                        {
                            Id = new Guid("df3f6301-3cae-480a-87da-c7b8f6150292"),
                            Category = "INGREDIENT",
                            Code = "TOMATO",
                            CreatedAt = new DateTime(2024, 12, 26, 8, 28, 11, 795, DateTimeKind.Utc).AddTicks(7152),
                            ImageUrl = "https://i.imgur.com/3NovRt2.png",
                            IsActive = true,
                            UpdatedAt = new DateTime(2024, 12, 26, 8, 28, 11, 795, DateTimeKind.Utc).AddTicks(7164),
                            Value = "Tomato"
                        },
                        new
                        {
                            Id = new Guid("2bf7f026-e745-4bd9-8701-a9519742d0f7"),
                            Category = "INGREDIENT",
                            Code = "EGG",
                            CreatedAt = new DateTime(2024, 12, 26, 8, 28, 11, 795, DateTimeKind.Utc).AddTicks(7166),
                            ImageUrl = "https://i.imgur.com/BAT5qyL.png",
                            IsActive = true,
                            UpdatedAt = new DateTime(2024, 12, 26, 8, 28, 11, 795, DateTimeKind.Utc).AddTicks(7166),
                            Value = "Egg"
                        },
                        new
                        {
                            Id = new Guid("92316e11-fd87-4c0f-aac7-bde4f19c2b38"),
                            Category = "INGREDIENT",
                            Code = "RICE",
                            CreatedAt = new DateTime(2024, 12, 26, 8, 28, 11, 795, DateTimeKind.Utc).AddTicks(7169),
                            ImageUrl = "https://i.imgur.com/C4nNmU1.png",
                            IsActive = true,
                            UpdatedAt = new DateTime(2024, 12, 26, 8, 28, 11, 795, DateTimeKind.Utc).AddTicks(7170),
                            Value = "Rice"
                        },
                        new
                        {
                            Id = new Guid("a7a1953d-027e-43b6-ad0d-d10312a3064d"),
                            Category = "INGREDIENT",
                            Code = "MUSHROOM",
                            CreatedAt = new DateTime(2024, 12, 26, 8, 28, 11, 795, DateTimeKind.Utc).AddTicks(7172),
                            ImageUrl = "https://i.imgur.com/m8wBuYO.png",
                            IsActive = true,
                            UpdatedAt = new DateTime(2024, 12, 26, 8, 28, 11, 795, DateTimeKind.Utc).AddTicks(7172),
                            Value = "Mushroom"
                        },
                        new
                        {
                            Id = new Guid("f92b7c2e-d2f0-4b7f-b5d5-9d3a41b718c3"),
                            Category = "INGREDIENT",
                            Code = "MILK",
                            CreatedAt = new DateTime(2024, 12, 26, 8, 28, 11, 795, DateTimeKind.Utc).AddTicks(7174),
                            ImageUrl = "https://i.imgur.com/Rk3MwdQ.jpg",
                            IsActive = true,
                            UpdatedAt = new DateTime(2024, 12, 26, 8, 28, 11, 795, DateTimeKind.Utc).AddTicks(7175),
                            Value = "Milk"
                        },
                        new
                        {
                            Id = new Guid("6f229db7-e0d7-4fd8-83d6-4f8b9c3ef5c1"),
                            Category = "INGREDIENT",
                            Code = "BUTTER",
                            CreatedAt = new DateTime(2024, 12, 26, 8, 28, 11, 795, DateTimeKind.Utc).AddTicks(7177),
                            ImageUrl = "https://i.imgur.com/Z8y4Hsr.jpg",
                            IsActive = true,
                            UpdatedAt = new DateTime(2024, 12, 26, 8, 28, 11, 795, DateTimeKind.Utc).AddTicks(7177),
                            Value = "Butter"
                        },
                        new
                        {
                            Id = new Guid("3e084d1f-4dd1-42dc-9a15-9f8fbb4b8495"),
                            Category = "INGREDIENT",
                            Code = "CHEESE",
                            CreatedAt = new DateTime(2024, 12, 26, 8, 28, 11, 795, DateTimeKind.Utc).AddTicks(7179),
                            ImageUrl = "https://i.imgur.com/feglS7k.jpg",
                            IsActive = true,
                            UpdatedAt = new DateTime(2024, 12, 26, 8, 28, 11, 795, DateTimeKind.Utc).AddTicks(7180),
                            Value = "Cheese"
                        },
                        new
                        {
                            Id = new Guid("9c5d4e5f-3c44-4bde-a5a6-7a1d3e1b67d6"),
                            Category = "INGREDIENT",
                            Code = "BACON",
                            CreatedAt = new DateTime(2024, 12, 26, 8, 28, 11, 795, DateTimeKind.Utc).AddTicks(7182),
                            ImageUrl = "https://i.imgur.com/lyYgVRi.jpg",
                            IsActive = true,
                            UpdatedAt = new DateTime(2024, 12, 26, 8, 28, 11, 795, DateTimeKind.Utc).AddTicks(7182),
                            Value = "Bacon"
                        },
                        new
                        {
                            Id = new Guid("8db97f13-4ff0-4a0e-9c5c-b2c1d4e1b78e"),
                            Category = "INGREDIENT",
                            Code = "GARLIC",
                            CreatedAt = new DateTime(2024, 12, 26, 8, 28, 11, 795, DateTimeKind.Utc).AddTicks(7184),
                            ImageUrl = "https://i.imgur.com/oLwdHvx.jpg",
                            IsActive = true,
                            UpdatedAt = new DateTime(2024, 12, 26, 8, 28, 11, 795, DateTimeKind.Utc).AddTicks(7185),
                            Value = "Garlic"
                        },
                        new
                        {
                            Id = new Guid("ad7dca4b-9ae8-44d3-b4c3-7d4c9e9b6f8e"),
                            Category = "INGREDIENT",
                            Code = "CARROT",
                            CreatedAt = new DateTime(2024, 12, 26, 8, 28, 11, 795, DateTimeKind.Utc).AddTicks(7187),
                            ImageUrl = "https://i.imgur.com/DZEq7TK.jpg",
                            IsActive = true,
                            UpdatedAt = new DateTime(2024, 12, 26, 8, 28, 11, 795, DateTimeKind.Utc).AddTicks(7187),
                            Value = "Carrot"
                        },
                        new
                        {
                            Id = new Guid("63af97d6-9fc0-4c5b-b6b1-d5e5e8b8a0a6"),
                            Category = "INGREDIENT",
                            Code = "BROCCOLI",
                            CreatedAt = new DateTime(2024, 12, 26, 8, 28, 11, 795, DateTimeKind.Utc).AddTicks(7189),
                            ImageUrl = "https://i.imgur.com/8nDcffy.png",
                            IsActive = true,
                            UpdatedAt = new DateTime(2024, 12, 26, 8, 28, 11, 795, DateTimeKind.Utc).AddTicks(7190),
                            Value = "Broccoli"
                        },
                        new
                        {
                            Id = new Guid("4a6fc1f9-7f8d-49de-85b4-b6b9f8d1c4a8"),
                            Category = "INGREDIENT",
                            Code = "SOY_SAUCE",
                            CreatedAt = new DateTime(2024, 12, 26, 8, 28, 11, 795, DateTimeKind.Utc).AddTicks(7192),
                            ImageUrl = "https://i.imgur.com/2QiWJWH.jpg",
                            IsActive = true,
                            UpdatedAt = new DateTime(2024, 12, 26, 8, 28, 11, 795, DateTimeKind.Utc).AddTicks(7192),
                            Value = "Soy Sauce"
                        },
                        new
                        {
                            Id = new Guid("71676633-493e-46c5-86a0-21773f196035"),
                            Category = "DISHTYPE",
                            Code = "ALL",
                            CreatedAt = new DateTime(2024, 12, 26, 8, 28, 11, 795, DateTimeKind.Utc).AddTicks(7194),
                            ImageUrl = "https://res.cloudinary.com/dhphzuojz/image/upload/v1735196328/default_storage/tag/dishtype/hivalxshuvx5nnlfp5t1.png",
                            IsActive = true,
                            UpdatedAt = new DateTime(2024, 12, 26, 8, 28, 11, 795, DateTimeKind.Utc).AddTicks(7195),
                            Value = "All"
                        },
                        new
                        {
                            Id = new Guid("6c91b894-d6dd-4c9b-a106-bfd029ce9e16"),
                            Category = "DISHTYPE",
                            Code = "NOODLES",
                            CreatedAt = new DateTime(2024, 12, 26, 8, 28, 11, 795, DateTimeKind.Utc).AddTicks(7197),
                            ImageUrl = "https://res.cloudinary.com/dhphzuojz/image/upload/v1735196327/default_storage/tag/dishtype/ingre9ficyzq0iitiwmd.png",
                            IsActive = true,
                            UpdatedAt = new DateTime(2024, 12, 26, 8, 28, 11, 795, DateTimeKind.Utc).AddTicks(7197),
                            Value = "Noodles"
                        },
                        new
                        {
                            Id = new Guid("de3698bf-ad8b-4cc6-8ed0-662bd7eca486"),
                            Category = "DISHTYPE",
                            Code = "SPICE",
                            CreatedAt = new DateTime(2024, 12, 26, 8, 28, 11, 795, DateTimeKind.Utc).AddTicks(7199),
                            ImageUrl = "https://res.cloudinary.com/dhphzuojz/image/upload/v1735196323/default_storage/tag/dishtype/frgtox8kb4edsvmutmez.png",
                            IsActive = true,
                            UpdatedAt = new DateTime(2024, 12, 26, 8, 28, 11, 795, DateTimeKind.Utc).AddTicks(7200),
                            Value = "Spice"
                        },
                        new
                        {
                            Id = new Guid("d8b74fc2-f848-41af-a53f-20170aa453cd"),
                            Category = "DISHTYPE",
                            Code = "BBQ",
                            CreatedAt = new DateTime(2024, 12, 26, 8, 28, 11, 795, DateTimeKind.Utc).AddTicks(7202),
                            ImageUrl = "https://res.cloudinary.com/dhphzuojz/image/upload/v1735196328/default_storage/tag/dishtype/zl1f9g0dxxbtw2f4jiel.png",
                            IsActive = true,
                            UpdatedAt = new DateTime(2024, 12, 26, 8, 28, 11, 795, DateTimeKind.Utc).AddTicks(7202),
                            Value = "BBQ"
                        },
                        new
                        {
                            Id = new Guid("042dd338-3338-45a1-96c6-a1e2d0ca71ff"),
                            Category = "DISHTYPE",
                            Code = "SEAFOOD",
                            CreatedAt = new DateTime(2024, 12, 26, 8, 28, 11, 795, DateTimeKind.Utc).AddTicks(7208),
                            ImageUrl = "https://res.cloudinary.com/dhphzuojz/image/upload/v1735196329/default_storage/tag/dishtype/jhxdroetbjq9f57cixwj.png",
                            IsActive = true,
                            UpdatedAt = new DateTime(2024, 12, 26, 8, 28, 11, 795, DateTimeKind.Utc).AddTicks(7209),
                            Value = "Seafood"
                        });
                });

            modelBuilder.Entity("RecipeService.Domain.Entities.UserBookmarkRecipe", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RecipeId");

                    b.HasIndex("RecipeId");

                    b.ToTable("UserBookmarkRecipe");
                });

            modelBuilder.Entity("RecipeService.Domain.Entities.UserReportComment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CommentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CommentId");

                    b.ToTable("UserReportComment");
                });

            modelBuilder.Entity("RecipeService.Domain.Entities.UserReportRecipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.ToTable("UserReportRecipe");
                });

            modelBuilder.Entity("RecipeService.Domain.Entities.Comment", b =>
                {
                    b.HasOne("RecipeService.Domain.Entities.Recipe", "Recipe")
                        .WithMany("Comments")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("RecipeService.Domain.Entities.CommentVote", b =>
                {
                    b.HasOne("RecipeService.Domain.Entities.Comment", "Comment")
                        .WithMany("CommentVotes")
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comment");
                });

            modelBuilder.Entity("RecipeService.Domain.Entities.RecipeTag", b =>
                {
                    b.HasOne("RecipeService.Domain.Entities.Recipe", "Recipe")
                        .WithMany("RecipeTags")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RecipeService.Domain.Entities.Tag", "Tag")
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("RecipeService.Domain.Entities.RecipeVote", b =>
                {
                    b.HasOne("RecipeService.Domain.Entities.Recipe", "Recipe")
                        .WithMany("RecipeVotes")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("RecipeService.Domain.Entities.Step", b =>
                {
                    b.HasOne("RecipeService.Domain.Entities.Recipe", "Recipe")
                        .WithMany("Steps")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("RecipeService.Domain.Entities.UserBookmarkRecipe", b =>
                {
                    b.HasOne("RecipeService.Domain.Entities.Recipe", "Recipe")
                        .WithMany()
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("RecipeService.Domain.Entities.UserReportComment", b =>
                {
                    b.HasOne("RecipeService.Domain.Entities.Comment", "Comment")
                        .WithMany()
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comment");
                });

            modelBuilder.Entity("RecipeService.Domain.Entities.UserReportRecipe", b =>
                {
                    b.HasOne("RecipeService.Domain.Entities.Recipe", "Recipe")
                        .WithMany()
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("RecipeService.Domain.Entities.Comment", b =>
                {
                    b.Navigation("CommentVotes");
                });

            modelBuilder.Entity("RecipeService.Domain.Entities.Recipe", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("RecipeTags");

                    b.Navigation("RecipeVotes");

                    b.Navigation("Steps");
                });
#pragma warning restore 612, 618
        }
    }
}
