name: CI Pipeline

on:
  pull_request:
    branches: 
      - master
      - pipeline
  push:
    branches: 
      - master
      - pipeline
  workflow_dispatch:
    inputs:
      BUILD_SERVICES:
        description: "space-separated services"
        required: false
      DEPLOY_ENV:
        description: "'staging' or 'production'"
        required: true
        default: "staging"


jobs:
  detect:
    name: Detect changes
    runs-on: ubuntu-latest
    outputs:
      services: ${{ steps.detect.outputs.services }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Detect services
        id: detect
        run: |
          BUILD_SERVICES="${{ github.event.inputs.BUILD_SERVICES }}"

          if [ "$BUILD_SERVICES" != "" ]; then
            echo "Manual override: $BUILD_SERVICES"
            echo "services=$BUILD_SERVICES" >> $GITHUB_OUTPUT
            exit 0
          fi

          ./scripts/ci/detect-service-changed.sh
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: ${{ github.ref_name }}
  build:
    name: Build services
    runs-on: ubuntu-latest
    needs: detect
    if: ${{ needs.detect.outputs.services != '' }}
    env:
      INFISICAL_TOKEN: ${{ secrets.INFISICAL_TOKEN }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PAT: ${{ secrets.DOCKER_PAT }}
      GMAIL_TOKEN: ${{ secrets.GMAIL_TOKEN }}
      GMAIL_CREDENTIALS: ${{ secrets.GMAIL_CREDENTIALS }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Install dependencies
        id: install_deps
        run: |
          echo "Begin install deps"
          ./scripts/ci/install-deps.sh
          echo "End install deps"

      - name: Retrieve secrets
        id: ret_sec
        run: |
          echo "INFISICAL_TOKEN=${INFISICAL_TOKEN}" > .env.local
          ./scripts/env/pull-env.sh

          mkdir -p data/Auth.Store
          echo "${GMAIL_TOKEN}" > data/Auth.Store/Google.Apis.Auth.OAuth2.Responses.TokenResponse-user

          mkdir -p app/server/NotificationService/src/EmailWorker
          echo "${GMAIL_CREDENTIALS}" > app/server/NotificationService/src/EmailWorker/credentials.json

      - name: Login to Docker Hub
        uses: docker/login-action@v4
        # This does not expand env variable ${DOCKER_USERNAME} so i have to inject from object secrets
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PAT }}
      
      - name: Build services
        id: build_serv
        run: |
          SHORT_SHA=$(git rev-parse --short HEAD)
          ./scripts/docker/build-services.sh -c $SHORT_SHA -le ${{ github.event.inputs.DEPLOY_ENV || 'staging' }} ${{ needs.detect.outputs.services }}

