name: CI Pipeline

on:
  pull_request:
    branches: 
      - staging
  push:
    branches: 
      - master
      - staging
  workflow_dispatch:
    inputs:
      BUILD_SERVICES:
        description: "space-separated services"
        required: false
      DEPLOY_ENV:
        description: "'staging' or 'production'"
        required: true
        default: "staging"


jobs:
  detect:
    name: Detect changes
    runs-on: ubuntu-latest
    outputs:
      services: ${{ steps.detect.outputs.services }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Detect services
        id: detect
        run: |
          BUILD_SERVICES="${{ github.event.inputs.BUILD_SERVICES }}"

          if [ "$BUILD_SERVICES" != "" ]; then
            echo "Manual override: $BUILD_SERVICES"
            echo "services=$BUILD_SERVICES" >> $GITHUB_OUTPUT
            exit 0
          fi

          ./scripts/ci/detect-service-changed.sh
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: ${{ github.head_ref || github.ref_name }}
  build:
    name: Build services
    runs-on: ubuntu-latest
    needs: detect
    if: ${{ needs.detect.outputs.services != '' }}
    outputs:
      sha: ${{ steps.build_serv.outputs.sha }}
    env:
      INFISICAL_TOKEN: ${{ secrets.INFISICAL_TOKEN }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PAT: ${{ secrets.DOCKER_PAT }}
      GMAIL_TOKEN: ${{ secrets.GMAIL_TOKEN }}
      GMAIL_CREDENTIALS: ${{ secrets.GMAIL_CREDENTIALS }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Install dependencies
        id: install_deps
        run: |
          echo "Begin install deps"
          ./scripts/ci/install-deps.sh
          echo "End install deps"

      - name: Retrieve secrets
        id: ret_sec
        run: |
          echo "INFISICAL_TOKEN=${INFISICAL_TOKEN}" > .env.local
          ./scripts/env/pull-env.sh

          mkdir -p data/Auth.Store
          echo "${GMAIL_TOKEN}" > data/Auth.Store/Google.Apis.Auth.OAuth2.Responses.TokenResponse-user

          mkdir -p app/server/NotificationService/src/EmailWorker
          echo "${GMAIL_CREDENTIALS}" > app/server/NotificationService/src/EmailWorker/credentials.json

      - name: Login to Docker Hub
        uses: docker/login-action@v4
        # This does not expand env variable ${DOCKER_USERNAME} so i have to inject from object secrets
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PAT }}
      
      - name: Build services
        id: build_serv
        run: |
          SHORT_SHA=$(git rev-parse --short HEAD)
          echo "sha=$SHORT_SHA" >> $GITHUB_OUTPUT
          ./scripts/docker/build-services.sh -c $SHORT_SHA -le ${{ github.event.inputs.DEPLOY_ENV || 'staging' }} ${{ needs.detect.outputs.services }}
  update-manifest:
    name: Update service manifest in gitOps repository
    runs-on: ubuntu-latest
    needs: [detect,build]
    env:
      GITOPS_REPO_NAME: ${{ secrets.GITOPS_REPO_NAME }}
      GITOPS_REPO_TOKEN: ${{ secrets.GITOPS_REPO_TOKEN }}
    steps:
    - name: Checkout GitOps repo
      uses: actions/checkout@v6
      with:
        repository: ${{ secrets.GITOPS_REPO_NAME }}
        token: ${{ secrets.GITOPS_REPO_TOKEN }}
        ref: improve-ci
    - name: Check if Infisical secret file exists
      id: check_secret
      if: github.event_name == 'pull_request' && github.event.pull_request.base.ref == 'staging'
      run: |
        SECRET_FILE="k8s/bootstrap/infisical-operator/base/secrets/infisical-secrets-pr-${PR_NUMBER}.yaml"

        if [ -f "$SECRET_FILE" ]; then
          echo "exists=true" >> $GITHUB_OUTPUT
        else
          echo "exists=false" >> $GITHUB_OUTPUT
        fi
      env:
        PR_NUMBER: ${{ github.event.pull_request.number }}
    - name: Setup Infisical for dev environment
      if: github.event_name == 'pull_request' 
        && github.event.pull_request.base.ref == 'staging'
        && steps.check_secret.outputs.exists == 'false'
      run: |
        cd k8s/bootstrap/infisical-operator/base

        export SECRET_FILE="secrets/infisical-secrets-pr-${PR_NUMBER}.yaml"
        export APP_NAMESPACE="tastopia-pr-$PR_NUMBER"
        export MONITORING_NAMESPACE="monitoring-pr-$PR_NUMBER"
        export SUFFIX="pr-${PR_NUMBER}"

        yq '.spec.authentication.serviceToken.secretsScope.envSlug = "staging"' secrets/infisical-secrets.yaml \
          | yq '(.spec.managedKubeSecretReferences[] | select(.secretNamespace == "tastopia") | .secretNamespace) = strenv(APP_NAMESPACE)' \
          | yq '(.spec.managedKubeSecretReferences[] | select(.secretNamespace == "monitoring") | .secretNamespace) = strenv(MONITORING_NAMESPACE)' \
          | yq '.metadata.name = .metadata.name + "-" + strenv(SUFFIX)' \
          > "$SECRET_FILE"

        yq -i 'with(.resources; select(all_c(. != strenv(SECRET_FILE))) | . += strenv(SECRET_FILE))' ./kustomization.yaml

        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git commit \
          -m "Set up PR #${PR_NUMBER}" \
          -m "PR #${PR_NUMBER}: ${PR_TITLE} (${PR_URL})" \
          || echo "No changes"
        git push
      env:
        PR_NUMBER: ${{ github.event.pull_request.number }}
        PR_TITLE: ${{ github.event.pull_request.title }}
        PR_URL: ${{ github.event.pull_request.html_url }}
    - name: Update image tag
      run: |
        #!/bin/bash
        
        if [[ "${{ github.event_name }}" == "pull_request" ]]; then
          PR_NUMBER="${{ github.event.pull_request.number }}"
          VALUES_FILE="k8s/helm/values-pr-${PR_NUMBER}.yaml"
        else
          case "$BRANCH" in
            master) 
              VALUES_FILE="k8s/helm/values-production.yaml"
              ;;
            staging) 
              VALUES_FILE="k8s/helm/values-staging.yaml"
              ;;
            *) 
              echo Unsupported branch
              exit 1
              ;;
          esac
        fi

        if [ ! -f "$VALUES_FILE" ]; then
          if [ "$BRANCH" == "master" || "$BRANCH" == "staging" ]; then
            echo "Values file does not exist, please add it before running the workflow..."
            exit 1
          fi
          echo "Values file does not exist, creating..."
          cp "k8s/helm/values-staging.yaml" "$VALUES_FILE"
        fi

        for SERVICE in ${{ needs.detect.outputs.services }}; do
          echo "Updating $SERVICE..."
          IMAGE="taiduc113/tastopia-${SERVICE}:${{ needs.build.outputs.sha }}"
          sed -i "s|taiduc113/tastopia-${SERVICE}:.*|${IMAGE}|g" "$VALUES_FILE"
        done
      env:
        BRANCH: ${{ github.head_ref || github.ref_name }}
    - name: Commit & push
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

        git add .
        git commit -m "Update image to ${{ needs.build.outputs.sha }}" || echo "No changes"
        git push
