#!/bin/bash
name: CI Pipeline

on:
  pull_request:
    branches: 
      - master
      - pipeline
  push:
    branches: 
      - master
      - pipeline
  workflow_dispatch:
    inputs:
      BUILD_SERVICES:
        description: "Comma-separated services"
        required: false
      DEPLOY_ENV:
        description: "'staging' or 'production'"
        required: true
        default: "staging"


jobs:
  build:
    runs-on: ubuntu-latest
    env:
      INFISICAL_TOKEN: ${{ secrets.INFISICAL_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Detect services
        id: detect
        run: |
          BUILD_SERVICES="${{ github.event.inputs.BUILD_SERVICES }}"

          if [ "$BUILD_SERVICES" != "" ]; then
            echo "Manual override: $BUILD_SERVICES"
            echo "services=$BUILD_SERVICES" >> $GITHUB_OUTPUT
            exit 0
          fi

          ./scripts/ci/detect-service-changed.sh

      - name: Install dependencies
        id: install_deps
        run: |
          echo "Begin install deps"
          ./scripts/ci/install-deps.sh
          echo "End install deps"

      - name: Retrieve secrets
        id: ret_sec
        run: |
          echo "INFISICAL_TOKEN=${INFISICAL_TOKEN}" > .env.local
          ./scripts/env/pull-env.sh

          mkdir -p data/Auth.Store
          echo "${{ secrets.GMAIL_TOKEN }}" > data/Auth.Store/Google.Apis.Auth.OAuth2.Responses.TokenResponse-user

          mkdir -p app/server/NotificationService/src/EmailWorker
          echo "${{ secrets.GMAIL_CREDENTIALS }}" > app/server/NotificationService/src/EmailWorker/credentials.json

      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PAT }}
      
      - name: Build services
        id: build_serv
        run: |
          echo "Public shared library"
          dotnet publish --packages "$(pwd)/data/nuget" \
            -o ./app/server/Contract/Contract/Published \
            ./app/server/Contract/Contract

          SHORT_SHA=$(git rev-parse --short HEAD)
          ./scripts/docker/build-services.sh -c $SHORT_SHA -le ${{ github.event.inputs.DEPLOY_ENV || 'staging' }} ${{ steps.detect.outputs.services }}

