version: 1
disable_existing_loggers: True
formatters:
  colored:
    "()": colorlog.ColoredFormatter
    format: '%(log_color)s[%(asctime)s %(levelname)s]%(reset)s %(name)s - %(message)s'
    datefmt: '%H:%M:%S'
    log_colors:
      DEBUG: "cyan"
      INFO: "green"
      WARNING: "yellow"
      ERROR: "red"
      CRITICAL: "bold_red"
handlers:
  console:
    class: logging.StreamHandler
    formatter: colored
    stream: ext://sys.stdout
filters:
  health_filter:
    "()": "filters.HealthFilter"  # make sure my_filters.py is importable
loggers:
  uvicorn.error:
    level: INFO
    handlers: [console]
    propagate: no
  uvicorn.access:
    level: INFO
    filters: [health_filter]
    handlers: [console]
    propagate: no
root:
  level: INFO
  handlers: [console]
