apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: ./ingresses/api-gateway.hydrated.yaml
    target:
      kind: Ingress
      name: api-gateway
  - path: ./ingresses/identity-api.hydrated.yaml
    target:
      kind: Ingress
      name: identity-api
  - path: ./ingresses/consul.hydrated.yaml
    target:
      kind: Ingress
      name: consul
  - path: ./ingresses/rabbitmq.hydrated.yaml
    target:
      kind: Ingress
      name: rabbitmq
  - path: ./ingresses/website.hydrated.yaml
    target:
      kind: Ingress
      name: website
